### ISSUE TITLE
HOLY SHIT IT'S LOOSE levels of lag

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#100]
Likely from a combination of runtimes and poor atmos performance.
Definitely needs some fixing.

**Comment by LetterJay** [comment]
https://github.com/tgstation/tgstation/commit/83e4404f7b56dc1bb5db86a949134edeb2167e46

**Comment by ghost** [comment]
why don't we just update to latest LINDA and solve all our problems that way

**Comment by TalkingCactus** [comment]
I already ported planetary atmos a long ass time ago

**Comment by LetterJay** [comment]
Added nullcheck value as pointed out by @PJB3005. This seems to still be the primary cause. It's been roughly two days and it hasn't happened yet. Still keeping an eye on the logs.

**Comment by LetterJay** [comment]
http://pastebin.com/crCn7i0d
http://pastebin.com/yHJ9t89n

**Comment by ghost** [comment]
wew

**Comment by LetterJay** [comment]
Marking this as fixed since it was mainly due to the ruins. which is all fixed in the branch merge.
