### ISSUE TITLE
Womb not working properly

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#1000]
Hi. Femcum liquid is not generated, even though womb is enabled in my character. In the code of womb organ on_life() is absent, and generate_x() is absent. Please fix it

**Comment by Poojawa** [comment]
Does your character also contain a vagina? Since that would understandably be needed for it as well.

**Comment by ghost** [comment]
Both. Also, compare breasts, testicles and womb code. First two have on_life() and generate_cum() or generate_milk() procs. Womb doesn't. Also, in cit_arousal only code for penis is implemented, so it also should be fixed. If developers don't agree to do it, I'll make a pull request later.

**Comment by Poojawa** [comment]
@TalkingCactus 

Also, if you know how to fix it, feel free to. We always welcome extra help.

**Comment by ghost** [comment]
Okay
Will do after match

**Comment by ghost** [comment]
BYOND account is Nitroethylene

**Comment by TalkingCactus** [comment]
It's not bugged, just not implemented (Though you seem to have figured that out).

**Comment by ghost** [comment]
Request 1108 got merged.
