### ISSUE TITLE
Can't fireman carry after someone gets hit with a rod

### ISSUE THREAD

**Issue by Daggertail** [citadel-station/citadel-main#10013]
[Round ID]: # 20332
<img width="403" alt="videogames" src="https://user-images.githubusercontent.com/5742277/69892338-fb2d5500-12c9-11ea-92ab-edefbfb5b8c9.png">

## Reproduction:
Someone gets hit by a rod, even if they are killed you can't carry them. they are still considered standing.

helper stands in front of rod
get hit
Can't carry them.

**Comment by Ghommie** [comment]
Probably a little issue with #9892. It'll be fixed soon I guess.

**Comment by Putnam3145** [comment]
more likely with #9894, since it's ex_act that penetrate calls
