### ISSUE TITLE
(Feature Request) Buildable Trash Bins

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10020]
I've seen trash bins on a few of the shuttles, VR locations, and other assorted areas. The idea of bins is really cool, but they're almost never used in mapping (because of disposals), and are completely unbuildable for those who'd like to use them. (Maint Bar, Maintenance Bases, Large Dorms.) It would be really nice to actually make them a bit more relevant by making them buildable/craftable.

The only thing I have for bins right now is their object string.

/obj/structure/closet/crate/bin

**Comment by ghost** [comment]
not an issue
