### ISSUE TITLE
Arena shuttle cant be bought

### ISSUE THREAD

**Issue by Arturlang** [citadel-station/citadel-main#10065]

**Comment by Ghommie** [comment]
Likely sources of such issue could be:
1) The medals' subsystem hub not being enabled. (If that's so I guess we should just datumize achievements like tgstation did and migrate them to the DB, and work around this specific issue too).
2) Said megafauna being admin spawn.
3) Proc runtiming somewhat.
4) An admin messing around and var editing said megafauna to screw over people.
