### ISSUE TITLE
You can no longer click+drag pdas to any part of your screen to open their interface.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10089]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
This was neat because then you wouldn't have to put it in your hand. Instead it just puts it in your hand now.

**Comment by Ghommie** [comment]
@deathride58, could you deal with this and #10087, pretty please? No malice, I'm just tired right now.

**Comment by Ghommie** [comment]
More or less fixed now that the alternative click dragging option by Bhjin is combat mode only.
