### ISSUE TITLE
Nanites sensor should be able to detect stamina.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10081]
Health analyzers already report 'fatigue', nanites should be able to do as well.

**Comment by Putnam3145** [comment]
Nanite sensor like the health sensor nanites? Cause that would be literally insanely powerful, passive auto-adrenals is bad.

**Comment by GrayRachnid** [comment]
It detects health/brute/burn/toxin/suffocation damage. Stamina damage should be considered /damage/ as well and the fact that certain things leave it out is inconsistent. Nerf it after you add it, but add it for the sake of consistency.
