### ISSUE TITLE
Slimes are taking Toxin Damage for Literally No Reason

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10104]
## Round ID:
20445

## Testmerges:
#10082: 'Bluespace launchpad QoL (read: powercreep)' by kevinz000 at commit 2d9c6e64c5
#9894: '[TESTMERGE] Explosion/bomb armor rework' by Putnam3145 at commit c40cad1658
#10083: 'Fixes space hermit asteroid rocks unintendedly spawning airless asteroid turf when mined, save for the perimeter.' by Ghommie at commit e0caf6007b
#10011: '[READY]Bloodsuckers, or, yknow, vampires.' by Arturlang at commit 4711eb0987
#9928: '[READY]Even more organ tweaks!' by Thalpy at commit f3813e35bb

## Reproduction:
Attempt to play as a slime.

**Comment by Ghommie** [comment]
Most likely caused by the last testmerge on the list.

**Comment by Thalpy** [comment]
Hmm yes this is a vampire thing.

_aaaa I'll fix asap_

**Comment by Arturlang** [comment]
I can test if it might be?

**Comment by Arturlang** [comment]
Nope, not due to vamps

**Comment by Thalpy** [comment]
Oh no sorry, I was being silly. It's me.
