### ISSUE TITLE
Picking up a deck of cards from a table still makes you draw a card.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10105]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
I believe this shouldn't be happening.

**Comment by Ghommie** [comment]
@deathride58, sorry for not having reviewed your PR there.

**Comment by Ghommie** [comment]
More or less fixed now that the alternative click dragging option by Bhjin is combat mode only.
