### ISSUE TITLE
Screaming Can Be Used to Escape Kindle

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10107]
## Round ID:
20446

## Testmerges:
#10011: '[READY]Bloodsuckers, or, yknow, vampires.' by Arturlang at commit 4711eb0987
#10083: 'Fixes space hermit asteroid rocks unintendedly spawning airless asteroid turf when mined, save for the perimeter.' by Ghommie at commit e0caf6007b
#9894: '[TESTMERGE] Explosion/bomb armor rework' by Putnam3145 at commit c40cad1658
#10082: 'Bluespace launchpad QoL (read: powercreep)' by kevinz000 at commit 2d9c6e64c5

## Reproduction:
Spam scream while kindled, the oxyloss shortens the duration significantly.

**Comment by Ghommie** [comment]
Emote spam in general is an issue. :smirk:
