### ISSUE TITLE
Emitter hit everything on a tile

### ISSUE THREAD

**Issue by r4d6** [citadel-station/citadel-main#10118]
Emitters hit every object on the tile when hitting something

## Reproduction:
Place a locker on top of visible pipes, then shoot it with an emitter, watch as the pipes get damaged too.

Place pipes under a supermatter crystal, see that they don't get disintegrated, turn on the emitter, watch as the beams hit the SM but unwrench the pipes below it as well.

Watch as the beam fly over every other pipes in the way.

**Comment by GrayRachnid** [comment]
This also applies to lasers.

**Comment by r4d6** [comment]
Good to know.

**Comment by r4d6** [comment]
I searched on TG, and apparently this is a bug, not fixed, dating back to **April 2018**,
Also apparently it is due to projectiles hitting everything on a turf when hitting something, and @kevinz000 was mentionned too, so I think it is because of him or something.

Also this issue seem to indicate the beginning of it : https://github.com/tgstation/tgstation/issues/44143
another one : https://github.com/tgstation/tgstation/issues/37247

**Comment by Ghommie** [comment]
The former issue is not even related to emitters, but to an anti-tactical crawling tweak from after crawling was added to tgstation.
Kevinz did actually fix the latter in tgstation PR #42241 over a year ago, yet did not mention to close it in the description.
I'll proceed to make a fix based on said PR later.

**Comment by r4d6** [comment]
ok
