### ISSUE TITLE
Character Preview breaks when you open the Character Appearance tab.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10117]
## Round ID:
 20455 

## Testmerges:
#10082: 'Bluespace launchpad QoL (read: powercreep)' by kevinz000 at commit 83ab577a6a 
#9894: '[TESTMERGE] Explosion/bomb armor rework' by Putnam3145 at commit c40cad1658 
#10083: 'Fixes space hermit asteroid rocks unintendedly spawning airless asteroid turf when mined, save for the perimeter.' by Ghommie at commit e0caf6007b 
#10011: 'Bloodsuckers, or, yknow, vampires.' by Arturlang at commit 4711eb0987 

## Reproduction:
Be ingame, go to preferences and open `Game Preferences`. Char preview loads up fine. Click on any other tab, it breaks.
I was a ghost.

**Comment by GrayRachnid** [comment]
To continue, only the Avian and Digitigrade legs load the preview fine. Plantigrade legs break it. Anthromorphic mushrooms are completely invisible. Plasmamen are completely invisible.

**Comment by Ghommie** [comment]
May be a sneaky issue with prefs copy_to raised by #10057. I'll look into it soon.
