### ISSUE TITLE
Fireman Carry is a QOL Nightmare because it overrides an attempt to strip someone you have aggro/neck grabbed. It is also a huge balance concern due to how easy it makes it to transport people without slowdown/blood.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10110]
Some changes need to be made, maybe find a different way to initiate it?

Also, it needs slowdown added onto it or /something/ other than simple taking one arm slot.

The person being fireman carried also needs some restrictions, currently they can use both hands. You can technically fireman carry someone wielding an L6 while the person running has an energy shield on nukeops, or do the same for sec but with a beam rifle.

**Comment by ghost** [comment]
looking at this rn but if ghommie wants to fix it faster then feel free

**Comment by Ghommie** [comment]
No, thanks, I already fixed (I hope) some bugs with it. And I really have other things to focus around. :sweat_smile:

**Comment by Owai-Seek** [comment]
The solution is clear, all guns should be two-handed weapons.

**Comment by necromanceranne** [comment]
It was added to tg because it was made that dragging people caused you to suffer slowdown. Fairly hefty slowdown at that. It is a genuine balance concern because without the slowdown you can quite easily transport two people at once without any real detriment.

**Comment by B1gb3ast** [comment]
make fireman carry combat mode only.
fixt?

**Comment by Ghommie** [comment]
These issues have been addressed in a recent PR by kevinz.
