### ISSUE TITLE
Blood loss from bullets needs a serious look at.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10124]
## Round ID:
20460

## Testmerges:
N/A

## Reproduction:
Gang round, I get my chest augmented and grab a bulletproof armor vest. Get shot up by an Uzi as expected, I got hit around 12 times by my approximation and didn't take much brute damage but almost passed out from blood loss about 2 minutes later.

**Comment by Ghommie** [comment]
Fixed now that boolets don't sap away blood like sponges anymore.
