### ISSUE TITLE
drones can bleed

### ISSUE THREAD

**Issue by dapnee** [citadel-station/citadel-main#10149]
Round 20491: hit self with tile by accident, blood goes onto the ground.

**Comment by Arturlang** [comment]
Caused by bloodsuckers, fixed loccally and will push soonish.

**Comment by GrayRachnid** [comment]
slimes can also bleed

**Comment by Ghommie** [comment]
Arturlang should have fixed this issue by now since that bloodsuckers are in.
Feel free to open another issue in case I'm wrong.
