### ISSUE TITLE
Stabilized Metal Extracts don't do anything

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10146]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
It's supposed to spawn a random mineral every 30 seconds.

**Comment by Ghommie** [comment]
To be exact, It's supposed to increase the amount of a random sheet stack found by the recursive `GetAllContents()` proc, not spawn new ones.
Only issue I can see right away is how it just increments the amount var, no proc call or anything.

**Comment by GrayRachnid** [comment]
https://i.imgur.com/ezxB5uh.png

**Comment by Ghommie** [comment]
Yes, please explain how it's broken, and perhaps I'll fix that too.

**Comment by GrayRachnid** [comment]
It doesn't spawn any materials.

**Comment by GrayRachnid** [comment]
OH.

**Comment by GrayRachnid** [comment]
IT ADDS A STACK TO WHATEVER MATERIAL YOU ALREADY HAVE. I'M DUMB

**Comment by Ghommie** [comment]
Don't worry, we all make these sort of mistakes. :joy:
