### ISSUE TITLE
Laughter/Slaughter demons bleed when hit by bullets.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10175]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>Clean an area and entrap a demon
>Buckshot
>He bleeds
>He leaves

**Comment by GrayRachnid** [comment]
#10124 probably related

**Comment by Putnam3145** [comment]
probably a duplicate of #10149

**Comment by Ghommie** [comment]
Should have been fixed by now since that bloodsuckers are in.
Feel free to open another issue in case I'm wrong.
