### ISSUE TITLE
hypovials don't splash their reagents when thrown

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10201]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
A

**Comment by Ghommie** [comment]
They were originally made to not spill their liquids when thrown, but I guess this could still be considered a consistency issue.

**Comment by GrayRachnid** [comment]
I'm just trying to empty those vials quickly bah

**Comment by Poojawa** [comment]
It's a sealed container, just use the chem master
