### ISSUE TITLE
Slime subspecies can't wag their own tails.

### ISSUE THREAD

**Issue by BlueWildrose** [citadel-station/citadel-main#10222]
Self explanatory - any non-roundstart slime species can't wag their tails if they have them.

I actually know how to fix this, but I don't really have access to making new branches and then creating pull requests with them.

**In code\modules\mob\living\carbon\human\species_types\jellypeople.dm -**

**Take:**

/datum/species/jelly/roundstartslime/spec_death(gibbed, mob/living/carbon/human/H)
	if(H)
		stop_wagging_tail(H)

/datum/species/jelly/roundstartslime/spec_stun(mob/living/carbon/human/H,amount)
	if(H)
		stop_wagging_tail(H)
	. = ..()

/datum/species/jelly/roundstartslime/can_wag_tail(mob/living/carbon/human/H)
	return ("mam_tail" in mutant_bodyparts) || ("mam_waggingtail" in mutant_bodyparts)

/datum/species/jelly/roundstartslime/is_wagging_tail(mob/living/carbon/human/H)
	return ("mam_waggingtail" in mutant_bodyparts)

/datum/species/jelly/roundstartslime/start_wagging_tail(mob/living/carbon/human/H)
	if("mam_tail" in mutant_bodyparts)
		mutant_bodyparts -= "mam_tail"
		mutant_bodyparts |= "mam_waggingtail"
	H.update_body()

/datum/species/jelly/roundstartslime/stop_wagging_tail(mob/living/carbon/human/H)
	if("mam_waggingtail" in mutant_bodyparts)
		mutant_bodyparts -= "mam_waggingtail"
		mutant_bodyparts |= "mam_tail"
	H.update_body()

**Move it below the data for datum/species/jelly, remove "roundstartslime/" from each one, good to go. Like so:**

/datum/species/jelly/spec_death(gibbed, mob/living/carbon/human/H)
	if(H)
		stop_wagging_tail(H)

/datum/species/jelly/spec_stun(mob/living/carbon/human/H,amount)
	if(H)
		stop_wagging_tail(H)
	. = ..()

/datum/species/jelly/can_wag_tail(mob/living/carbon/human/H)
	return ("mam_tail" in mutant_bodyparts) || ("mam_waggingtail" in mutant_bodyparts)

/datum/species/jelly/is_wagging_tail(mob/living/carbon/human/H)
	return ("mam_waggingtail" in mutant_bodyparts)

/datum/species/jelly/start_wagging_tail(mob/living/carbon/human/H)
	if("mam_tail" in mutant_bodyparts)
		mutant_bodyparts -= "mam_tail"
		mutant_bodyparts |= "mam_waggingtail"
	H.update_body()

/datum/species/jelly/stop_wagging_tail(mob/living/carbon/human/H)
	if("mam_waggingtail" in mutant_bodyparts)
		mutant_bodyparts -= "mam_waggingtail"
		mutant_bodyparts |= "mam_tail"
	H.update_body()

**Super easy I believe.**

_(I just want my wiggly tentacles when I change subspecies please fix this)_

**Comment by Ghommie** [comment]
This should be fixed now. Someone close it please.

**Comment by BlueWildrose** [comment]
Thanks!
