### ISSUE TITLE
SO MANY PEOPLE ARE PALE

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10236]
Literally like, every other person I see has pale skin despite saying they dont have any of the blood disorders, they arent a vampire, undead, ect. This REALLY fucks with medical treatment.

https://www.youtube.com/watch?v=hdzH_aSL-6k

**Comment by Arturlang** [comment]
Its due to people having the ALBINO skin colour, i think, if they dont have it it might be borked and ill need more info

**Comment by Ghommie** [comment]
Albinos being pale is intended (duh), yet it doesn't check if the current species uses skin tones or not. Very easy to fix.
