### ISSUE TITLE
wizard fireball hits corpses and people laying down even if not aiming for them

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#10258]
## Reproduction:
kill someone, use fireball at someone across the room, die to point-blank fireball
think this might be from @Ghommie's projectile code ports

**Comment by Ghommie** [comment]
Uh, that's testmerged? Interesting.

**Comment by YakumoChen** [comment]
Intended though, it reacts on the first mob the spell touches, via proximity.
