### ISSUE TITLE
Random characters almost always have wings

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#10271]
I noticed randomized characters now always have wings if applicable, messing with a slime mulligan made me usually have moth wings, along with other head and tail stuff, which usually looks weird and not believable, important for trying to mulligan or something.

**Comment by Ghommie** [comment]
Will likely be fixed in #10230.

**Comment by DeltaFire15** [comment]
Thats just how character randomization works as of now.
