### ISSUE TITLE
Dynamic spawning is broken?

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#10273]
Issue reported from  Round ID: 20642 (Citadel Station 13)

Reporting client version: 512

During this round it asked for Pirates, Abductors and a Wizard (twice).  Yes was hit on all the options but none were spawned in.  The pirate spawners (the sleepers) DID work, but the other two failed to spawn despite hitting yes on the options.

**Comment by Arturlang** [comment]
Any idea how many ghosts there were?

**Comment by Ghommie** [comment]
I heard this was an issue with a testmerge but was fixed later, maybe I am wrong though. @Putnam3145

**Comment by Ghommie** [comment]
They did quite a handful of tweaks and fixes since then I'm pretty sure this has been handled.
