### ISSUE TITLE
Remove Obfuscation of alarm levels and Intermission Intersections 

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#10280]
> Please be aware that feature discussions most often take place on the Citadel Station Discord and should not be requested here.
>
Simple put, Make the round always start on green, and remove the whole "Rng to be blue"
This does a few things
1) Makes blue mean something again like low threats - Traitors/lings
2)We already are allowed to legit do all 3 station goals, why  not give us the go for them every shift?
3) Makes fake reports no longer a thing on round start meaning CC is more trustworthy!
4) Still makes the round not-meta
5) Makes Raising to blue/amber mean more as no one should have known baddies were on the station.
6) Makes amber more able to mean higher threats - Rouge bots/Cults

**Comment by Ghommie** [comment]
Suggestions like these shouldn't belong in the issues section.
Alert levels and roundstart command reports are rather simple already and do no need to be made useless or removed, imo.
