### ISSUE TITLE
Cargo Balance Issue

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10294]
## Reproduction:

Cigarettes give you way too much money and you can buy restocking kits for the vendor. Keep restocking the vendor, sell the cigs, and you make an obscene amount of money. Service borgs can print cigs and you get the same effect. 

This was like, less than 10 vendor kits, which only "cost" 800 each. Even at 10 kits. that's only 8000 credits for over 100k in cigs.

![image](https://user-images.githubusercontent.com/7543955/71459477-afa98200-2775-11ea-98f3-6342083d9e25.png)

**Comment by ghost** [comment]
@Trilbyspaceclone i blame you


why did you make all /drug's worth 12 credits 😳

**Comment by Ghommie** [comment]
I'm quite worried this can also be replicated with other vendor refills such as nanomed, booze-o-mat, space cola vendors etcetera.
Pricing of easily achievable reagents needs to be dunked, refill packs cost increased, and possibly goofconomy to stop this issue.

**Comment by Trilbyspaceclone** [comment]
@kappa-sama Cuz I didnt think Nico was a drug. Thought it was in Medical/Food chems :/
@Ghommie also booze mat/nanomed can net a good worth, but its better to use the autobottler and get even more.
