### ISSUE TITLE
One of the RCD Models doesn't work properly.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10302]
## Reproduction:

Not really sure, got it as a Christmas gift and not sure which RCD it is or where it comes from. It comes with deconstruction included, but cannot actually place or deconstruct anything.

![image](https://user-images.githubusercontent.com/7543955/71494873-7b3ad200-2818-11ea-8d05-2248a32a5cf6.png)

**Comment by Ghommie** [comment]
I could say that was indeed a syndicate cyborg RCD, not meants to be usable nor accessible by other mobs.
Yet there is no easy way to define which christmase present shouldn't be rolled as it would require someone to scroll through all item subtypes. Perhaps in a near future, who knows.
