### ISSUE TITLE
official #10265 dump post

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#10314]
pr #10265 bugs:

1) the newly added doors in hop/captains office are part of no area and have space underneath
2) the strip club door to maint ^
3) no camera in the vault entrance, only in the vault
4) wiring issues from sm->smes and smes->gravgen

will add more as i find them

**Comment by ghost** [comment]
https://gyazo.com/94b5b478b47b1445807d97db7745796e

**Comment by Ghommie** [comment]
Probably fixed on #10317. hopefully.
