### ISSUE TITLE
Stims didn't prevent me from getting stunned from a Stun Baton.

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#10341]
Issue reported from  Round ID: 20727 (Citadel Station 13)

Reporting client version: 512

Stims didn't prevent me from getting stunned from a Stun Baton.

**Comment by Trilbyspaceclone** [comment]
Stims prevent stuns, not knockdown nor stam loss

**Comment by YakumoChen** [comment]
Stims give you high stamina regen and significantly reduce stun times but are not full immunity to non-lethals.

**Comment by deathride58** [comment]
Stims are not intended to be a knockdown immunity source here. They're primarily for hardstun reduction and stamina regen. Not a bug.
