### ISSUE TITLE
Dogborg analyzer does not analyze.

### ISSUE THREAD

**Issue by Strazyplus** [citadel-station/citadel-main#10359]

**Comment by GrayRachnid** [comment]
This is intended. The dogborg noses are now only for booping and not for analyzing. Not a bug.

**Comment by Owai-Seek** [comment]
Is it still called an Analyzer? Should rename it to a boop module or something.

**Comment by Ghommie** [comment]
@BlackMajor I think doggies nose and tongue fluff items shouldn't be a subtype of the legacy analyzer and soap ones.

**Comment by BlackMajor** [comment]
> @BlackMajor I think doggies nose and tongue fluff items shouldn't be a subtype of the legacy analyzer and soap ones.

Ye sayin' I oughta just make them their own type?

I forgot to change their name to booper, whoops.

**Comment by Ghommie** [comment]
Yea, they should have their own types to avoid issues like these.
