### ISSUE TITLE
Cryo Pods (or tablets) sometimes drop a standard battery on cryo.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10382]
## Reproduction:

I'm actually unsure how to reproduce it, but hell, I don't even know if it's actually a bug or not. I've just seen it happen fairly often and it seems a bit odd to be coincidental.

![image](https://user-images.githubusercontent.com/7543955/71638090-74e79400-2c24-11ea-8ac2-ff9b954eabd7.png)

**Comment by Trilbyspaceclone** [comment]
Oh hey those things, likely from Tablets tbh

**Comment by Ghommie** [comment]
^

**Comment by YakumoChen** [comment]
It's a problem with qdel. Qdel deletes most items, but some containers like tablets are not de-spawned on qdel.
