### ISSUE TITLE
Alt Clicking Tiles to See Item Lists Feels Less Responsive

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10385]
## Round ID:
N/A, noticed it for about a week

## Testmerges:
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit 1b6359a175
#10317: 'Corrects issues with box map' by Trilbyspaceclone at commit 9adb7a718d
#10224: 'Makes trait blacklisting remove random positives instead of removing every quirk (new and improved)' by Seris02 at commit 551e9f540d
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10189: 'Storytellers for Dynamic' by Putnam3145 at commit 444f862a4d
#10170: 'kneecaps tasers - makes taser knockdown require stamloss, nerfs taser stamloss, and removes the status effect's combat mode disabling' by deathride58 at commit 2d8d6eda11
#10305: 'Various Mining borg changes. And some extras.' by BlackMajor at commit 8085022d97
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10191: 'Custom Holoforms for pAIs and AIs oh and adds certain cyborg pai holograms. also mild pai nerf.' by kevinz000 at commit 094d225874

## Reproduction:
Lately it feels like it takes longer for the item list to appear, and it can disappear shortly after coming up with no action on the user's part.

**Comment by ghost** [comment]
intentional change
#10246

**Comment by IronEleven** [comment]
That's unfortunate, it feels borderline-useless now.
