### ISSUE TITLE
Gibs shoot too far.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10381]
## Reproduction:

Butcher some stuff and watch as the gibs rocket across the screen, painting the halls with blood until a wall finally stops the rampage.

![image](https://user-images.githubusercontent.com/7543955/71638084-29cd8100-2c24-11ea-9698-8723f980f897.png)

**Comment by GrayRachnid** [comment]
This usually happens in low-pressure or no-gravity. Was it either of those?

**Comment by Owai-Seek** [comment]
It was not, normal gravity/pressure on the station as far as I could tell, wasn't getting any lack of oxygen, gravity was on, no KPA notice.

I've also seen it happening with botanists tossing blood tomatoes.

**Comment by Ghommie** [comment]
Fixed in a "soft" revert of Pooj's blood rework.
