### ISSUE TITLE
Tables near Sec on Box are structures instead of Tables

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10392]
Issue reported from  Round ID: 20772 (Citadel Station 13)

Reporting client version: 512

![image](https://user-images.githubusercontent.com/7543955/71648190-512d5800-2ccf-11ea-8b97-a56a492ef8b2.png)

Something to note: These dont work as tables at all. You cant place things on them and you can walk over them.

**Comment by Tupinambis** [comment]
: )

**Comment by Ghommie** [comment]
Should have been fixed.
: )
