### ISSUE TITLE
Dermal Buttons Do Not Have Icons

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10422]
## Round ID:
20803

## Testmerges:
#10305: 'Various Mining borg changes. And some extras.' by BlackMajor at commit a4d2ea0281
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit 1b6359a175
#10317: 'Corrects issues with box map' by Trilbyspaceclone at commit 304ac7b20b
#10224: 'Makes trait blacklisting remove random positives instead of removing every quirk (new and improved)' by Seris02 at commit a6a110bca3
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10170: 'kneecaps tasers - makes taser knockdown require stamloss, nerfs taser stamloss, and removes the status effect's combat mode disabling' by deathride58 at commit 2d8d6eda11
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10191: 'Custom Holoforms for pAIs and AIs oh and adds certain cyborg pai holograms. also mild pai nerf.' by kevinz000 at commit 094d225874
#10409: 'IT WORKED ON LOCAL' by kevinz000 at commit b793bceffc
#10419: 'HELP I CANT POWERGAME NANITES IF I CANT MAKE NANITE MACHINES (please testmerge these things more)' by kevinz000 at commit 04649efc62

## Reproduction:
I made a program with four buttons.  Plus, minus, and power icons were used.  When the skin buttons were activated via remote, they had no icons, only blank buttons with tooltips.

**Comment by Arturlang** [comment]
@keronshb

**Comment by keronshb** [comment]
Thanks for pointing this out!  Made a PR to fix it - https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10472
