### ISSUE TITLE
Floor lights layer

### ISSUE THREAD

**Issue by SandPoot** [citadel-station/citadel-main#10448]
## Round ID:
LOCALHOST

## Testmerges:
LAST VERSION

## Reproduction:
There's not really a reproduction, like, make a floor light then stand on it and you'll see it kinda transparent and you can't easily click on yourself

**Comment by Ghommie** [comment]
Lights visual overlays use a fairly high plane value so they can be seen better in dark areas, and thus will show up above mobs.

**Comment by Ghommie** [comment]
Turns out it's not a visual overlay.
