### ISSUE TITLE
limbs are taking horrendously lowered damage from bullets

### ISSUE THREAD

**Issue by Hatterhat** [citadel-station/citadel-main#10476]
## Round ID:
local tested today (1/7/2020), brought to my attention earlier
## Testmerges:
none on local
## Reproduction:
- shoot a guy in the arm
- realize that the damage is horrendously low
- shoot the guy in the chest
- realize that the damage is correct, now

**Comment by Ghommie** [comment]
Ummmh, should have been fixed on #10483, right?
