### ISSUE TITLE
Medical borg hypo and health scanner chemical scans

### ISSUE THREAD

**Issue by Echopsychotic** [citadel-station/citadel-main#10517]
## Round ID:
20919

## Testmerges:

The following pull requests are currently test merged:
#10450: '(is this really a good idea) hitscan emitters' by kevinz000 at commit 39461e2806
#10416: 'Massive RCD Port & Updates' by r4d6 at commit 581654f13f
#10464: 'adds key_cache[] resets to the returns added by #10443 (obsolete now)' by deathride58 at commit 7ddf14258f
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit 1b6359a175
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10170: 'kneecaps tasers - makes taser knockdown require stamloss, nerfs taser stamloss, and removes the status effect's combat mode disabling' by deathride58 at commit 2d8d6eda11
#10409: 'IT WORKED ON LOCAL' by kevinz000 at commit 62b8513795
#10417: 'Nightshift improvements: public area settings/levels, nightshift auth requirement change, config changes, etc etc' by kevinz000 at commit 8725ffe916

## Reproduction:
Borgs hypo sprays show more than needed.
Medical scanners also fail to show any signs of chemicals when chems were injected. Rather it only shows that the scanner has been used but no results appear.

![Borg stuff](https://user-images.githubusercontent.com/58645053/72197864-dc9f9b00-33eb-11ea-9ddd-03a73dc967b0.png)

**Comment by ghost** [comment]
it also doesn't show blood type
