### ISSUE TITLE
Arousal system is not producing any breast milk when used in any fashion.

### ISSUE THREAD

**Issue by CharAznable117** [citadel-station/citadel-main#10514]
Round ID: 20198

## Reproduction:
I had gone through my usual routine, and I found out during RPing that I could not fill any container while using the arousal mechanics to fill any containers with milk from milking breasts. 

I have tried this on two separate rounds (the one mentioned and the one before this). I used several different containers from drinking glasses to beakers to flasks and none worked. I then tried using ejaculate created from the arousal system and that manages to work. I did no modifications such as Breast enlargement pills and made sure lactation was on for the character.  

1.let arousal meter fill
2. went through the commands through sexual activity by clicking on arousal meter with beaker in hand. clicked on fill container/climax alone/let fluids spill out.
3. observed no containers being dispensed despite receiving messages saying it had started/filled the container with liquid or even any stains on the floor from spilling the result onto the floor from climax.

**Comment by Putnam3145** [comment]
Arousal does not produce milk, genitals produce their fluids independently, regardless of arousal or even if you have it enabled (yes, seriously). If you're cumming repeatedly, you won't have much fluid, because the fluid generates rather slowly.

**Comment by CharAznable117** [comment]
The thing is this the genitals were not producing milk at all, despite this being far into the round (roughly 30minutes and over to almost 1hour and more) at both occurrences. Even on their first use. Using the vagina however for fluids however filled the container every single time but the breasts for milk failed to produce any at all.
