### ISSUE TITLE
APCS not interactable

### ISSUE THREAD

**Issue by Erokusan** [citadel-station/citadel-main#10529]
Round ID: 20922
Player (if applicable): Ekeci-The-Great-Star
Your BYOND name: Erokusan
Reason for a-help: I am unable to change anything about any APC as the AI, admin could also not alter anything about the APC

Basically, silicons and admins seem unable to interact with APC controls

**Comment by Ghommie** [comment]
An issue with a testmerged PR that was recently fixed
