### ISSUE TITLE
Gibtonite Explodes Instantly When Pickaxed

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10534]
## Round ID:
20930

## Testmerges:
#10521: 'Fixes roundstart borg spawns, plus a little bit extra.' by BlackMajor at commit 30fc5b560b
#10450: '(is this really a good idea) hitscan emitters' by kevinz000 at commit 39461e2806
#10416: 'Massive RCD Port & Updates' by r4d6 at commit 581654f13f
#10464: 'adds key_cache[] resets to the returns added by #10443 (obsolete now)' by deathride58 at commit 7ddf14258f
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit 1b6359a175
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10170: 'kneecaps tasers - makes taser knockdown require stamloss, nerfs taser stamloss, and removes the status effect's combat mode disabling' by deathride58 at commit 2d8d6eda11
#10409: 'IT WORKED ON LOCAL' by kevinz000 at commit 62b8513795
#10417: 'Nightshift improvements: public area settings/levels, nightshift auth requirement change, config changes, etc etc' by kevinz000 at commit 8725ffe916
#10493: 'Makes the post-secret gamemode vote score-based instead of schulze-based' by Putnam3145 at commit e0587aeac0

## Reproduction:
Pickaxe gibtonite ore.  The instant detonation that normally occurs after two hits should happens instantly.

**Comment by Arturlang** [comment]
Were you walking into the gibtonite?

**Comment by IronEleven** [comment]
Yeah this was using the movement keys to start picking.  Seems like you can safely hit it with the wide mode unless you pick directly at it.

**Comment by deathride58** [comment]
I actually died to this on live and I felt so unbelievably dumb because of it. Coders, please fix.

**Comment by Ghommie** [comment]
Fixed
