### ISSUE TITLE
Rising Bass' Side Kick can put people into walls, allowing for some serious Ninjutsu.

### ISSUE THREAD

**Issue by 2birdie** [citadel-station/citadel-main#10543]
## Round ID:

20938

## Testmerges:

#10493: 'Makes the post-secret gamemode vote score-based instead of schulze-based' by Putnam3145 at commit 3f5e68765e
#10417: 'Nightshift improvements: public area settings/levels, nightshift auth requirement change, config changes, etc etc' by kevinz000 at commit 8725ffe916
#10409: 'IT WORKED ON LOCAL' by kevinz000 at commit 62b8513795
#10170: 'kneecaps tasers - makes taser knockdown require stamloss, nerfs taser stamloss, and removes the status effect's combat mode disabling' by deathride58 at commit 2d8d6eda11
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit 1b6359a175
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10464: 'adds key_cache[] resets to the returns added by #10443 (obsolete now)' by deathride58 at commit 7ddf14258f
#10450: '(is this really a good idea) hitscan emitters' by kevinz000 at commit 39461e2806

## Reproduction:
Obtain Rising Bass.
Face east, with a wall to the south.
Perform the Side Kick.
You have now merged with the wall and may pass through to the other side.

**Comment by Ghommie** [comment]
This is why I did not like that thing to start with. @Seris02

**Comment by Owai-Seek** [comment]
This is just a secret escapist technique.
