### ISSUE TITLE
Just some text issues

### ISSUE THREAD

**Issue by Echopsychotic** [citadel-station/citadel-main#10576]
Round ID:
20999

## Testmerges:
The following pull requests are currently test merged:
#10158: 'Removes greentext' by Putnam3145 at commit 7a406e9db1
#10346: 'Nerfs limb stamcrit by doubling the base limb stam regen rate and making disabled limbs double the regen rate further' by deathride58 at commit 9ea99d4c81
#10347: '[experimental] Buffs the stamina buffer by making it recharge for free.' by deathride58 at commit bbdedd20b6
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10125: 'Ports a few projectile code updates by ke:b:inz.' by Ghommie at commit 02fbbd4f95
#10564: '[TESTING ONLY FOR NOW] Experimental optimizations' by kevinz000 at commit 7fb515173d
#10572: 'Removes harm prevention clause indicators from relevant sources.' by Tupinambis at commit dd9e62c8bb
#10575: '[TESTMERGE] Properly working TGUI Next' by Arturlang at commit 3a132d0a25
## Reproduction:

Observe/ghost then open the spawner menu from the ghost tab.

![bug](https://user-images.githubusercontent.com/58645053/72515391-6e0c7400-3815-11ea-94b1-2555fdf59589.png)

**Comment by Arturlang** [comment]
TGUI next bug

**Comment by Arturlang** [comment]
Fixed in the PR.
