### ISSUE TITLE
Elite mob herald (player controlled) still makes the war horn sound even after death each time the ghost speaks in Dchat

### ISSUE THREAD

**Issue by Echopsychotic** [citadel-station/citadel-main#10574]
## Round ID:
20998

## Reproduction:
Kill the (player controlled) herald do not revive them and let them speak in dead chat and watch as the ominous sound is played every time the ghost player speaks when in the body afterwards

**Comment by ghost** [comment]
expanding this issue:

any usage of talking also plays the noise, including emotes like flipping or spinning, without cooldown
