### ISSUE TITLE
Wrapping yourself up with package wrapper

### ISSUE THREAD

**Issue by Krasudreal** [citadel-station/citadel-main#10607]
## Reproduction: While holding nothing in one hand, and package wrapper in the other, climb on a chest, lay down, close the chest, then click on the chest with the wrapper, by switching hands. This will make the chest get wrapped with you inside, somehow. Additionally, you'll be stuck there until you RESIST and destroy the wrapping in the process

The issue is that you are able to wrap yourself in package wrapper while inside a chest. Sure, you can't use the destination tagger on yourself, but this still feels like something you shouldn't be able to do.
it is hilarious, but I think you shouldn't be able to do that.

**Comment by Owai-Seek** [comment]
I'm pretty sure the disposal ejects anything with a person in it right back to cargo, even if a destination is set.

**Comment by Krasudreal** [comment]
> I'm pretty sure the disposal ejects anything with a person in it right back to cargo, even if a destination is set.

Not the issue here. It is only that wrapping yourself in package wrapper should be impossible to begin with.

It is hilarious, but it should be impossible.
