### ISSUE TITLE
Feature Request: Allow players to refuse antagonist conversion.

### ISSUE THREAD

**Issue by Mikolail** [citadel-station/citadel-main#10613]
There is currently a major issue with the way antagonist conversion is handled: Players do not have any means to refuse a conversion while in-character.

While it isn't openly spoken of, many people will demand a ban in order to avoid playing Cult or any role that forces a conversion. Others have to announce to the current admins that they do not wish to play the given role. Certain will even resort to taking their own life or announce the current gamemode by outing the person/group in their fit of rage.

The current system used is a direct conflict to the "Do not be a creep" rule as the player who do not want to play the role is forced to consent into doing things they do not want to do. (Yes, even if there is not a single shred of sexual behavior with the act of converting someone, it is still considered as non-consensual.)

The refusal or approval of joining a team should be consented in-Character. Resorting to the Local-Out-of Character chat or Adminhelp should not be the proper scenario if the player wishes to not play the role. Being unable to choose this decision creates unnecessary issues for both the newly converted player, those who wishes to advance their objectives and the admins trying to solve the current situation. 

There are many reasons why people do not want to get converted. Some hates it because they have to break out of character, others get stressed out by the sheer responsibility they receive, several dread to be caught and killed, others believe they won't be of use to the current situation, many do not know what to do and may not get the proper training from other members and for others it means they must ignore whatever roleplay they were having and serve toward the current objective given. For all of them, it comes down to a round ruined or a potential ban.

My suggestion to avoid this issue: Allow players to select a second option toward game mode conversion in the preference menu. Selecting Allowed will prompt them a Yes or No option upon conversion.

Example: 

Blood Cult: Allowed
Blood Cult conversion: Disallowed
Clock Cult: Allowed
Clock Cult conversion: Disallowed
Vampire: Allowed
Vampire conversion: Disallowed
Revolution: Allowed
Revolution conversion: Disallowed
Gang: Allowed
Gang conversion: Disallowed

Upon selecting Disallowed, the player will not receive a prompt while being converted and the system will automatically pick no as their choice. This is for those who absolutely refuse to play the gamemode in question or to be converted mid-round.

This system ensure that the player who has the allowed option may still decide if they wishes to be converted at the moment or not depending on their current situation in the round. Those who do not desire at all to be converted can simply click the Disallowed option.

As per the change, there should be an appropriate In-Character reason toward why the player do not want to convert into the role along with a proper result from this depending on the current game mode.

Suggestion: A regenerative prototype Mindshield infused into the body.

Normal mindshields are currently used by the Captain, security and heads at all times. Anyone can come and ask for one at security, however it is rather bothersome when there are many people onboard and not everyone want to go through the process of getting a mindshield each shift. This cause a major time loss for both security and the players who do not want to be converted through the shift.

Furthermore, these mindshield can be surgically removed at any point whether it is for roleplay reasons (I.E: termination of contract by Nanotrasen. Fear of faulty device. Ect), or Antagonists for forcing a conversion. Being cloned removes completely the mindshield, forcing the player to get another one upon revival.

The prototype Mindshield is meant to resolve this issue by being permanently placed inside the body of the host. Because of the regenerative features, a cloned patient will receive a duplicate into his body.

However, due to the prototype nature, it may not fully protect against every type of brainwashing. (Explaining the Disallowed/Allowed options. Upon cloning, these will remain the same.) The surgical operation is also a very complicated process that cannot be reverted by normal means. (Thus cannot be removed at all through normal gameplay and requires adminhelp if a disallowed player decides to change this mid-round.).

A medical note should be added for the players using the prototype pointing out if they have a fully functional device or if it is defective. Fully functioning meaning they cannot be converted at all (All option are disallowed) Faulty (Some options are are disallowed.). A person with every convert options allowed should not receive a prototype mindshield.

Needless to say, those with a Faulty prototype can be given a second normal Mindshield for protection against every sort of brainwash. However a surgery will show that only the normal mindshield can be taken out afterward.

For Roleplay purposes, there could be notes indicating the disallowed option in Medical, akin to the quirks system. This will allow those with medical access to pinpoint potential recruits without going through the process of converting someone that will officially refuse the conversion

Example:

Blood Cult: This person does not like the sight of blood
Revolution: This person is devoted to Nanotrasen
Gang: This person abides to the law.
Vampire: This person hates to be bitten

Due to the nature of certain gamemodes, there could be some changes to accommodate this new feature. However this is something that should be discussed with the playerbase as this feature request is for the consent of the player upon conversion.

**Comment by Owai-Seek** [comment]
Personally, I don't like conversion antags, they're almost always an incredibly LRP shitfest, but this will -never- happen on citadel main because of the "gameplay first" philosophy. The closest I think the community would ever get to this idea is allowing someone to set their preferences for when they auto ghost instead of asking for an antag ban.

**Comment by silicons** [comment]
no, we are not giving people blanket roundstart opt in immunity from conversion.
every single conversion mode is /tg/ based conversion aka no choice.
if you want to design a gamemode that actually works via rp conversion, you can do so, but we are not doing this.

**Comment by silicons** [comment]
also conversion bans just replace you with a ghost when you're converted so someone's playing as you.
we're not cucking conversion antags out of a hard earned (at least in some cases hard earned) convert because someone doesn't want to play conversion.

**Comment by silicons** [comment]
oh yeah slightly less professional response

if you consider antagonist conversion to violate the rule that is very, very hecking clearly directed to non con sexual/vore related bullshit, and you actually go around trying to convince people it breaks the rules, hahahahaha no.
citadel will not get hugboxed to that level as long as i'm here.

**Comment by optimumtact** [comment]
hecking

**Comment by Fikou** [comment]
hecking
