### ISSUE TITLE
a lot of virgo hair styles are broken

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#10612]
first: one hairstyle is copied onto many other, it gives all these weird horns
don't think this is intended
curly through ponytail6(in the list)
plait through tbraid(in the list)
fingerwave
tbob
straight
clean
shaggy
mohawk
wife
second: straight borked(error)
short over eye
undercut
sideburn(facial hair)
dorsalfnil(facial hair)
spike(facial hair)
tribearder(facial)

there's also tons of duplicates and you can't search through them by pressing the first letter of a name

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/22992659/72676666-81a81c80-3a59-11ea-9781-952dd77cdab2.png)
for example, these random styles have the thing. same thing for their other directions but you know facing differently

**Comment by Ghommie** [comment]
I damn hate virgo hair styles, whoever ported them really did an awful job, thank you for reminding me that.
