### ISSUE TITLE
Vore can make you go permanently blind.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10611]
Issue reported from  Round ID: 21047 (Citadel Station 13)

Reporting client version: 512

I've actually seen people complain about this more than once, they get blinded in the vore room but after being ejected, they're still blinded.

**Comment by Poojawa** [comment]
Yeah, I noticed that as well. the blindness Ref isn't being cleared anymore, and I don't actually know what changed to break it.
