### ISSUE TITLE
Animal Feed Crate gives the wrong stuff.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10673]
## Reproduction:

Order an animal feed crate, instead of gettin 50 wheat and oats as advertised it dumps out the agreed upon wheat, but also, an absolute ton of towercaps.

**Comment by Ghommie** [comment]
@Trilbyspaceclone, yea, why are there wood logs in an animal feed crate? We don't have beavers.

**Comment by Trilbyspaceclone** [comment]
Wait you mean, the issue, that has been around for over 2 months. After the fix was merged gets, THEN gets reported???
