### ISSUE TITLE
Races need revision to ensure they're working as intended (12/21 Port)

### ISSUE THREAD

**Issue by Poojawa** [citadel-station/citadel-main#107]
I attempted to preserve as much of the furry race snowflake code as possible during the port update, as well as mutant colors 2 and 3. 

In client/preferences.dm, Mutant 2 & 3 were slightly changed to follow what Mutant 1 color had changed.
Most body parts, including the xeno additions, were saved as much as I could find

Most accessories were also copied.

There is a new type of bodypart - Legs. Digilegs are now a thing for lizards, and obviously can be easily adapted to better fit our furry races. We can probably hijack this for Tauric body special rules as long as we sprite the adapted stuff like hardsuits and uniforms.

**Comment by LetterJay** [comment]
So the only thing needed for this are leg sprites?

**Comment by Poojawa** [comment]
being worked on.
