### ISSUE TITLE
wheelchair and disabled legs people bugs

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#10863]
## Round ID:
21261

## Reproduction:
have the disabled legs trait, exist

FIRST: they still slip in wheelchairs, probably does this for any vehicle and it doesn't make sense

SECOND: if your legs are disabled for some reason on-mob shoe slot sprites just don't show, maybe it thinks it's amputated?

**Comment by ghost** [comment]
one other thing, i checked and they only slip on lubed floors and not bananas

**Comment by Ghommie** [comment]
Well then, certain objects or turfs are meant to slip people regardless of vehicle and no slip footwear. That's a feature.
