### ISSUE TITLE
You can't CTRL+F TGUI Menu stuff.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10896]
## Round ID:
21286

## Reproduction:

Just CTRL+F in TGUI, it sadly doesn't work. Gonna be hell for PDA, Cargo, and Craft Menu searching.

**Comment by Arturlang** [comment]
Not a bug, oversight, something u need to look into

**Comment by Arturlang** [comment]
It works for me, wierd.

**Comment by Owai-Seek** [comment]
Might have been my byond being fucky, Ima close this, its working now.
