### ISSUE TITLE
Shuttle Timer is broken.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10895]
## Round ID:
21286

## Reproduction:

Just like, look at the timers. It's all goofy and hard to tell the actual time left.

![image](https://user-images.githubusercontent.com/7543955/73746095-7542e580-4722-11ea-92c0-f2f4a260da81.png)

**Comment by Ghommie** [comment]
Yea, a little consequence with the unicode support PR, is a thing on tgstation too.
Perhaps I'll write or port the fix later, depending whether this is getting fixed up there or not.
