### ISSUE TITLE
One of the paragraphs of the greeting message given when joining the server into the lobby in dark mode is unreadable

### ISSUE THREAD

**Issue by BlueWildrose** [citadel-station/citadel-main#10912]
![image](https://user-images.githubusercontent.com/57083662/73824359-4165cf80-47b7-11ea-8e00-b98aa2915d52.png)
![image](https://user-images.githubusercontent.com/57083662/73824379-4c206480-47b7-11ea-86d5-5ecc86a8703f.png)
Hopefully self explanatory.

**Comment by Ghommie** [comment]
Finally fixed after I pinged the headmins about it several times.
