### ISSUE TITLE
Being Fireman Carried does not show your hand being filled.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#10945]
## Round ID:
21325

## Reproduction:
Just get lifted up. It doesnt show which hand you've filled up.

![image](https://user-images.githubusercontent.com/7543955/73992714-e995a880-491d-11ea-982e-d3dd68e04e6b.png)

**Comment by Ghommie** [comment]
Kevinz fixed this gameplay issue a while ago by making people unable to use the items they are holding while fireman carrying someone iirc.
