### ISSUE TITLE
Fleshpeople hate them! Watch this slimeperson break the law of conservation of mass regarding their own jelly in their system with a syringe!

### ISSUE THREAD

**Issue by BlueWildrose** [citadel-station/citadel-main#11052]
Here's how!

1. Be a xenobiological slime hybrid
2. Get a syringe, and a health analyzer
3. Analyze yourself to see your blood levels
4. Draw out your slime jelly blood using the syringe
5. Analyze yourself again
6. Inject your slime jelly blood back into yourself
7. Analyze yourself again - you should see yourself with a higher blood level than before.

This only happens as a slimeperson as far as I know - other species don't have this problem.

**Comment by InquisitiveEpidemic** [comment]
That's the toxin damage that slime jelly blood inflicts, which increases blood volume along with the blood being added back into the slime's body.
