### ISSUE TITLE
Fixing of the Light Replacer on Engineering Cyborg

### ISSUE THREAD

**Issue by Terekichi** [citadel-station/citadel-main#11067]
It is impossible to refill the Engineering Cyborg Light Replacer with light bulbs: Charging doesn't refill it, can't refill it with light bulbs, nor glass

**Comment by Trilbyspaceclone** [comment]
Use normal glass and not R-glass,
recharging fills it really slowly

**Comment by DeltaFire15** [comment]
The light replacer can be refilled properly via using glass on it.
