### ISSUE TITLE
Mag Weapons are Built with Zero Charge

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#11116]
## Round ID:
 21471

## Testmerges:
#10572: 'Removes harm prevention clause indicators from relevant sources.' by Tupinambis at commit dd9e62c8bb
#10857: 'FUCK SHIT I'M NAKED IS THIS A DREAM OR REAL FUCK FUCK WHERE ARE MY CLOTHES hallucination' by Seris02 at commit 3e0cd361b1
#10877: 'Riot Electrostaves ' by kevinz000 at commit de5186026d
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#11033: 'gives CMO special surgery drapes that can initiate techweb surgeries without operating console' by kevinz000 at commit 70e752dbc9
#11080: 'hey someone gave me this idea for stunbatons (and I sort of expanded it) and it's worth a test' by kevinz000 at commit 938d87cfba

## Reproduction:
Build mag rifle, add firing pin, load ammunition, attempt to fire.  This is inconsistent with the behavior of every other printable weapon that uses the charge mechanic.

**Comment by Owai-Seek** [comment]
I'm pretty sure it was an intentional change, but I could be wrong.
