### ISSUE TITLE
Ash Walkers missing legs

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#11127]
Issue reported from  Round ID: 21480 (Citadel Station 13)

Reporting client version: 513

Sometimes Ash Walkers will spawn with no visible legs. It appears to be random, as sometimes you do have visible legs.
The legs are still actually there, but they are completely invisible.

Images showing the bug:
[One](https://cdn.discordapp.com/attachments/546822932278673420/678394786033696778/unknown.png) [Two](https://cdn.discordapp.com/attachments/546822932278673420/678394821898928151/unknown.png) [Three](https://cdn.discordapp.com/attachments/546822932278673420/678394867277365251/unknown.png) [Four](https://cdn.discordapp.com/attachments/546822932278673420/678756931992813586/unknown.png)

**Comment by DeltaFire15** [comment]
Think this got fixed sometime ago
