### ISSUE TITLE
Pai Apc unlock and pipe manipulation

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#11137]
## Round ID:
21510

## Reproduction:
alt click APC as pai (works in card form too!) witness how the apc becomes unlocked or locked. interact with the apc with carbon hands mess with its settings.
Edit: learned pais can also mess with pumps and  atmos machinery can use the alt click and ctrl click actions on them.

**Comment by YakumoChen** [comment]
hell no
