### ISSUE TITLE
You can hold belts, ids, and have things in your pocket without any i_clothing on.

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#11148]
## Round ID:
21527
## Reproduction:
I had been wearing long john bottoms and a shirt in the Character Appearance part of Character Setup. For the item I had found this glitch in, it had been 'tan pants.' At the time, I had also been augmented with cyborg limbs and parts. Once I took the pants off, everything that should've fallen off, did fall off. However, I found that I could still equip things to the ID, belt, and storage 1 and storage 2 slots, despite wearing no inner clothing to hold it. So basically, you don't need a jumpsuit to hold those types of items for some reason.

**Comment by Ghommie** [comment]
To explain, cyber legs allow items to be pocketed (also provides resistance against caltrops), while the cyborg chest allows The ID and belt to be worn, all without the need of a jumpsuit.

Not a bug, but a feature, thanks for throughfully explaining the situation anyway.
