### ISSUE TITLE
Mechs are disappearing or not finishing.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#11171]
## Round ID:
21552

## Reproduction:

Apparently as soon as you weld a ripley or firefighter with this step it turns invisible and loses its density. Other issues are the mech remaining in the location, but not accepting rods, meaning the mech can't be finished. Walking on the tile will delete the mech from existence, but alt clicking the tile beforehand still shows it (when invisible).

![image](https://user-images.githubusercontent.com/7543955/74909577-9ba18b80-5386-11ea-8d53-fdc79dc63b27.png)

Yell at Crash about it, he's the one who was too lazy to make an account for this.

**Comment by FerretBox** [comment]
Crash here.

As an addendum to that problem, as that problem was earlier today, the Ripley APLU outright refuses to take the metal rods after welding the armor onto it. This problem was tested about twenty minutes ago by myself.

**Comment by Ghommie** [comment]
@Hatterhat.

**Comment by Ghommie** [comment]
Fixed in #11907.
