### ISSUE TITLE
Nuke near miss minimal effect

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#11197]
## Round ID:
21592

## Reproduction:
Detonate the nuke in a near miss scenario for example on a tile out in the middle of space still triggers the 500 dev explosion and gives nuke ops a major

**Comment by Ghommie** [comment]
Was it on the station z-level?

**Comment by Trilbyspaceclone** [comment]
Yes thats how you do it, what you basicly do is drag the nuke out of the ship by 1 tile, and then active it then leave.

**Comment by Detective-Google** [comment]
> Was it on the station z-level?

the round in question ops pulled the nuke a few tiles away from their ship built a floor in space to anchor it on and then left.

**Comment by Ghommie** [comment]
Still the station z-level.

**Comment by bunny232** [comment]
Issue is the end round cinematic where it says *Minimal effect on target* while it still vaporized the station. Assuming the cinematic plays in the first place
edit: more info:
there's a separate nuke_win and nuke_miss cinematic

**Comment by bunny232** [comment]
Assuming we want the space nuke to result in a win the miss cinematic should just be changed to the win cinematic
