### ISSUE TITLE
Cyborgs cannot sit/lay down

### ISSUE THREAD

**Issue by Echopsychotic** [citadel-station/citadel-main#11194]
## Round ID:21590

## Testmerges:
#10327: 'ports hyper's genetics (tg genetics but not as powergamey)' by Seris02 at commit b811194d85
#10629: 'Putnamos aka "i made LINDA fast"' by Putnam3145 at commit eeba1b7457
#11110: 'you kids like extend votes?' by Hatterhat at commit 362ebbcf8f
#11130: 'Enables space ruin generation in the station z-level. Adds new ruins for the sake of station ruins.' by BlackMajor at commit 984b57560b
#11158: '[TESTMERGE ONLY] Patches out examiner integrated circuits' checking descriptions.' by Putnam3145 at commit fa2f6be232
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10451: 'Mobility flags + combat rework stuff refactoring, fixes a few edge cases including the Oh Dreaded Xenomorph Hardstuns, etc etc time to break the game' by kevinz000 at commit 5a580dda20

## Reproduction: 
1. use the rest command as dog borg
2. Watch as you do not sit/lay/go on back.
Should you switch the sit sprite appearance while you are sat down it will instantly switch to the rest sprite. 

Edit: Adding on to this cyborgs also cannot stand up without changing their sprite sitting shape. in order to do so. So it looks like they are just dragging on the ground. Example: sitting->laying down.

**Comment by Ghommie** [comment]
Related to the #10451 testmerge.

**Comment by Ghommie** [comment]
Fixed.
