### ISSUE TITLE
Atmos pipes around AI upload on boxstation is a single circuit and doesn't lead to atmospherics.

### ISSUE THREAD

**Issue by dapnee** [citadel-station/citadel-main#11205]
Rooms affected: Bridge, captain's office, AI upload, Vault, HoP's office, meeting room, and teleporter room. 

I was a slime that spawned in the vault and went to ventcrawl to get to the main hallway, what I found was that the scrubbers only lead to the above areas and nowhere else. When I tried the vents, same thing.

**Comment by bunny232** [comment]
closed by #11358
