### ISSUE TITLE
Defective clones can't speak or gesture

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#11204]
## Round ID: 
21607
## Reproduction: 
Title. Spawn in as a defective clone from the experimental cloner and you won't be able to talk or gesture anything.

**Comment by Owai-Seek** [comment]
Does this persist after genetic fixes?

**Comment by necromanceranne** [comment]
There wasa fix on tg if someone wants to port it.

**Comment by Ghommie** [comment]
Weird cause the issue was indeed ported long time ago already and I can't see any potential cause atm.

**Comment by Ragolution** [comment]
Could not reproduce in test environment. 
All defective clones that I spawned/generated seemed completely fine, and ones that spawned with genetic defect were absolved of blindness, muteness, et al. when administered appropriate medical aid.

**Comment by ghost** [comment]
It may have been something going on with something else in the round. No amount of medical or genetic help could fix it. At least it's probably not gonna affect later rounds if it's truly fixed.
