### ISSUE TITLE
Dogborg lick pref

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#11226]
## Round ID:
21647

## Reproduction:
toggle off lick pref in vore panel get dog borg to lick you ???? profit

**Comment by Ghommie** [comment]
Please give us a more exhaustive description of the issue. I really don't understand what you are trying to explain here.

**Comment by Owai-Seek** [comment]
They're saying that if you have the lick pref set to not want licking, Dogborgs can still do it to you.

**Comment by bunny232** [comment]
sorry writing bug reports while falling asleep is a bad idea but ya what owai said, dogborgs can still lick you even though you have the lick pref set to off in the vore menu

**Comment by Xantholne** [comment]
I believe you are thinking of their lick module that they have for some reason as a dog borg, letting them just bypass the lick pref since it's a module item and not the verb from vore panel

**Comment by Ghommie** [comment]
@Putnam3145 god I hate dogborgs.

**Comment by Ghommie** [comment]
Should have been fixed in the PR that deleted the vr_prefs datum.
