### ISSUE TITLE
Game dislikes the character ' in many locations.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#11228]
## Reproduction:

Use ' in your flavortext, it turns into something like this:
![nZutiDlooF](https://user-images.githubusercontent.com/7543955/75189739-d6a41600-571c-11ea-9ed2-50ac840dbefe.png)
![dreamseeker_jlwe830LTE](https://user-images.githubusercontent.com/7543955/75189761-e3286e80-571c-11ea-886b-924d7062fd4c.png)
I've noticed it in a few places but the flavor text is most apparent.

**Comment by bunny232** [comment]
Pretty sure this has been a age old issue due to byond fuckery or smth

**Comment by Ghommie** [comment]
Not completely byond funkery, just the stripped_input proc html encoding the message for safety.
