### ISSUE TITLE
Bug with virology

### ISSUE THREAD

**Issue by Addirem** [citadel-station/citadel-main#11267]
### Virology anthromorph bug?
So, I was playing a round on Lowpop just a few minutes ago. I was the only one in medbay, and decided to try out virology. I created a virus (Symptoms of Regen Coma, Self Resp, and sensory restoration) and attempted to use it on myself. It did nothing whatsoever to me. I tested it on a monkey, and it worked fine. Since it was bloodbased, I then injected some of that monkey's blood into myself, with no effect. Nobody else tried my virus, so I couldn't test it on anyone else. Round ID 21719

**Comment by Ghommie** [comment]
A fix had already been made and merged before this report was done.
I'll bug the headmins to update the server if they haven't already done so in the past hours.
