### ISSUE TITLE
Turrets are unable to give back guns.

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#11269]
## Round ID:
N/A
## Testmerges:
N/A
## Reproduction:
Make a turret with any gun in it, decon it. Get a message you successfully got the gun back. Look around at the gun that isnt their.

This is also true for pre-spawned turrets like at Turreted Outpost
AI Sat, some away missions.

Checking Vars and code, it does say theirs a gun stored in the turrets and it REFUSES to give it back...

**Comment by necromanceranne** [comment]
There is a fix on /tg/ but this presented an obscene number of problems. I'll port over the fix but the consequences are gonna be pretty numerous.
