### ISSUE TITLE
Vampires never actually repair their coffin lock.

### ISSUE THREAD

**Issue by chaoko99** [citadel-station/citadel-main#11295]
## Round ID:
Round ID: 21782

## Testmerges:

The following pull requests are currently test merged:
#11268: 'quick vampire lunge nerf (and mesmerize kinda)' by raspyosu at commit 8953877a69
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10327: 'ports tg genetics' by Seris02 at commit b195783dfb
#10986: 'wall walking boots for traitors' by Seris02 at commit fc64c0a008
#10451: 'Mobility flags + combat rework stuff refactoring, fixes a few edge cases including the Oh Dreaded Xenomorph Hardstuns, etc etc time to break the game' by kevinz000 at commit 7f7dced8b0
#11130: 'Enables space ruin generation in the station z-level. Adds new ruins for the sake of station ruins.' by BlackMajor at commit fc4f9e7800
#11274: 'Fixing a whoopsie with airlocks.' by Ghommie at commit c9a5f49623
## Reproduction:
Break the lock by struggling out of your coffin, then 
recieve message "The secret latch to lock the coffin from the inside is broken. You set it back into place...". This never actually completes.

**Comment by chaoko99** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/575f6e4ebc4ae5d680c72007e4adaf948c1e147b/code/modules/antagonists/bloodsucker/objects/bloodsucker_coffin.dm#L207 Relevant code

**Comment by Arturlang** [comment]
There is no completion message, though it does actually complete. Should probably address this.

**Comment by chaoko99** [comment]
``			to_chat(resident, "<span class='notice'>The secret latch to lock [src] from the inside is broken. You set it back into place...</span>")
			if (do_mob(resident, src, 50))//sleep(10)
				if (broken) // Spam Safety
					to_chat(resident, "<span class='notice'>You fix the mechanism and lock it.</span>")
					broken = FALSE
					locked = TRUE``


what do you mean? It repeats every time I go for the sun nap

**Comment by Arturlang** [comment]
Wierd. Its worked in testing. Ill see about it.
