### ISSUE TITLE
SPRITE bugs!

### ISSUE THREAD

**Issue by Echopsychotic** [citadel-station/citadel-main#11301]
**THE ROUND ID**
21787

## Testmerges:
#11268: 'quick vampire lunge nerf (and mesmerize kinda)' by raspyosu at commit 8953877a69
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10327: 'ports tg genetics' by Seris02 at commit b195783dfb
#10986: 'wall walking boots for traitors' by Seris02 at commit fc64c0a008
#10451: 'Mobility flags + combat rework stuff refactoring, fixes a few edge cases including the Oh Dreaded Xenomorph Hardstuns, etc etc time to break the game' by kevinz000 at commit 7f7dced8b0
#11130: 'Enables space ruin generation in the station z-level. Adds new ruins for the sake of station ruins.' by BlackMajor at commit fc4f9e7800
#11274: 'Fixing a whoopsie with airlocks.' by Ghommie at commit c9a5f49623

## Reproduction:
Put a battery in a charger and let it charge to full then take it out. It will continue to show a battery in place even without one there.
Also seen in the cloner as well, I have no idea if it is an issue in other things.

**Comment by Ghommie** [comment]
Should have been fixed now. If more issues arise, make more bug reports.
