### ISSUE TITLE
Vampire heart objective

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#11386]
## Round ID:
21923

## Reproduction:
have reqiured number of hearts in round start internal box survive till end
![image](https://user-images.githubusercontent.com/1371992/76165486-caad5080-612d-11ea-99cf-d195855e2707.png)

**Comment by Owai-Seek** [comment]
Is it possible someone took a bite out of any of them? I think it turns it from an organ into a snack.

**Comment by bunny232** [comment]
I don't think so also I looked at the code it just checks for /obj/item/organ/heart while checking the monkey code says they spawn with a /obj/item/organ/heart so it should work.

**Comment by Arturlang** [comment]
Some custom races seem to have perhaps wierd typepaths of hearts, ive  had this issue as well.
Should perhaps introduce a feature allowing vampires to perhaps SMELL if the heart is RIGHT? And then limit it to hearts derived for sentient beings, so itll atleast require stealing their heart via surgery if they want to safely remove it.
