### ISSUE TITLE
Felinid Cat tail shows up twice on sprite.

### ISSUE THREAD

**Issue by C-Kuha** [citadel-station/citadel-main#11469]
![gjk;](https://user-images.githubusercontent.com/54485383/76686019-87435e00-65d5-11ea-92cb-a761bb6b4985.PNG)
The regular cat tail is duplicated on your sprite, with one being static and one being animated.
The animated one remains and functions while the one able to be surgically removed is static.

**Comment by Ludox235** [comment]
Finally a good issue :/
