### ISSUE TITLE
monkeys can snatch items from people while inside a folded bluespace bodybag

### ISSUE THREAD

**Issue by timothyteakettle** [citadel-station/citadel-main#11510]
get a bluespace bodybag
put a monkey in it
fold it up
hold it
watch as the monkey (eventually) takes it from your hands

bonus stuff:
the monkey eventually suffocates, and drops the bag
you can still take the bag from the monkey, despite it being on the floor (there's two bags now)
this bag has no sprite, and if you use it in your hand, you can infinitely produce new bags

**Comment by Trilbyspaceclone** [comment]
Know issue from 2017.

**Comment by timothyteakettle** [comment]
cool but uh, it lets you create an infinite amount of bluespace bodybags and should probably be fixed (aside from other quirky behaviour)
