### ISSUE TITLE
Alien Organ Manipulation and Dissection Not Working With Advanced Surgery Tools

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#11525]
Issue reported from  Round ID: 22119 (Citadel Station 13)

what it says on the tin, some alien organ manipulation and Dissection of xenomorphs does not work with advanced surgery tools.

Reporting client version: 513

**Comment by Ghommie** [comment]
Just tried and it works fine, are you sure you used the right tool modes and followed the correct surgery steps?
Alien organ manipulation steps differ from the normal deal: See more [here](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/code/modules/surgery/organ_manipulation.dm)

**Comment by InquisitiveEpidemic** [comment]
yes I did do the proper tools for xeno surgeries bone-cutting laser scalpel.  It was a on a surgery table and computer built in round instead of round start if that might make a difference.
