### ISSUE TITLE
Incubus Draft Affecting Blood Volume When Disabled 

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#11550]
Issue reported from  Round ID: 22152 (Citadel Station 13)

Reporting client version: 513

Incubus Draft will increase the required blood volume for survival when enlargement is turned off in prefs. This may be unintentional (though amusing) as this round it too needed blood volume up to 2000 cl but could only maintain ~650 cl (normal blood volume is I think 650 cl).  After enabling enlargement in prefs (while the chem was metabolizing) maximum blood volume stabilized at 1968.5 cl

**Comment by Ghommie** [comment]
Apparently, enlargement chems affecting livers and blood volume when the prefs are off seems to be an intended feature emulating some sort of liver damage before the generic standard organ damage code was ported, how peculiar..,
