### ISSUE TITLE
blueprints remove no_teleport from turfs

### ISSUE THREAD

**Issue by timothyteakettle** [citadel-station/citadel-main#11599]
reproduction:
1. get blueprints
2. create new area
3. you can now teleport in this new area

saw the issue on tg and was like 'haha isn't that quirky, I wonder if we have the exact same blueprints issue' and we do

**Comment by Ghommie** [comment]
Umh, could you give me a more descriptive version of this issue? no_teleport is a area variable, not a turf one.

**Comment by timothyteakettle** [comment]
ah, my bad about the area not turf thing, this is a reference to what I saw on tg, I remembered seeing it when being bored and looking at quirky stuff, and then during a local test decided to see if we had the same issue, and we do apparently, and it's fairly bad

no clue how you reference issues from other repositories so i'll just post the link:
https://github.com/tgstation/tgstation/issues/49043
