### ISSUE TITLE
Borgs can apparently sleeper you completely bypassing preferences

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#11616]
## Round ID:
22240

## Reproduction:
have 
Voracious MediHound sleepers:No
be vored by medborg while ((dead? unsure if it matters))

**Comment by Arturlang** [comment]
Its a separate preference...

**Comment by cebutris** [comment]
The voracious preference doesn't prevent you from being sleepered by medihounds, but rather changes the flavortext of it- Voracious being implied to be the belly, while non-voracious is simply a mounted sleeper.

The only reason this would be an issue is if you got the voracious flavortext with the preference off

**Comment by ghost** [comment]
this is just a problem with shitty rules inconsistency
