### ISSUE TITLE
Chaplain Vampire No Workies (on purpose?)

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#11626]
Issue reported from  Round ID: 22251 (Citadel Station 13)

Reporting client version: 513

Spawned in as chaplain vampire, could not use null rod transformation, armaments beacon, or bless things with my bible. I'm assuming that when I pray it also isn't treated as if I'm chaplain, but I cannot confirm this directly.
Suggest either blacklisting vampire from chaplain, or making it more clear that vampire chaplain cannot do holy things on purpose, because holy things do not work on vampires normally as a defensive measure (aka holy water and the null rod do not specifically damage vampires) so in theory they would work when you're using them yourself as chaplain.
I hope this made sense thank you.

**Comment by Trilbyspaceclone** [comment]
All those things are holy trait locked iirc.
Being a vampire removes holy trait as you would burn up if you have it. Also how did you become a vampire round start out side of halloween?
