### ISSUE TITLE
disguises do not change pronouns of disguisee

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#11637]
title

steps to reproduce:
1) get character of male/female gender
2) get another character of opposing gender
3) changeling/abductor/envy's knife/etc the target
4) pronoun doesn't change despite the rest of the body changing

**Comment by Trilbyspaceclone** [comment]
gender is a mind thing, its what you select in character. Without chems or a magic slime bottle you cant change gender by those ways as they /mimic/ not change
