### ISSUE TITLE
a couple of ventcrawling consistency issues

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#11736]
people with ventcrawl (ie abductor gland given to a human) can walk through plastic flaps while standing up. dunno if this is intentional or not but it's not really a vent

people with ventcrawl (i e abductor gland) take damage from ventcrawling unless they have hardsuit/oxytank. this is probably intentional but seems pretty inconsistent with the idea that it should let you ventcrawl like everything else that can ventcrawl

**Comment by Ghommie** [comment]
The first one is intentional, ventcrawlers can pass through plastic flaps.
The second is probably also sort of intentional and shared with other mobs vulnerable from pressure and air contents such as monkeys too, specially around scrubbers.

**Comment by ghost** [comment]
yeah idk it just seemed kinda inconsistent even if i was sure it was intentional
