### ISSUE TITLE
The synthesizer starts sounding a little off...

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#11754]
Issue reported from  Round ID: 22418 (Citadel Station 13)

Reporting client version: 513

Test merge likely to have caused this: #11680 Ports a rewritten version of BAYSTRUMENTS

Reproduction steps:

1. Tune your instrument (in this case a synthesizer but any should work)

2. Wait until your instrument stops being tuned, either during play or immediately after starting to play after taking ages to play the instrument after tuning so it wears off

3. You will now be spammed with "The synthesizer starts sounding a little off..." in increasing amounts, capping at what seems to be a set of five strings per notice going off (starting at one string per notice and going up by one each time you re-tune your instrument)
Please note that you WILL be spammed with "The synthesizer starts sounding a little off..." until you tune the instrument, not just the two times shown in the example image.

[Image](https://cdn.discordapp.com/attachments/546822932278673420/696530260996522044/unknown.png)

**Comment by Ghommie** [comment]
Fixed.
