### ISSUE TITLE
hulk combining does not work

### ISSUE THREAD

**Issue by redta1l** [citadel-station/citadel-main#11769]
## Reproduction:
find Strength and Radioactivity mutations in gene sequence console, select both for combining, be confused when nothing happens

**Comment by ghost** [comment]
not a bug hulk is just disabled

**Comment by ghost** [comment]
addendum: someone should just add some error feedback if a mutation is disabled, probably

**Comment by Ghommie** [comment]
It's not disabled, it's outright not present in the codebase right now.
