### ISSUE TITLE
/obj/item/gun/energy/pumpaction/ AKA the wardens laser runtimes on destroy or update_icon

### ISSUE THREAD

**Issue by Arturlang** [citadel-station/citadel-main#11772]
## Reproduction: Start game as warden, get runtime
![image](https://user-images.githubusercontent.com/24881678/78644088-00289380-78be-11ea-91d4-c66781c96993.png)

**Comment by Arturlang** [comment]
![image](https://user-images.githubusercontent.com/24881678/78644014-e12a0180-78bd-11ea-8385-0a44162b66fb.png)

**Comment by Arturlang** [comment]
![image](https://user-images.githubusercontent.com/24881678/78644041-eab36980-78bd-11ea-85b2-24db195462bf.png)

**Comment by Arturlang** [comment]
![image](https://user-images.githubusercontent.com/24881678/78644088-00289380-78be-11ea-91d4-c66781c96993.png)

**Comment by Ghommie** [comment]
@kevinz000
