### ISSUE TITLE
being a slime lets you ignore several limb-based negative quirks

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#11862]
If you're parapalegic or otherwise have a quirk that removes or hampers a limb you can just cut it off and regrow it for a new, working limb. This is pretty dumb and powergamey for quirks imo

**Comment by Ghommie** [comment]
Something tells me that may have something to do with `update_disabled()` or `update_disabled_bodyparts()` not being called when a new limb is implanted.
