### ISSUE TITLE
Viruses Do Not Work Some Rounds

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#11872]
## Round ID:
22563

## Testmerges:
#11835: '[TESTMERGE ONLY] Revert "Ports "Obliterates item_color: new washing machine functionality edition""' by kevinz000 at commit 9d3fe8f185

## Reproduction:
For entire rounds at a time, player created viruses fail to infect any hosts.  I have not noticed any sort of pattern as to which rounds it occurs so far.

**Comment by Ghommie** [comment]
Probably caused by a few malformed logics that were fixed a while ago by kevinz. Let's hope everything is fine now.
