### ISSUE TITLE
holodeck console gives a completely blank white window

### ISSUE THREAD

**Issue by redta1l** [citadel-station/citadel-main#11904]
## Testmerges:
#11864: 'The bag of holding (and I guess backpack) balancing pass no one asked for' by kevinz000 at commit ab077a42ec
#11848: 'Removing SS_TICKER from the lighting subsystem' by Putnam3145 at commit 4703af111d

## Reproduction:
click on holodeck window, get completely white window with no exit button
this will force AIs to reconnect as they cannot close the window by walking out of range

**Comment by Ghommie** [comment]
Fixed in #11903, you were a dozen minutes too late with that issue report.

**Comment by Ghommie** [comment]
This is still an issue until the fix is merged, boy.
