### ISSUE TITLE
Agent id + economy

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#12018]
## Round ID:
22673

## Testmerges:
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11890

## Reproduction:
have agent id, change account code, put in a invalid code, go to change name cant beacuse it wants you to change account code first

**Comment by Ghommie** [comment]
Did you make sure you didn't accidentally Alt Click the ID while the Forge/Reset/Show/Change-Account-ID alert popup was open? Byond queues additional input/alert pop-ups while one is open for safety.

**Comment by Ghommie** [comment]
Probably that.
