### ISSUE TITLE
Cyborg torso augmentation cause stamina damage stop regenerate

### ISSUE THREAD

**Issue by Sonic121x** [citadel-station/citadel-main#12046]
## Round ID:
none

## Testmerges:
localhost

## Reproduction:
start a augmentation surgery on torso
replace it with cyborg torso(/obj/item/bodypart/chest/robot)
take some stamina damage(sprint around,disabler etc.)

use view variables and try to heal stamina damage won‘'t work(full heal still fine)

**Comment by Ghommie** [comment]
Was fixed by kevinz a while ago.
