### ISSUE TITLE
cat ears broken, inner ear not showing

### ISSUE THREAD

**Issue by silicons** [citadel-station/citadel-main#12113]
Issue reported from  Round ID: 22787 (Citadel Station 13)

Reporting client version: 513

![image](https://user-images.githubusercontent.com/2003111/80966059-99b56900-8dc8-11ea-89b3-f2bb8fecdd21.png)

no pink

haha what an urgent bug report

**Comment by Tumesuo** [comment]
![5RVjYGgr6E](https://user-images.githubusercontent.com/15519576/80966888-1292e000-8e1e-11ea-9743-a18517ddcd48.png)
for some reason hairs of different colour still seem to have them, I've seen brown and dark brown to black loose their ears for some reason, with orange and purple(?) haired cats still keeping them.

**Comment by Tumesuo** [comment]
![dreamseeker_ufWI5nTWYe](https://user-images.githubusercontent.com/15519576/80967111-803f0c00-8e1e-11ea-9c5b-25f464f820fb.png)
Also having a flower in your head is still fucked over, shows under the cat ears. Prolly layering issue or smth

**Comment by Ghommie** [comment]
Uh, uh.
