### ISSUE TITLE
Trying to hit a missing limb runtimes

### ISSUE THREAD

**Issue by Azarak** [citadel-station/citadel-main#12137]
## Round ID: N/A
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/master/code/modules/mob/living/carbon/human/species.dm#L1684
The affecting limb check happens after some other checks, where it should be the first thing that happens

## Reproduction:
1. Delimb someone
2. Try and hit the delimbed part
3. Nothing happens

**Comment by DeltaFire15** [comment]
I fixed this.
