### ISSUE TITLE
ghost orbits are off center

### ISSUE THREAD

**Issue by silicons** [citadel-station/citadel-main#12184]
Issue reported from  Round ID: 22851 (Citadel Station 13 - Medium Roleplay)

Reporting client version: 513

![image](https://user-images.githubusercontent.com/2003111/81485995-85c59900-9206-11ea-83b2-9aa9feef8154.png)

**Comment by Ghommie** [comment]
Weird, haven't experience this issue yet.

**Comment by Ghommie** [comment]
Couldn't replicate the issue outside of the pixel shifting feature monster made a while ago.
