### ISSUE TITLE
AI camera doesn't move away from the splashscreen at roundstart

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#122]
http://i.imgur.com/uYp0WPW.png

**Comment by king5327** [comment]
Literally the easiest solution to that is to hit the "view core" button, which will center you on your AI core no matter what you were looking at or where you are.

**Comment by ghost** [comment]
i don't think you understand the development process here :^)

we fix it because it's **NOT SUPPOSED TO HAPPEN**

**Comment by Poojawa** [comment]
Likely fixed with updates
