### ISSUE TITLE
Can't use ghost cafe vendors

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#12265]
## Testmerges:
#12075: 'Field of Vision component.' by Ghommie at commit 226d0f111f
#12175: 'Adds a New map, Snow Taxi (A vgstation13 map port)' by Detective-Google at commit 4378a34ea7
#12217: 'The real fastmos: C++ monstermos port' by Putnam3145 at commit 86afd889f1

## Reproduction:
Spawn in at ghost cafe, try to use the drink vendors, see that they're all greyed out and you can't interact with them. Deconning and reconning them just makes everything cost stuff.
![Capture](https://user-images.githubusercontent.com/32374784/82021020-0f2dfe80-963f-11ea-991a-a3aba6557c1c.PNG)

**Comment by Ghommie** [comment]
Pretty sure this got fixed already but the server didn't update yet at the time.

**Comment by MrJWhit** [comment]
I can confirm that it got fixed:
![image](https://user-images.githubusercontent.com/48370570/82402875-7e369900-9a2b-11ea-8304-9c5e90ed0031.png)
