### ISSUE TITLE
Bluespace floors break stanima

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#12344]
Issue reported from  Round ID: 23020 (Citadel Station)

Reporting client version: 513
Blue space tiles accelerate the speed you loose stamina at a higher than normal amount.

**Comment by Trilbyspaceclone** [comment]
having slowdown also gives you more stamina it feels like.

**Comment by YakumoChen** [comment]
stamina is lost per tile, not in seconds, so this is not a bug.
