### ISSUE TITLE
Hotkey ctrl+t makes two chat windows

### ISSUE THREAD

**Issue by Tumesuo** [citadel-station/citadel-main#12374]
Issue reported from  Round ID: 23062 (Citadel Station)

Reporting client version: 513

say"text" window appears and "say" window comes on top of it after a delay
![dreamseeker_2wjnMAmKuf](https://user-images.githubusercontent.com/15519576/83067366-3b9a3f80-a06f-11ea-9386-96fbe017afdc.png)

**Comment by Ghommie** [comment]
Fixed by #12626
