### ISSUE TITLE
Advanced interogation device not working as intended

### ISSUE THREAD

**Issue by LetterN** [citadel-station/citadel-main#12371]
## Round ID:
23058

## Testmerges:
#12343 : '[Needs testing] Making metastation the meta.' by Detective-Google at commit dd0a48e10f
#12364: 'updates dmapi from dmapi 5.1.1 to dmapi 5.2.1' by deathride58 at commit 49e9c5d57b
#1627: '[WIP]"Unofficial" Combat Rework Part 3: Blocking/Parrying ' by kevinz000 at commit 1c064e9b5a

## Reproduction:
 * Get brainwashed by the advanced interrogation device 

![image](https://user-images.githubusercontent.com/24603524/83013278-50ff7180-a04f-11ea-9e5a-c4612f10d039.png)

**Comment by Trilbyspaceclone** [comment]
Not a bug, the word that I stated was the same word that your mindwashed to not hear.

**Comment by LetterN** [comment]
yes but it the chat should not do that

**Name Name** [verb], "the thing they said, but all in *"
