### ISSUE TITLE
Ghosts can fully interact with Abandoned Crates 

### ISSUE THREAD

**Issue by subtumaka** [citadel-station/citadel-main#124]
[Note]: As a ghost, you can fully interact with abandoned crates to the extent of anything a living person can do to it short of pulling them. As a ghost, you can alt-click to enter a password, if and if the password is correct, it will unlock the crate. Unlocked crates (only unlocked loot crates) can then be opened and closed as many times as ghosts want. 

[Admins]: # I only used admin powers to find out the code of the crate.

**Comment by LetterJay** [comment]
#21153

**Comment by LetterJay** [comment]
Not a bug. Only aghosts can do this.

https://github.com/tgstation/tgstation/issues/21153
