### ISSUE TITLE
Getting eaten while inside of someone causes black screen

### ISSUE THREAD

**Issue by GreenHoodJ** [citadel-station/citadel-main#125]
When inside of someone, getting eaten by another person causes the screen to turn black, and no sounds can be heard. You also cannot see any speech or actions. Seemingly fixed upon being released from the belly.

**Comment by LetterJay** [comment]
When you're released, does it give you trouble coming out or does it work normally?

**Comment by Poojawa** [comment]
Fixed/worked around by #155
