### ISSUE TITLE
Issue with Grill and Bonfire creating infinite food

### ISSUE THREAD

**Issue by MrJWhit** [citadel-station/citadel-main#12547]
## Testmerges:

#12343: 'Making metastation the meta.' by Detective-Google at commit 774f0bce1b
#12412: 'Adds vampires' by kevinz000 at commit ed54e07e18
#12468: 'Box Medbay Rework!' by Detective-Google at commit ae60418174
#12487: 'Adds |italics| _underline_ +bold+ support because why the fuck not' by kevinz000 at commit cc51768223

## Reproduction:

Quote from the person who found it: "I put goliath meat on a bonfire with a grill. Then suddenly it just started spawning steaks and multiplying."

Notably it made a bunch of burned messes.

No runtimes that were relevant from what I could see.
![image](https://user-images.githubusercontent.com/48370570/84813233-9cb59300-afdd-11ea-9de3-809f000b60e5.png)

**Comment by YakumoChen** [comment]
Goliath meat doesn't even microwave or cook like that, it has to be lava cooked...
