### ISSUE TITLE
Broken XenoHybrid Scream

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#12559]
Issue reported from  Round ID: 23329 (Citadel Station)

Reporting client version: 513

Xenohybrids are screaming with the Human scream, instead of the xenomorph death scream

**Comment by Ghommie** [comment]
Not a bug. We found the xenomorph deathgasp a tad too annoying as snowflake xeno-crew scream and removed the feature. Regardless, you are always welcome to PR a shorter xeno-ish scream sound that isn't as much high pitched.
