### ISSUE TITLE
ChemMaster pill type button,and vending mechine icon are missing.

### ISSUE THREAD

**Issue by Sonic121x** [citadel-station/citadel-main#12602]
## Reproduction:
1:Chem master.
![Chem](https://user-images.githubusercontent.com/64410541/85647531-3f9e9900-b6d1-11ea-8a13-030ef657d66b.png)
2:Vending mechine.
![Vend](https://user-images.githubusercontent.com/64410541/85647532-40cfc600-b6d1-11ea-813e-168f16a138d5.png)
other icon are fine.
![Tech](https://user-images.githubusercontent.com/64410541/85647535-41685c80-b6d1-11ea-915c-cbfbdb2b2137.png)

**Comment by Ghommie** [comment]
I'm pretty sure something gone wrong with the new asset cache PR.

**Comment by LetterN** [comment]
fuck, fixing time then!
