### ISSUE TITLE
Techweb pixelart is gone.

### ISSUE THREAD

**Issue by TomGarou** [citadel-station/citadel-main#12613]
Issue reported from  Round ID: 23410 (Citadel Station)

Reporting client version: 513

![image](https://user-images.githubusercontent.com/31218944/85817260-832ded00-b73b-11ea-9060-e6fde4241420.png)

(reloged+refreshed. to check if it was merely a momentary visual bug...persists.)

**Comment by Ghommie** [comment]
Related to #12602.
