### ISSUE TITLE
Pride's Mirror Chasm not Triggering Jaunters

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#12768]
## Testmerges:
#12706: 'adds security/medical records to character setup ' by silicons at commit f7b476bc64
#12728: '"I didn't see the map vote" - Adds a stat vote panel for plurality and approval voting as an alternative to the regular popups.' by silicons at commit 630d65dfec
#12727: 'bandaids around turnstiles being bad code until it can have its movement checks refactored' by silicons at commit 8686029009
#12229: '[READY]TGUI 3.0' by Arturlang at commit 732a1ca438

## Reproduction:
1. Find pride's mirror
2. Equip a jaunter on your belt
3. Use pride's mirror
4. Teleport into space and die anyways because it didn't trigger the wormhole jaunter on your belt

**Comment by Ludox235** [comment]
I'm pretty sure codewise it just teleports you then adds a chasm, instead of just making a chasm that gets you to space. Hence why the jaunter doesn't work.
But anyways, just jab a medipen, gear back up and use the jaunter to get back.
