### ISSUE TITLE
Alkali Perspiration UI Crash (Has existed for 4 months)

### ISSUE THREAD

**Issue by DeusSepulchre** [citadel-station/citadel-main#12831]
The UI for the PanD.E.M.I.C 2200 crashes when you attempt to expand the symptom Alkali Perspiration to view its description, stats, thresholds, etc. I first noted this exact error in early March when writing my virology notes for the Skyrats server which has a derivative of Citadel code. I believe, in a previous PR from the time, I was told that this issue stems from Citadel's code and seeing as it's an issue right now I imagine that it was never fixed. Since not everyone has a gigantic virology spreadsheet for three different servers to reference like I do, I'm going to ask that this gets looked into fairly soon considering PanDEMIC UI crashes are always due to very small syntax errors.
Issue reported from  Round ID: 23703 (Citadel Station)

Reporting client version: 513

**Comment by Arturlang** [comment]
This is due to tgui nextification of the UI, formatting errors and is a easy fix, not able to fix it at a moment but I can guide whoever is willing to. 
Really should have been reported earlier
