### ISSUE TITLE
Xenohybrids can't have temporal scars

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#12870]
Issue reported from  Round ID: 23750 (Citadel Station)

Reporting client version: 513

When i was editing some of my characters, i saw 'temporal scaring' on some of them, but when i switched to my xeno-character, i was given no option to enable them

**Comment by timothyteakettle** [comment]
will fix this for when wounds is next updated

their species traits just needs CAN_SCAR appending to it

**Comment by timothyteakettle** [comment]
fixed
