### ISSUE TITLE
Slime People can take the robo limbs quirk for free points

### ISSUE THREAD

**Issue by Sneakyrat6** [citadel-station/citadel-main#12890]
## Reproduction:

1. Be slime person
2. Take the robotic limb quirk for free quirk points
3. Remove robotic limb via harm intent or surgery
4. Regrow limb

**Comment by timothyteakettle** [comment]
this isn't a bug and cutting your own limb off is going to hurt you, and surgery is a step anyone with the quirk can take

**Comment by Sneakyrat6** [comment]
yes but normal races cant just regrow limbs

also watching a slime person with a robolimb meta rush the removal of the limb at round start is goofy as hell

**Comment by lolman360** [comment]
emergent gameplay tbh

**Comment by DeltaFire15** [comment]
Yeah not exactly a bug
