### ISSUE TITLE
Being able to get off hand as an item you can hold, drag, drop, and do anything with

### ISSUE THREAD

**Issue by xurxomario** [citadel-station/citadel-main#13007]
**Issue reported from  Round ID:** 23895

**Testmerges:** Not sure if there are any that would affect this

**Issue:** Title, you can get off-hand as an item

**Reproduction:** With telekinesis, grab a spear from far away, press Z (or whatever your hotkey to use item in hand is), move the spear with TK, then swap hand and drop the offhand.

**Comment by timothyteakettle** [comment]
issue already reported as #12978 please check for existing issues before reporting stuff (especially when it's like, 4/5 issues down on the list from the top)
