### ISSUE TITLE
Anthro plants will sometimes spend the entire round stuck with a fat moodlet

### ISSUE THREAD

**Issue by tiramisuapimancer** [citadel-station/citadel-main#13023]
## Round ID:
Requires multiple rounds to be observed

## Testmerges:
yes

## Reproduction:

Play as an anthro plant and notice that, on about half of all the rounds played, you will be stuck with a near-permanent negative moodlet from being fat that can only be temporarily dispelled by entering the darkness, which damages you, or consuming lipolicide. The moodlet will come back as soon as you either re-enter the light or run out of the chemical. Some rounds this won't occur and you'll instead just have a permanent stuffed moodlet. 

I think it might be for the best to make it so that anthro plants get slightly less nutrient value from light, requiring them to sometimes eat, or to look into if being in the light simply automatically sets their hunger to fat instead of slowly regenerating their nutrient, or to make it so that the light has a cap on how high your nutrition can be restored by it, requiring eating to get to higher fullness levels. Since they're supposed to be weaker than the regular version of plant people. Also someone should look into if the pod cloning version of the species has the same issue or if it's just the round start version. I can't myself.

**Comment by Ludox235** [comment]
The podpeople have the same issue.
