### ISSUE TITLE
Jaunters do not jaunt

### ISSUE THREAD

**Issue by Hatfish** [citadel-station/citadel-main#13099]
After activating a wormhole jaunter and stepping into it or clicking on it, the wormhole disappears without any sparks or message and you are not jaunted to a random point on the station z-level.  Tested only on lavaland's z-level, but this is presumably an issue on all other z-levels as well.

Steps to reproduce:
1.  Buy a wormhole jaunter
2.  Activate it
3.  Step into it
4.  Watch as nothing happens

Issue reported from  Round ID: 23977 (Citadel Station)

Reporting client version: 513

The following pull requests are currently test merged:
#13002: 'explosions now only hard knockdown for 1-4 seconds instead of 4-16+, instead doing stamina damage. on people affected.' by silicons at commit b20c2ef8e7
#13022: 'increases space levels to 4' by silicons at commit beceef3221
#8017: 'IRV viewer for player rep, TESTMERGE ONLY - Right branch edition' by silicons at commit f8bc890ce3
#13045: 'ports bronze (fake clockwork) airlocks and windows' by silicons at commit d6a5442a37
#13014: '[TESTMERGE] Minimum Megas/Tendrils For Lavaland But Cleaner I Swear' by Hatterhat at commit 76cad8f1bf
#13058: '[testmerge] broom sweeping push object on pre_move rather than moved()' by silicons at commit 3529876aa9
#13057: 'Fixes telekinesis being able to be used to wield objects' by silicons at commit 36bdb9e482
#13055: 'squeaking objects including air horns and clockwork boots now have a default 1 second cooldown. squeaking objects crossing each other will on average only allow 3 squeaks to occur, because if byond is literally running out of sound channels you know the fun has went too far' by silicons at commit 94fa7e4fbb
#12853: 'TGUI4 port' by LetterN at commit d4fc32f158
#12808: 'you can now use any typepath as an emoji :/obj/item/clothing/mask/joy:' by silicons at commit c14a110a97

**Comment by Ludox235** [comment]
If anyone is planning on fixing this bug, the jaunters also for some reason are fucked with by bags of holding, teleporting you into space usually.

This doesn't make any sense considering wormhole technology is supposedly outdated and different than bluespace.
