### ISSUE TITLE
Oddyseus medibeams aren't visible

### ISSUE THREAD

**Issue by rossark** [citadel-station/citadel-main#13121]
This is a disaster waiting to happen.

Issue reported from  Round ID: 24010 (Citadel Station)

Reporting client version: 513

**Comment by lolman360** [comment]
![image](https://user-images.githubusercontent.com/22850904/89881171-79d3e380-dc08-11ea-9625-2cf9c5c36080.png)
tested on a fork, any testmerges on said round?

**Comment by rossark** [comment]
ok this is weird, it works now too in the same round after I crashed...might just be on my side. Which is weird cause I've had it happen before too but only on the pilot. But yeah, I was just really confused.
