### ISSUE TITLE
Slime sentience notifications cannot be disabled

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#13165]
## Round ID:
24061

## Reproduction:
be a ghost, have slimes appear from the pyro anomaly or supermatter delam non-stop
![image](https://user-images.githubusercontent.com/6613514/90298364-062c1380-de60-11ea-991a-33abb89eb5ee.png)

**Comment by Ghommie** [comment]
Should be fixed by the above PR.
