### ISSUE TITLE
Pizza bombs delete brain

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#13200]
haha funny round remove bomb when they shouldn't. Admins told me dev 1 shouldn't fully gib you

**Comment by DeltaFire15** [comment]
Explosions with any deva radius can gib as long as you are in said radius, and have less than like 60 (or was it 80?) bomb armor.

**Comment by YakumoChen** [comment]
Deleting the brain shouldn't be happening though. Especially for a bomb as small as the pizza bomb.
