### ISSUE TITLE
Astrogen kick your very soul out of your body.

### ISSUE THREAD

**Issue by Sonic121x** [citadel-station/citadel-main#13231]
## Reproduction:
1:drink some Astrogen(/datum/reagent/fermi/astral)
2:wait until the Astrogen effect wear off.
3:got kicked out by your own mind.and become a stray Astral projection.unable to return to your body.
![Astrogen](https://user-images.githubusercontent.com/64410541/90930229-cac7b100-e42c-11ea-8813-2047b7e978c9.png)

**Comment by MrJWhit** [comment]
This is the intended behavior of the drug

**Comment by timothyteakettle** [comment]
@MrJWhit no it's not
what's happened is they were forced into their body and it kicked out who was currently in their body
.. which was them
causing them to end up as a ghost permanently
this is not at all intended

**Comment by MrJWhit** [comment]
_OH_

**Comment by DeltaFire15** [comment]
Astrogen has effectively been removed due to issues with it, therefore, closing this.
