### ISSUE TITLE
UI bug from TG-code still here - BSOD

### ISSUE THREAD

**Issue by boniblade** [citadel-station/citadel-main#13285]
## Testmerges: TG fancy gui

Copy paste of my issue from TG github to here:
Unable to get property 'includes' of undefined or null reference
at ~~http://127.0.0.1:56623/tmp4512/tgui-common.chunk.js:1:45991~~ Link doesn't work anymore
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; ASU2JS; Zoom 3.6.0)
State: {"config":{"title":null,"status":2,"interface":"Vending","window":{"key":"[0x2007a1c]-main","size":null,"fancy":1,"locked":0},"client":{"ckey":"biadely","address":"112.206.109.66","computer_id":"4159891279"},"user":{"name":"Moffy Fluffy","observer":0}},"suspended":false,"suspending":false}

Sorry if my issue seems awkward(?) English is not my first language and I don't know how to make proper reports.

**Comment by Arturlang** [comment]
Test again with the statpanel testmerge

**Comment by boniblade** [comment]
![CoderPleaseHelp](https://user-images.githubusercontent.com/41778816/93733406-cd721d80-fc07-11ea-8a78-f16fd8f12ea4.JPG)

**Comment by Arturlang** [comment]
@boniblade Update your internet explorer verson and post the full pic, avoid version 11

**Comment by boniblade** [comment]
Full pic doesn't appear because it's only on the lower right corner - I'll update my IE, will tell you what happens later

**Comment by boniblade** [comment]
I'm confused, is this a good enough version? Don't know how to -manually- update it. Sorry if I seem stupid ![Capture](https://user-images.githubusercontent.com/41778816/93747218-f8b93480-fc28-11ea-81ce-6007d79dba34.JPG)

**Comment by boniblade** [comment]
![Capture](https://user-images.githubusercontent.com/41778816/93750636-5ef48600-fc2e-11ea-9669-f503f7a18846.JPG)

**Comment by boniblade** [comment]
Woah what the

**Comment by boniblade** [comment]
Shortly after I clicked the link on the bottom, everything looked like as it was before this post. I don't know what happened, but thank you!!

**Comment by Arturlang** [comment]
If you have problems, just google windows internet update
