### ISSUE TITLE
BUG- Podmen healing got reversed?

### ISSUE THREAD

**Issue by VitorGoatman** [citadel-station/citadel-main#133]
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)
Hello I think the podmen regen got reversed somehow.

When I spawn my hunger quickly drops and I keep getting damaged all over my body. Cloning doesn't fix it. I have 2 screenshots of me dying if it helps.

https://i.gyazo.com/0341d301f1b9e971fb020bae43431165.png

https://i.gyazo.com/7fc3a62c1c68d8a3bee7e6b0ac1cdc01.png

**Comment by LetterJay** [comment]
This was fixed in #116
