### ISSUE TITLE
[URGENT] TGChat keyword highlighting prevents clicking of any links

### ISSUE THREAD

**Issue by jack-avery** [citadel-station/citadel-main#13315]
## Round ID:
24260
(probably doesn't matter)

## Testmerges:
#13274 at 34e0da2, #13273 at cf85d68, #13270 at e6008f6, #13295 at 5dce47b, #13289 at 578f078, #13309 at afa9993
(probably doesn't matter)

## Reproduction:
1. be a ghost or AI
2. have a message in chat match one of your TG Chat highlight words
3. try to click the (F) or the player's name to orbit the message source
without reading the code i assume it to be as if the highlight itself is an overlay and is blocking interaction with the link

This is more urgent than I thought. This means that, if a message is highlighted, the person cannot:
- Follow as a ghost
- Track as an AI
- **RESPOND TO AN ADMINISTRATOR MESSAGE**
- I assume this also includes administrator tools to follow people performing important actions (e.g, the (JMP) on messages such as The Supermatter being powered on for the first time.)

**Comment by DeltaFire15** [comment]
This got resolved somewhen.
