### ISSUE TITLE
Turrets disappear from reality once you break off the outer plating.

### ISSUE THREAD

**Issue by HeroWithYay** [citadel-station/citadel-main#13328]
## Details 

In normal gameplay after taking enough damage the metal outer casing of a turret should break away, exposing the inner part which can be salvaged with a crowbar. This is how the station would normally obtain a few space ruin exsclusive weapons. For whatever reason some time around TGUI 4 this stopped working and the turret is just deleted from existence the moment they take enough damage. 

## Round ID:
N/A
Happens consitently every round without fail

## Reproduction:

Just waltz over to any of the turrets in space ruins that have those grey disc-shaped unfolding shells and hit it a few times. You'll notice that after it's been thoroughly bonked the entire turret vanishes rather than just the outer layer like normal.

**Comment by timothyteakettle** [comment]
will look into this now
