### ISSUE TITLE
Hijack Implant can no longer access any interface under your control with new TGUI

### ISSUE THREAD

**Issue by necromanceranne** [citadel-station/citadel-main#13376]
Most machines are inaccessible with the hijack implant right now. If this is working like an AI or borg, you should have remote access to anything in the room you're in and full functionality with those machines. 

But as it stands, you only have access to the APC. You can click and access the interface itself of a machine (like a chem dispenser or a vendor), but everything is greyed out and unusable.

Also, some machines can't even be used. It seemed like I couldn't access chemmasters.

**Comment by Arturlang** [comment]
/obj/machinery/can_interact(mob/user) must be failing to ui_interact?

**Comment by Arturlang** [comment]
Might be attackby, APCs are the only have that have ``if(area.hasSiliconAccessInArea(user) && get_dist(src,user)>1)
		return attack_hand(user)``

**Comment by Ghommie** [comment]
This should have been fixed by Arturlang in a PR I recently merged.
