### ISSUE TITLE
Mech suits icons don't show up 

### ISSUE THREAD

**Issue by tiramisuapimancer** [citadel-station/citadel-main#13428]
Issue reported from  Round ID: 24519 (Citadel Station)

Reporting client version: 513.1526

It just does the SUIT shit in the corner like when any jumpsuit sprite bugs out. Come on man I just want my Eva memes.

**Comment by DeltaFire15** [comment]
Did you have digitigrade legs when this issue was present or not?

**Comment by tiramisuapimancer** [comment]
nope

**Comment by tiramisuapimancer** [comment]
OH SHIT WAIT YES I DID I FORGOT WHAT SERVER I HAD THIS ISSUE ON WHEN I WAS REPLYING THRU EMAIL I AM SO SORRY

**Comment by DeltaFire15** [comment]
Digitigrade sprites for mech suits have now been added.
