### ISSUE TITLE
alt click broke

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#13440]
TGUI fucked with alt click, now you have minimal interaction with objects in the alt click screen and all the icons are broken

**Comment by SandPoot** [comment]
They said the part about interactions was intentional because tg didn't do it and unless someone does it, we won't be having them.

**Comment by YakumoChen** [comment]
What the fuck? That's the only way to do interactions while dealing with layer shit most of the time, or clicking small items, or interacting with things under full tile sprites

**Comment by SandPoot** [comment]
We are now open to cry or try to do some pr ourselves.

**Comment by DeltaFire15** [comment]
The Alt click menu now once again allows access to (most) functionalities.
