### ISSUE TITLE
Dice bag folds into cardboard, does not fold back

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#13492]
![image](https://user-images.githubusercontent.com/10399117/94883862-40c32d00-045b-11eb-8a16-c7605b5e2d34.png)
my immersion is ruined

**Comment by Ragolution** [comment]
Intended. (Pretty sure.)

**Comment by YakumoChen** [comment]
why isn't it made of cloth
why is it just a box child but poorly made

**Comment by Ragolution** [comment]
it predates cloth

**Comment by Ragolution** [comment]
ffffffffffffine
