### ISSUE TITLE
Gaia trays are not yellow after being planted in

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#1351]
1. Get a tray yellow via Gaia compost
2. Plant anything into the tray with Gaia in it
3. Sprite returns to normal blue, but still has Gaia properties.
It's just a visual glitch, and for some reason it flickered occasionally back to yellow really quickly then back to blue. Still kinda annoying.

**Comment by Poojawa** [comment]
overlay issue. likely has been resolved in one of the various fixes.

**Comment by Poojawa** [comment]
actually, it's more just the change in our tray sprites, sooo
