### ISSUE TITLE
Arachnids are not playable

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#13620]
[Round ID]: I don't know what round I noticed this in.

## Testmerges:

I don't remember, but here's the PR that added arachnids.
#13473 

## Reproduction:

Look in the list where you pick your character's species and see that arachnids are not available.

**Comment by BlueWildrose** [comment]
This probably needs to be changed via the server's own config.

So someone with access to said config will have to change it.

**Comment by BlueWildrose** [comment]
actually I see arachnids in the race list, so this is probably fixed.
