### ISSUE TITLE
Emagged satellites do nothing

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#13663]
Not sure if this is a bug or an oversight. Either it's broken or it has a value so low that it will never occur through the use of the emag. Go try it, Use an entire emag on satellites and see what happens. Nothing at all.

**Comment by DeltaFire15** [comment]
How many people were there playing at that time? If it was less than 15, there might've just been too few for the event to fire.

**Comment by Arturlang** [comment]
Did you set up the emagged satelites?

**Comment by lightcat** [comment]
> How many people were there playing at that time? If it was less than 15, there might've just been too few for the event to fire.

That would be the problem then.... so that I know of.



> Did you set up the emagged satelites?

Yes
