### ISSUE TITLE
Viral Mech Domination  Might(?) Not be working.   

### ISSUE THREAD

**Issue by R3dtail** [citadel-station/citadel-main#13768]
Issue reported from  Round ID: 25313 (Citadel Station)

Reporting client version: 513.1536

Basically, had it reported that upon purchasing the ability, there was only a sound played, and no new icons showed up in the "malfunction" tab, nor did a new ability icon show up.  Right clicking on the mech did not give any new options, either.  Considering how rarely malf rolls, it's not something that is easy to test in a live environmet (and I'm on the verge of passing out as typing this so can't test it either ATM).

**Comment by YakumoChen** [comment]
I believe you have to left click the mech and a link in chat titled "ASSUME DIRECT CONTROL?" Displays in large red letters you have to click. Also gives you a readout of the mech weapons like an examine would.

**Comment by R3dtail** [comment]
Considering that's how the wireless AI control module works I'm willing to believe that.  "Fuck around and find out" applies I suppose.

**Comment by DeltaFire15** [comment]
Yeah, what Chen said. Domination just has a different text for remote controlling, plus it's in red, other than that it is accessed the same way like the default mecha remote control.
