### ISSUE TITLE
Borg Medical Injector and Synthesizer

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#13861]
Issue reported from  Round ID: 25442 (Citadel Station)

Reporting client version: 513.1538

Medical Borgs can no longer inject anyone laying on a table when damaged, but still can if they're laying on a floor, buckled to a chair, or standing. I believe this is being caused by #13811 somehow?
Medical Synthesizer readout in the status panel also does not update properly.

**Comment by DeltaFire15** [comment]
Pretty sure this isn't table-related, but has to do with a active surgery on them instead?

**Comment by TripleShades** [comment]
No, I also tried when a surgery was not in progress, I believe.

**Comment by TripleShades** [comment]
Closing issue to reopen with updated information
