### ISSUE TITLE
Syndicate Abandoned Listening Post Has Broken Disposals

### ISSUE THREAD

**Issue by GirlieAllie** [citadel-station/citadel-main#1386]
In the asteroid abandoned syndicate listening station, it is possible to become entirely encased in rock by jumping into the disposals chute found within the break room that contains two vending machines. Issue found while being placed inside as a pAI, and confirmed by a derelict drone that followed me in as well. Trash put into the disposals beforehand was found in the same location as well. Revision unknown. [http://imgur.com/a/rICki](http://imgur.com/a/rICki)

**Comment by Poojawa** [comment]
Gunna fix this after #1883 goes through. though it's a pretty simple fix you could probably make to TG as well.
