### ISSUE TITLE
Infinite Cabbage Patch Kids

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#13860]
Issue reported from  Round ID: 25439 (Citadel Station)

Reporting client version: 513.1538

Mutating cabbages with Left 4 Zed or E-Z Nutrient eventually causes the cabbages on harvest to spawn infinite human monkies (cabbage patch kids)

I believe this is happening because the tray's autogrow function stops a plant from formally becoming the mutated plant, but keeps letting the current plant in the tray gain genes, possibly related to the entire pool(??) of what that plant could normally mutate to gain, or what their mutation results might be able to gain(?????) because turning the autogrow off allows the plant to formally mutate and resets the traits like normal (in the case of cabbages, they formally turn into a replica pod in the tray)

Replication steps:
Plant Cabbage in Tray
Turn tray's autogrow function on (IMPORTANT!!!)
Tend to as normal with E-Z Nutrient and Left 4 Zed
After about three or so harvests, you start to harvest your cabbage patch kids
Repeat until plant is removed or the tray's autogrow is off, thus allowing it to fully mutate the plant into a Replica Pod

**Comment by timothyteakettle** [comment]
slightly confused at this but if nobody else works it out ill have a look at it soon

**Comment by TripleShades** [comment]
#14566 fixes this, closing issue.
