### ISSUE TITLE
Abductor Fleshy Mass Removal Doesn't Fix The Objective-Giving Trauma

### ISSUE THREAD

**Issue by Hatterhat** [citadel-station/citadel-main#14058]
## Round ID:
25697
## Testmerges:
#13770: 'Adds a spontaneous guardian spirit event.' by Putnam3145 at commit 72d99776b6
#13895: 'Restores speedup to meth and nuka cola' by silicons at commit 005f7e2d6d
#14047: 'boomerangs now properly turn ON your throw mode rather than turning it off when it already is' by silicons at commit 06bc57580a
#14046: 'buffs and fixes BOOMERANG STUNBATONS' by silicons at commit 701bacd355
#13962: 'Porting cloaks from Beestation' by MrJWhit at commit 13bf9a4bb9
#13610: 'Makes the atmos subsystem pause correctly' by Putnam3145 at commit 6dfcf12773
## Reproduction:
- acquire abductor victim
- remove abductor victim heart
- according to #10295, this should clear out their quirky abductor objective
- (it does not)

note: i think it'd be nice if it removed the deep-rooted trauma too, or at least downgraded it to something treatable that didn't involve lobotomy

**Comment by DeltaFire15** [comment]
Not a bug. That PR was modified to require brain surgery / lobotomy instead of gland removal pre-merge, as is stated in the PR name.
