### ISSUE TITLE
(Test Server) Buying a shuttle function does not seem to work

### ISSUE THREAD

**Issue by Roland410** [citadel-station/citadel-main#141]
By default the station has 5000 credits, but even if I join in as captain or use a sandbox ID, the purchase shuttle function brings me to a menu with the budget being displayed and no selectable options other than going back to the main menu.
![screenshot 2017-01-11 09 05 50](https://cloud.githubusercontent.com/assets/6581435/21840393/94fe68e8-d7dd-11e6-90b6-87df3ae0189f.png)

**Comment by LetterJay** [comment]
fixed in #175
