### ISSUE TITLE
Alcohol Intolerance and Synthetics

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#14177]
Issue reported from  Round ID: 25833 (Citadel Station)

Reporting client version: 513.1538

The quirk Alcohol Intolerance does not work at all on synthetics and possibly IPCs.
Character did not receive corruption, nor did they receive toxin, and the character did not get drunk (not sure if related.)

**Comment by DeltaFire15** [comment]
Synthetics are not affected by alcoholics at all, which overrides alcohol intolerance and simillar. The trait simply has no effect if present in synthetics (unless they become a nonsynthetic via species changes), which is intentional.
