### ISSUE TITLE
Crowbars act like jaws of life

### ISSUE THREAD

**Issue by R3dtail** [citadel-station/citadel-main#14297]
Issue reported from  Round ID: 26138 (Citadel Station)

Reporting client version: 513.1542

You can just, use crowbars like jaws of life, and they pry open any door.

**Comment by shellspeed1** [comment]
honestly a really nice feature for alien crowbars, but for standard crowbars its definitely a problem.

**Comment by SandPoot** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14299 someone close this issue.

**Comment by The-Sun-In-Splendour** [comment]
> 
> 
> #14299 someone close this issue.

For future reference, place "fixes #14297" in your PR so it auto-closes the issue
