### ISSUE TITLE
Crowbar and Hemostat cannot remove IPC eyes even on help intent

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#14317]
Issue reported from  Round ID: 26163 (Citadel Station)

Reporting client version: 513.1533

As the title says, the step screws up and requires a different tool for both the Crowbar and hemostat.

**Comment by DeltaFire15** [comment]
Worked fine when tested by me. Needs replication

**Comment by keronshb** [comment]
I think this is fixed.
