### ISSUE TITLE
Drones delete items if they try to place items on tables or in closets

### ISSUE THREAD

**Issue by BlueWildrose** [citadel-station/citadel-main#14377]
Issue reported from  Round ID: 26304 (Citadel Station)

Reporting client version: 514.1547

**Note that this is with the TGS Hardsync 1.5.**

Self explanatory, what the title says.

Reproduction is simply repeating what is said in the title.

Dropping items onto the table or into the closets work, but trying to place them via clicking on the closet or table doesn't.

**Comment by LetterN** [comment]
oh fuck i forgot to rever that minor inventory change
