### ISSUE TITLE
Surgery - Tend wounds fix injury operation not repeating

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#14370]
Issue reported from  Round ID: 26268 (Citadel Station)

Reporting client version: 513.1542

The tends wound surgery, done by a medical borg, is not repeating while a carbon mob has the corresponding damage to the surgery.

**Comment by LetterN** [comment]
Hardsync issue, fixed.

**Comment by LetterN** [comment]
@silicons close issue
