### ISSUE TITLE
AI "Set AI Core Display" displays two different ways of selecting the display, the new one being broken.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#14387]
## Reproduction:
Be AI, hit Set AI Core Display, get this. 
https://i.imgur.com/neJqRNY.png

**Comment by LetterN** [comment]
code responsible for ai chang:
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/3693eb1f168020ef6920dee6ea76c86bf0d8e9be/code/_globalvars/lists/flavor_misc.dm#L156-L166
