### ISSUE TITLE
Renault in bag

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#14417]
## Reproduction:
Put renault in a bag then take him out. Obtain 1 ghost renault in your arm that you can drop while the real one sits on the floor. I was using a satchel of holding if that matters.

**Comment by WanderingFox95** [comment]
This is the case for all pets you can pick up and put in your bag, including Ian (or any corgi), Runtime (or any cat), Renault (or any fox), etc. And yes, they fit in normal bags too.
