### ISSUE TITLE
Laptops can't be picked up and have very confusing controls for operating them.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#14424]
## Reproduction:
Get a laptop from the vendor, try to pick it up.
Opening the laptop needs you to drag and drop to an empty tile.
Dragging and dropping the laptop to your sprite makes it open and close.
Alt clicking the laptop closes it. You cannot close it by dragging and dropping.
To pull an ID card out, you need to alt click it while it's closed, and you cannot do it while it's open.

**Comment by LetterN** [comment]
drag the laptop on your hand slot to pick it up, as attack hand opens/closes it
