### ISSUE TITLE
department techfab (Service) outputs Automated Hydroponics system [Machine] NOT [Board]

### ISSUE THREAD

**Issue by Solaris-Shade** [citadel-station/citadel-main#14531]
## Round ID:
26558

## Testmerges:
The following pull requests are currently test merged:
#14443: 'Another dreaded baton rework pr; batons knockdown and slow on rightclick (with a cooldown), otherwise stagger, plus more' by necromanceranne at commit 8091844a1c
#14418: 'Updates openspace & enables perlin generation on alvaland & icebox/snaxi' by LetterN at commit e3fb2d5491
#14528: 'Fixed being unable to fix suit sensors if damaged at all unless destroyed completely' by BlueWildrose at commit f6b3ef0893
#14527: 'Fixes order-of-nullspacing boards' by LetterN at commit 9c3c9861ab
#14526: 'what if i just gave the x01 an rmb taser while also giving it, like, way more disablers' by Hatterhat at commit c3b68e4d8a
#14518: 'Shields: Changes, additional flags, bug fixes, sprites' by necromanceranne at commit 2368968c66

## Reproduction:
Issue is department techfab (Service) outputs entire [Machine] Automated Hydroponics system NOT [Board]. [Machine] outputs on same tile as department techfab (Service) and is [Anchored]. Verified material cost to match the amount for the [Board]. Disassembled Machine to verify all parts are in [Machine] to include the [board].

**Comment by Linzolle** [comment]
fixed by  #14533
