### ISSUE TITLE
Masochism unwanted erp

### ISSUE THREAD

**Issue by The-Sun-In-Splendour** [citadel-station/citadel-main#14557]
## Reproduction:
1. be cyborg (idk if it works as any other being than cyborg)
2. CTRL + Click pull someone
3. murder them mercilessly with a circular saw
4. 
![Screenshot_1974](https://user-images.githubusercontent.com/70348069/113361208-b85f0f80-934b-11eb-893f-ca8ed0daf52a.png)

No I don't want to fucking cum with someone I'm brutally murdering fuck off

**Comment by silicons** [comment]
@Putnam3145
