### ISSUE TITLE
ling nerf plz (salty lozer)

### ISSUE THREAD

**Issue by Insane-Jimmy** [citadel-station/citadel-main#14572]
## Reproduction:
thats right, after i salted my ass off because of lings outhealing literally everything, even 4 point blank buckshots (that someone else did and i watched), i am now on the ling nerf train and i am making this "bug" report just so i can salt my ass off even further
and probably get this report get deleted cuz its not a bug or some shit, but regardless, plz nerf linggers cuz they 2 op and they just fucking snowball if its lowpop and if people aren't even prepared, even if they are prepared, they'll just OUTHEAL the godamn damage! FUN!

**Comment by TetrakoHateThis** [comment]
The man has a point tho.

**Comment by The-Sun-In-Splendour** [comment]
Just use dragonsbreath rounds. Even if the ling is fireproof somehow he won't be able to fleshmend.
