### ISSUE TITLE
Pacifism detects Beanbag rounds as lethal

### ISSUE THREAD

**Issue by bob-carter** [citadel-station/citadel-main#14590]
I had the trait on, and it said those were lethal

Issue reported from  Round ID: 26706 (Citadel Station)

Reporting client version: 513.1539

**Comment by ghost** [comment]
don't think it's a bug
beanbags iirc deal low brute damage but a good quantity of stamina damage. any kind of possibly lethal action will be stopped by pacifism trait. that brute damage COULD be lethal
actual thing to ponder is should beanbags deal any lethal damage?

**Comment by YakumoChen** [comment]
Pacifism checks the gun, not the ammo. Not a bug. Shotguns are considered lethal weapons and a no-go for pacifists.

**Comment by The-Sun-In-Splendour** [comment]
Pacifism also makes the multiphase unable to be shot

And also makes the BIG IRON unable to be shot even if it's fully loaded with disablers

**Comment by YakumoChen** [comment]
For the exact same reason I stated above, that isnt a bug

**Comment by ghost** [comment]
> Pacifism also makes the multiphase unable to be shot
> 
> And also makes the BIG IRON unable to be shot even if it's fully loaded with disablers

>Pacifism checks the gun, not the ammo. Not a bug. Shotguns are considered lethal weapons and a no-go for pacifists.

i had to deal with pacifism bugs recently, and reading gun code, it seemed that it SHOULDN't work like that. it really looked like ONE of the checks was for ammo. if there is one for gun as well that's a little silly but whatever
i swear it checked for ammo, it was in fact a glitch related to the ammo that i had to fix to make PKAs unusable by pacifists

**Comment by DeltaFire15** [comment]
Not a bug nor oversight. Beanbag rounds deal ~~small~~ medium amounts of brute damage, making their designation as harmful reasonable.
