### ISSUE TITLE
Tucking Diskie Spam

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#14694]
Issue reported from  Round ID: 27045 (Citadel Station)

Reporting client version: 513.1533

Tucking the nuclear disk into bed still spams, despite there having been a pr to make it not do this?
Wait yeah here it is #14023 fuck

**Comment by ghost** [comment]
it happens every 2 or so seconds, imo that's very spammy as well, i would turn it up to 30 seconds or maybe one minute
