### ISSUE TITLE
Stacking Machine Broke

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#14745]
Issue reported from  Round ID: 27238 (Citadel Station)

Reporting client version: 513.1533

The stacking machine and/or the computer interface for releasing materials is broken, and does not count any materials.

**Comment by ghost** [comment]
It's working as intended. Stacking machine can be connected to a silo or equivalent remote storage so it sends any compatible materials to it. So whenever it catches most of the stuff that CAN be added to a silo, it just gets sent and disappears. Other materials, like wood or cardboard will be collected, until it's full of that material, and then it will spit it out.
On my tests, it all worked, again, as intended.

**Comment by TripleShades** [comment]
Previously, it would catch metal and glass, and you had to manually dispense them. Was that the machine working improperly then?

**Comment by ghost** [comment]
yep, it started unlinked from the silo, which is less "unintended" and more "hey nobody fucking knew it could even be linked"
dont even know why or HOW it was fixed

**Comment by TripleShades** [comment]
alright thanks, closing this then
