### ISSUE TITLE
AI Shells Bug

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#14746]
Issue reported from  Round ID: 27239 (Citadel Station)

Reporting client version: 513.1533

If an AI has multiple of the same type of shell, you cannot connect to both once it gets renamed, because they both have the same name, instead of incrementing in number.

**Comment by Arturlang** [comment]
This issue is caused by AI shells not getting unique numbering, them always being 0

**Comment by TripleShades** [comment]
This is still happening, but this is also a duplicate of #14425 so closing.
