### ISSUE TITLE
Chest infections untreatable

### ISSUE THREAD

**Issue by kiwilover8** [citadel-station/citadel-main#14838]
## Reproduction: Get an infection in the chest beyond initial infection.

We do not have any known chems to treat infections, so your only options to treat them are surgery, full cloning, or fully replacing the infected limb. As infections can also manifest in the chest, that means you need a body augment surgery or the intended treatment of the excise flesh, then wrap gauze. The issue, is the sheer number of times you need to excise flesh, as well as the sheer amount of gauze needed, on top of the fact that, while performing these surgeries, each excising of flesh causes a sizable amount of brute damage, the infection is constantly dealing toxin damage, and the infection continues to cause spread instances. Each instance of excising takes a noticeable amount of gauze, and each time you excise you must wrap gauze once. This means that, for worse infections, you must excise dozens upon dozens upon dozens of times, then wrap that much gauze. In the time it takes to even collect the materials for and perform these steps, the infection will spread again creating new instances of needing to excise the flesh. Due to the obscene amount of gauze needed and the amount there is per stack, it's not reasonable to ever have enough gauze on hand to treat even one infection in the chest. As we also do not have chems to actually treat the infections, we cannot use any alternatives besides cloning or fully body part replacements, which is again unreasonable for the chest. I've personally tried to spend over an hour trying to treat a chest infection on a patient, only to be completely unable to overcome its inherent re-spreading and eventually ran out of gauze entirely. Either make instances of gauze go farther than a 1:1 ratio, possibly acting similarly to a cautery in most normal surgeries as you already perform multiple excises in the same instance, likely the brute damage also needs to be dropped as you can only realistically perform 3-4 instances of it before critting the patient, compounded by the toxins damage from the infection.

**Comment by keronshb** [comment]
This might need replicating.  I fixed a third degree burn on myself yesterday using nothing but gauze and burn mesh.  All I needed was 1 full use of gauze and 1 full use of burn mesh.

**Comment by kiwilover8** [comment]
a third degree burn isn't the same as an infection, the infection has its own stages to it. There's the wound, and the infection is a separate entity related to but different from it. If you let the stages of infection progress beyond a certain point, it becomes completely infeasible to treat as well, as I outlined.

**Comment by kiwilover8** [comment]
If you let the stages of infection progress beyond a certain point, it becomes completely infeasible to treat as well.

**Comment by bunny232** [comment]
This is a non issue as you can just use the round start cryopods to resolve the infection

**Comment by JogBoba** [comment]
Unless I’m mistaken, an infection past early stages is no longer treatable via cryopods.

**Comment by DeltaFire15** [comment]
Chest burn infections are indeed finnicky, though the fact they are nearly untreatable past their final stage is not a bug.
Once it reaches that state, you indeed need to augment / replace it with a borg or a limbgrower chest (unless they already have an cyborg chest in which case that doesn't work).. or cryo them apparently, since cryoxadone seems to still work on fully infected burn wounds.

General treatment of burns is not too difficult pre final infection state either, Bandages (aka gauze), regen mesh, ointment, spaceacillin, sterilizine, miner salve, uv flashlights (the pen thing all med docs get), synthflesh and burn dressing (debridal) surgery can all be used to treat it in combination.

All in all, not an issue.
