### ISSUE TITLE
Spraybottle Spray Broken

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#14900]
Issue reported from  Round ID: 27657 (Citadel Station)

Reporting client version: 513.1533

When spraying a spraybottle, the spray stays in place and turns into a static texture called Chemicals.
It also does not do anything (ex. cleaning bottle spray wont clean) because of this.

**Comment by BlueWildrose** [comment]
I believe this was already fixed, albeit whoever fixed it decided to exclude the sound that came with it.

**Comment by TripleShades** [comment]
> I believe this was already fixed, albeit whoever fixed it decided to exclude the sound that came with it.

I think Silicons fixed it, but I can close this now since they work (even if missing the sound.)
#14903
