### ISSUE TITLE
Phobia deletes trigger text.

### ISSUE THREAD

**Issue by KareRott** [citadel-station/citadel-main#14948]
When taking Phobia quirk (and I assume acquiring through brain trauma), words that trigger your phobia are removed from other people's speech. This can be quite confusing when having phobia, some times not knowing who or what is triggering it.

Here is a screen shot where the word "laser" is removed from a radio communication:
https://cdn.discordapp.com/attachments/336748540690825216/865064894268571688/85c68546dc7f5ca2edce1fb5f10726e1.png

I was told that this could be a hardsync issue. I first noticed this bug many months ago, thought someone might have caught it by now. Turns out, this has been like this for so long that some people think it is as intended.

one more example screenshot.
https://cdn.discordapp.com/attachments/864286674245648396/865424533690384395/2e4b276015fab0f0dd78a4e848209028.png

**Comment by KareRott** [comment]
one more example screenshot.
https://cdn.discordapp.com/attachments/864286674245648396/865424533690384395/2e4b276015fab0f0dd78a4e848209028.png

**Comment by DeltaFire15** [comment]
yeeah, while this is reasonable for the hypnosis trauma, phobia should probably only highlight it. This apparently has been the case for close to two years, by the way.
Looking into it.

**Comment by KareRott** [comment]
Not a very easy fix, eh? It's so rare that anyone would take the phobia quirk, and even more rare that anyone would get phobia from a brain injury. So I really don't think this should take any priority over something else.

**Comment by DeltaFire15** [comment]
> Not a very easy fix, eh? It's so rare that anyone would take the phobia quirk, and even more rare that anyone would get phobia from a brain injury. So I really don't think this should take any priority over something else.

Not as much that as just the fact I had no idea how regular expressions worked in byond so I had to find some time to read the documentation for it.
