### ISSUE TITLE
Oxygen damage stops nanite defib from working.

### ISSUE THREAD

**Issue by TheEaterOfBeans** [citadel-station/citadel-main#14990]
## Round ID
didn't look and the round is over

## Testmerges:
didn't look and the round is over

## Reproduction:
Step 1: Make reviver nanites.
Step 2: Get reviver nanites.
Step 3: Suffocate yourself.
Step 4: Watch as the nanites try and fail to defibrillate you despite you only having the one type of damage that DOESN'T stop defibrillation.

**Comment by DeltaFire15** [comment]
gonna look into this somewhen soon
