### ISSUE TITLE
power alarms sticking around after being fixed

### ISSUE THREAD

**Issue by bunny232** [citadel-station/citadel-main#14997]
## Testmerges:
#14685: 'Reworks blood regeneration into something a bit more tame' by Arturlang at commit 5acd7fef2d
#14971: 'Ports update appearance' by Arturlang at commit feac8568b6
#14983: '(Please testmerge first) Enables monstermos' by Putnam3145 at commit 7e34540903
#14978: 'Adds military gas mask for donator' by LetterJay at commit f327592784

## Reproduction:
cause a power alarm, fix the power alarm, walk to a alarm console witness how they are still reporting the power alarms.

**Comment by Arturlang** [comment]
#14971 messes with APC code, probable cause
