### ISSUE TITLE
Energy guns don't change icon states until fired

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#15030]
Issue reported from  Round ID: 28109 (Citadel Station)

Reporting client version: 514.1557

Before: If you hit Z on an energy gun to swap between Disabler or Leathal it would switch instantly.  Now you need to fire the gun first for the icon state to change

**Comment by UncleBourbon** [comment]
Also will add that rechargers are busted like this as well, you insert a weapon and the recharger is still blank. Making you have to examine the recharger constantly to know if your weapon is done charging.
