### ISSUE TITLE
Can't play Citadel - "Bad Index" errors

### ISSUE THREAD

**Issue by kannthus** [citadel-station/citadel-main#15046]
## Can't play Citadel- "Bad Index" errors

After using the Build.bat and running the server I get the following errors in my Dream Daemon. This happens regardless of what version of byond used.

I can connect to the server, but none of the UI elements load properly and just stay stuck at "Loading..."
[As shown here:](https://i.imgur.com/zY2gjx6.png)

I can click on certain menus here and there, but none of them fully load as expected.

Version: 514.1565 and 514.1561

```
BYOND hub reports port 6666 can be reached by players.
runtime error: bad index
proc name: Get (/datum/controller/configuration/proc/Get)
  source file: configuration.dm,223
[08:18:08] Runtime in configuration.dm,223: bad index
  proc name: Get (/datum/controller/configuration/proc/Get)
runtime error: bad index
proc name: Get (/datum/controller/configuration/proc/Get)
[08:18:54] Runtime in configuration.dm,223: bad index
[08:18:54] Runtime in configuration.dm,223: bad index
[08:18:54] Runtime in configuration.dm,223: bad index
[08:18:56] Runtime in view.dm,10: list index out of bounds
[08:18:56] Runtime in view.dm,99: cannot read from list
[08:18:56] Runtime in client_procs.dm,999: change_view called without argument.
[08:18:57] Runtime in configuration.dm,223: bad index
  usr: Kannthus/(Kannthus)
  usr.loc: (start area (11, 174, 1))
[08:18:57] Runtime in configuration.dm,223: bad index
  usr: Kannthus/(Kannthus)
  usr.loc: (start area (11, 174, 1))
[08:18:57] Runtime in configuration.dm,223: bad index
[08:18:57] Runtime in configuration.dm,223: bad index
  usr: Kannthus/(Kannthus)
  usr.loc: (start area (11, 174, 1))
  (This error will now be silenced for 10 minutes)
```
[Full pastebin here:](https://pastebin.com/kV3UPxbh)

## Reproduction:

- Download the Citadel Station ZIP
- Unzip
- Build via build.bat
- load via Dream Daemon
- Kaput

Update:
I ran the dream daemon server on my PC instead of on my remote server (windows 2019 server) and it doesn't have the issue. So I am at a complete loss as to what the issue might be.

**Comment by BlueWildrose** [comment]
@kannthus 
Later versions of the beta BYOND build seem to be pretty fucky right now. Try 514.1557.

**Comment by Putnam3145** [comment]
it's the byond *stable* build now that's fucky, and yes, try an earlier version.

**Comment by kannthus** [comment]
> @kannthus
> Later versions of the beta BYOND build seem to be pretty fucky right now. Try 514.1557.

Hey!

We went back to 1557 and it managed to reduce a few of the errors, so progress! Except in the process it has caused another error to surface which is quite gamebreaking.

The window that pops up when you join the server, the "New Player Panel" which lets you click "Join Game" or "Setup Character" yeah, none of the buttons of that do anything now. Here is the error that shows up when you attempt to click Setup Character. 

```
[03:29:50] Runtime in _lists.dm,716: Unknown value:                               
  proc name: safe json decode (/proc/safe_json_decode)
  src: null
  call stack:
  safe json decode(null, /list (/list))
  /datum/preferences (/datum/preferences): load character(1, 0)
  /datum/preferences (/datum/preferences): New(Kannthus (/client))
  Kannthus (/client): New(null)
  Kannthus (/client): New()
```
  
I've tried stuff like: Installing every version of C++ (Just incase) and .NET 3.5/4 with no effect. These errors don't show up when we tried running the server locally on our PCs, but it is an error on our windows 2019 server. I have a gut feeling its some sort of dependency issue, but I have no idea what the dependencies for citadel are (aside from C++)


Edit: It appears to be to-do with the 18+ menu being broken, as mentioned here: https://github.com/Citadel-Station-13/Citadel-Station-13/issues/15035

**Comment by LetterN** [comment]
did you delete the entire config dir? because you should **not** do it. You should only change the values in the config dir unless you know what you are doing.

**Comment by kannthus** [comment]
> did you delete the entire config dir? because you should **not** do it. You should only change the values in the config dir unless you know what you are doing.

Nope, haven't touched the config file aside from adjusting the typical settings like adding admin ckeys and the sort

Its related to the bugged 18+ player menu, as it will say people haven't confirmed their age except it never shows up at all. the only way around this right now would be giving everyone admin, which.. isn't going to happen. so we are temporarily running a different codebase until we get advise on the matter (Questioned in coderbus and they helped to the best of their ability but to no avail)
