### ISSUE TITLE
Blood from specific human species (especially notably slimepeople) are discolored, except for footprints.

### ISSUE THREAD

**Issue by BlueWildrose** [citadel-station/citadel-main#15051]
Generally non-human blood is colored a certain way. But, it isn't in this case.

![](https://i.imgur.com/4WZfOaj.png)

I'm assuming this is because we're using a non-monochrome variant of blood as a sprite here.

## Reproduction:

Cut shit up.

**Comment by TheEaterOfBeans** [comment]
I looked in the blood icon file and all the blood is red so...
