### ISSUE TITLE
airlocks have no armor

### ISSUE THREAD

**Issue by zeroisthebiggay** [citadel-station/citadel-main#15078]
## Round ID:

it does not matter

## Testmerges:

probably does not matter

## Reproduction:

take a lightbulb
break it
use it to break open an airlock and completely ignore the
#define AIRLOCK_DAMAGE_DEFLECTION_N  21  // Normal airlock damage deflection
#define AIRLOCK_DAMAGE_DEFLECTION_R  30  // Reinforced airlock damage deflection

**Comment by BlueWildrose** [comment]
This got fixed
