### ISSUE TITLE
lavaland funky roundstart atmos

### ISSUE THREAD

**Issue by NalyKalZul** [citadel-station/citadel-main#15079]
Issue reported from  Round ID: 28248 (Citadel Station)

Reporting client version: 514.1556

![Screenshot_220](https://user-images.githubusercontent.com/12812081/132114253-05413d94-14ff-48b4-9b6b-ac0b3f0031f7.png)
so this is the roundstart atmos of the lavaland, and without seva your burning up fairly fast.
even with seva suit i am barely not catching fire just yet.

**Comment by Putnam3145** [comment]
this has been fixed by #15090, #15197
