### ISSUE TITLE
Security bomb suit does not protect against cargo syndicate bombs

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#15170]
**Round ID:** 28389
**Staition time around 1 hour 43 minutes**

Quite simple really. I put on the sec bomb suit, loaned a bomb and the bomb gibbed me. Suits are supposed to protect ya against bombs or at least make sure your not gibbed. This was not the case as I was gibbed.

**Comment by buffyuwu** [comment]
Hi! I tested this on live and didn't get gibbed with the security bomb hood and security bomb suit on. Can you provide additional details or steps to reproduce this?

**Comment by lightcat** [comment]
Sadly there isn't much more detail I can give. The loaned cargo shuttle brought back a bomb the gibbed me through it. You would have to look at the logs to get more info.

**Comment by DeltaFire15** [comment]
Uhh kinda stupid but neccessary question; Were you using both a bomb suit and bomb hood?

**Comment by lightcat** [comment]
Perhaps this was just a one off issue. I will make a new issue if it occurs again
