### ISSUE TITLE
Disable All Antagonism does not work on dynamic

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#15212]
Issue reported from  Round ID: 28505 (Citadel Station)

Reporting client version: 513.1542

As stated in the title, antag rolls are still rolling despite disable all antagonsim being on.

Reproduction - have disable all antag on and start a round with dynamic, it will ignore it RNG depending

**Comment by keronshb** [comment]
This is fixed.
