### ISSUE TITLE
Cryo Console

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#15358]
Issue reported from  Round ID: 28960 (Citadel Station)

Reporting client version: 514.1569

Test Merges: #15317

When a person cryos, their belongings no longer get stored into the cryo console, nor into a box.

**Comment by LetterN** [comment]
it should drop all of their items as soon as `despawn_occupant` invokes

**Comment by TripleShades** [comment]
That's not how it was functioning before.
When a person cryoed, it would be put in a box in the cryo console, for someone with head-level access to retrieve.

Right now, it's dropping literally all their shit on the floor, which is gross and not how it was.

**Comment by shellspeed1** [comment]
just an FYI, this is likely the result of changes tg made to cryopod code. Iirc I saw mention that they had made it impossible for items to get trapped in the menu so you couldn't cryo to get rid of objectives. Something like that.

**Comment by TripleShades** [comment]
This was fixed, closing.
