### ISSUE TITLE
SSD Cryo

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#15355]
Issue reported from  Round ID: 28960 (Citadel Station)

Reporting client version: 514.1569

Test Merges: #15317
You can no longer cryo SSD people.
![image](https://user-images.githubusercontent.com/6299921/141235458-f4961ff4-c267-44c4-83f3-ea3eba906f3a.png)

**Comment by LetterN** [comment]
latest push fixes this

**Comment by TripleShades** [comment]
You still cannot put SSD people into cryo.
It doesn't even say the message now.

**Comment by TripleShades** [comment]
I believe this was fixed, closing.
