### ISSUE TITLE
AI and Z-Levels

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#15378]
Issue reported from  Round ID: 29002 (Citadel Station)

Reporting client version: 514.1569

Testmerges: #15317
The AI can no longer interact with things on another z-level.
Example: AI core is on lavaland and viewing through cams on station.
... I swear this was possible as of earlier this year, but I might have missed a pr.

Additionally, at random(?), if your core is transported to another z-level, you cannot use your shells and get repeatedly kicked out of them. Was somehow able to fix this in-round, but uncertain as to how or why. Possibly related.

**Comment by LetterN** [comment]
I dont know if this is tgui related, need someone to test it with a clean fork

**Comment by SandPoot** [comment]
As i've seen this was somewhat of always a thing? Maybe not intended but always been like this as i've seen, onstation you control everywhere, otherwise you only control where you are

**Comment by DeltaFire15** [comment]
AIs offstation can only interact with their own z-level
AIs onstation can interact with any z-level they can view.

**Comment by TripleShades** [comment]
Closing issue since I guess I might have forgotten a change at some point, or straight up mistook what I previously could do.
