### ISSUE TITLE
Cannot use minibuttons

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#15408]
Issue reported from  Round ID: 29164 (Citadel Station)

Reporting client version: 514.1568

Testmerges: #15401

Cannot use the buttons that would let you adjust suit style, untie shoes, or disable internals.
Assume this is the same for remove hardsuit helmet.

**Comment by SandPoot** [comment]
Fixed by https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15401/commits/19d3459b46abd6630fedbb918615fee229f89baa.
