### ISSUE TITLE
Trying to dump something into itself gives it a permanent progress bar.

### ISSUE THREAD

**Issue by TheEaterOfBeans** [citadel-station/citadel-main#15575]
Issue reported from  Round ID: 30104 (Citadel Station)

Reporting client version: 514.1582

### Round ID:
30104

### Testmerges:
#15569
#15565
#15539
#15231

### Reproduction:
Drag a container onto itself.

Reconnecting doesn't fix it.

**Comment by Solaris-Shade** [comment]
After testing, indications of Projectile Code PR + current Merged content is NOT the source of the error.
