### ISSUE TITLE
Gang antag datum runtimes

### ISSUE THREAD

**Issue by IHOPMommyLich** [citadel-station/citadel-main#15678]
## Round ID:

30658
## Reproduction:
Giving someone a gang antag datum causes a runtime, where it says on line 83, the index goes out of bounds. It also fails to read the bonus items correctly, giving cannot read null.bonus_items when trying to do /datum/antagonist/gang/proc/equip_gangster_in_inventory. In this specific instance, they were attempted to be given the Tunnel Snake gang specifically.

Removing the datum causes a runtime on line 93.

**Comment by keronshb** [comment]
This is fixed
