### ISSUE TITLE
Invisible Flan Monsters in Space Ruins

### ISSUE THREAD

**Issue by sevntohno** [citadel-station/citadel-main#160]
One of the space ruins had a variant of the Flan simplemob
![ss 2017-01-20 at 09 05 20](https://cloud.githubusercontent.com/assets/20675343/22152205/b213ae0c-deef-11e6-8ecb-c03f78e13f7b.jpg)
 that had no icon, only could be seen by their floating health bars with medhud. 'Flame Flans' also had no icon and presumably, would be able to attack while remaining completely hidden without a medical hud like other iconless Flans.

**Comment by Poojawa** [comment]
Fixed by #162
