### ISSUE TITLE
Box Station ERROR Connector Ports

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#16076]
Issue reported from  Round ID: 33631 (Citadel Station 13 - Main)

Reporting client version: 515.1636

Toxins maints
![image](https://github.com/Citadel-Station-13/Citadel-Station-13/assets/6299921/89c4ce84-e72c-444e-9407-2f444e034b45)
Security maints
![image](https://github.com/Citadel-Station-13/Citadel-Station-13/assets/6299921/97b8f7fc-8b4f-49d6-b411-562769403474)

Yeah I have no clue.
Unwrenching and then re-wrenching them fixed it.

**Comment by iliyaxox** [comment]
genuinely couldn't reproduce, neither on local or main. couldve been an issue with your client or an initialization fuckup 😭

**Comment by TripleShades** [comment]
I haven't seen it since that round either, so I have no idea what the fuck happened. Gonna just close this assuming it's a one-off until I can reproduce/find it happen again.
