### ISSUE TITLE
Vomit Comet Mode

### ISSUE THREAD

**Issue by LSommers** [citadel-station/citadel-main#161]
I don't know what the fuck I'm doing, but something caused, [well, this.](https://gyazo.com/91954f769cc7a9d88d10e023431d1985)

Parallax was not enabled. Upon rejoin, everything[ just vanished](https://gyazo.com/f01da8b539f5193d5e8d40693b2b96c1).

Problem persists through _multiple_ relogs, ghosting, etc. In addition, ghosting also proved that the "vanishing" of the "floating" shit is only local. Upon teleporting to a new area, the problem occurs again until a re-log, which makes everything vanish.

I don't even.

**Comment by LSommers** [comment]
[Applying Jay's "black tile" fix does NOT, in fact, fix this. Problem occurs even with parallax disabled. Please re-open.](https://gyazo.com/c99b67388386c1b1be8a2c1cad512a57)

**Comment by ghost** [comment]
Update to latest BYOND Beta.

**Comment by Poojawa** [comment]
Try locally running the Bleeding-edgy branch. And see if the problem persists.

**Comment by LSommers** [comment]
Updating BYOND solves the Vomit Comet, but induces fuzziness. No amount of tweaking of Graphics Settings seems to be able to stop the fuzz. FML.

**Comment by LSommers** [comment]
Reverting to BYOND v. 511.1362 fixes all listed issues.
Don't know why, don't know how, but goddamn am I glad it works.

**Comment by LetterJay** [comment]
Fix listed above.
