### ISSUE TITLE
Cannot save logs with goonchat port

### ISSUE THREAD

**Issue by regtaf** [citadel-station/citadel-main#1682]
Attempting to save logs will result in the entire game window freezing up, becoming unresponsive with no way to recover from the crash. Considering the theme of the server, and what usually occurs... I would assume saving logs is important for players.

**Comment by LetterJay** [comment]
Already known. Upstream issue.

**Comment by Poojawa** [comment]
You should be able to just copy/pasta the log output itself. Use that. A bit more wonky and you'll need to trim it as needed, but just save it as HTML and it'll work.
