### ISSUE TITLE
Scrub Puppy can not injest Work Boots - maybe other items too?

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#1687]
Problem Description: Could not injest Work boots. created invisible copy of work boots within trash compactor.

What did you expect to happen: Injest work boots like any normal item.

What happened instead: Boots could be injested multiple times, even though there was only one object. Object would not disappear. later, i emptied my trash compactor and found an invisible pair of work boots.

Why is this bad/What are the consequences: This could possibly apply to other items too. more testing required.

Steps to reproduce the problem: Play as a scrub puppy and attempt to injest work boots.

Server: Citadel Station (main server)

Revision: What revision was the server running? f4ee87 

Possibly related stuff: Extended late at night. ~45 players online. did not notice replecation with any other item. The boots were left outside a dorm. their owner likely went to erp. No human attempted to pick up the boots (to my knowledge), or summarily wear them. Its possible the owner of the shoes could have some bearing on this bug.

![2017-06-19_23-21-44](https://user-images.githubusercontent.com/18063157/27322658-8dbe07e6-5564-11e7-973b-89b39ace73f4.png)
![2017-06-19_23-25-17](https://user-images.githubusercontent.com/18063157/27322659-8dc40718-5564-11e7-8c28-4438588a6689.png)

**Comment by Poojawa** [comment]
Teeeechnically an upstream issue? 

`icon_state = "workboots"
	item_state = "jackboots"`

dunno.

**Comment by Poojawa** [comment]
#1805 blacklists a lot of items now, not workboots, but try not to eat everything on the station.
