### ISSUE TITLE
Crew Monitor shows Box Stations instead of Pubby

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#1698]
Dunno if this was just on my end, but the crew monitor for pubby shows box instead of pubby.

![image](https://user-images.githubusercontent.com/27295611/27348690-caa15588-55a9-11e7-9738-1a024a57b052.png)

**Comment by ghost** [comment]
Yeah, ive had this problem too. I cant remember however, if its just pubby, or any of the other maps too. additional testing required.

**Comment by Poojawa** [comment]
Has to do with the mapping subsystem. honestly it should understand what map its on and ensure it's got the right output file.

**Comment by ghost** [comment]
There's no minimap for pubby in the /tg/station codebase, that's why

**Comment by Poojawa** [comment]
Resolved in #1883
