### ISSUE TITLE
Stacking Chat Messages

### ISSUE THREAD

**Issue by gozulio** [citadel-station/citadel-main#17]
Would it be possible to make repeated event messages stack or appear to be stacked?
so that:

> Clown has hit John with spleen
> John: "Help the clown is attacking me!"
> Clown has hit John with spleen

would instead update to look like:

> john: "Help the clown is attacking me!"
> Clown has hit John with spleen (x2)

There are some anomalies (or sometimes even players) that end up flooding the chat log with red text, making it hard to actually read the log.

**Comment by Poojawa** [comment]
The problem with that is the chat buffer is just a generic, basic printer of text. When an item/mob prints a message, then that's the only instance of it ever.

Our combat logs are shit like <timestamp> (ckey)[Clown] attacked (ckey)[John] with the spleen (New Health:99)

and every single hit is printed into a billion lines near round end.

**Comment by TalkingCactus** [comment]
I really don't see this ever being added, sorry.
