### ISSUE TITLE
Skateboards + Scooters don't function.

### ISSUE THREAD

**Issue by LSommers** [citadel-station/citadel-main#172]
You can build them, but attempting to mount them just places you on them ([or does nothing](https://gyazo.com/e52e8701ed4d20ca36913b836170d136)), and moving acts as if you are not on them. Also, if you pick up skateboards, a copy may be left where you picked it up from until someone moves through that tile.

**Comment by LetterJay** [comment]
Already known by /tg/. They're working on a fix.

**Comment by Roland410** [comment]
Same with boats, so don't use those either.

**Comment by LetterJay** [comment]
fixed in #177
