### ISSUE TITLE
Dufflebags are heavier than backpacks and satchels

### ISSUE THREAD

**Issue by chesse20** [citadel-station/citadel-main#1731]
[Note]:Dufflebags severely slow you down while wearing them, while satchels and backpacks seem to have very little effect at all

**Comment by chesse20** [comment]
i tested just to see if there was any advantage to dufflebags by filling a satchel and a dufflebag full, but they both had 21 item slots each

**Comment by improvedname** [comment]
They are supposed to be hold extra stuff hence them being heavier

**Comment by lm40** [comment]
the capacity difference isn't noticeable with tiny items because they seem to be hardcapped at 21. if you try with medium items it becomes clear the dufflebag holds more so this is working as intended.

**Comment by Poojawa** [comment]
As Kenzie pointed out, it isn't a bug. the dufflebag is the mid-point between the backpack and the BoH.
