### ISSUE TITLE
Angel wing sprite still broken

### ISSUE THREAD

**Issue by Roland410** [citadel-station/citadel-main#186]
Issue still stands, only managed to test on local since I haven't been able to get a flight potion on the actual server for a bit.
On local tested it on bleeding edgy and tg patch branches with normal and clean compile too.

**Comment by Poojawa** [comment]
Broken... how?

**Comment by Roland410** [comment]
#140 This. Still won't give the sprites after transforming with a flight potion.

**Comment by Poojawa** [comment]
fixed in #189
