### ISSUE TITLE
Facehuggers might persist between rounds on the bar monkey

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#1924]
Honestly I have no idea what happened. Round ID 8683 ended with xenomorphs. Round ID 8684 was a regular secret round, but about 15 minutes in, ghosts were asked if they wanted to be a larva coming from the bar monkey. There was no xenomorph ruin (I checked) and no other way that I'm aware of for a facehugger to exist that early. The only explination I can think of is that the alien, placed on the bar monkey from the round previous, persisted like other hats persist on the bar monkey

EDIT: the next round the monkey had a hugger even though it had gibbed. Major issue.

**Comment by Poojawa** [comment]
Looking into it, this is intended behavior. :man_shrugging:
