### ISSUE TITLE
Traitor Objectives deleted on Cloning

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#1949]
**Round ID:** 8697

**Observed Subject**: Hannah Tagg
**Status**: Traitor

**Objectives**: 
1. Steal SMC sliver.
2. Kill assistant
3. Escape

**Can be reproduced**: Yes
**How to reproduce**: Die with Streal SMC sliver objective and become cloned.

_May not require the 'Steal SMC Sliver' objective. Seemed to occur with all naturally generated Traitor objectives. Probably an upstream issue?_

**Comment by silicons** [comment]
Unstrwam issue iirc
