### ISSUE TITLE
Supermatter delaminates after putting in coolant

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#1952]
First off, I don't know who thought they were cheeky when they coded it, but the gas filters under the gas chamber are set to filtered N2, the gas supplied to cool the SME.

Anyways,
I did my usual set-up. Set all pumps to max, filters to plasma, CO2 and Oxygen underneath the engine. I made the gas go through the cooling loop in space, and bypassed the cooling on the right since I thought it didn't need it. Filters were also set to max, and N2 canisters were hooked up. Before I did that, I set vents to max and siphon with everything but freon on it. As soon as I start pushing N2 through the cooling loop, the SME delaminates immediately. Emitters have never been shot, and the crystal is on fire, needing freon to cool it down.

I don't feel it's a me issue here because just about everyone I've seen has failed to set it up, and needs freon to cool it down.

**Comment by ChayseRamsay** [comment]
Not an issue. Look at the pipes and you'll see why they're filtering N2.
