### ISSUE TITLE
Recent change reverted from /tg/ merge

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#1983]
Recent merge seems to have caused conflicts or overwritten this change:

https://github.com/Citadel-Station-13/Citadel-Station-13/commit/b21556329b5fd7b97d41340e21b722dae5c42160

This goes hand-in-hand with the fact that the sprites are missing for the corresponding jumpsuits/underclothes.

**Comment by LetterJay** [comment]
This is why I've always told people to not edit the vanilla files and if they're going to add something new to add its own file with a citadel prefix in the code file name to prevent bad mirror files.

**Comment by Poojawa** [comment]
Sprites as of #2759 just need porting to the override files. 

Just up to someone to make sure everything's in the right files.
