### ISSUE TITLE
Drones unable to drop firefighting nozzle

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#1984]
Drones, when using the backpack firefighting tank are unable to drop the nozzle, even when forced to drop all items via the VV panel. They can use the device normally other than that they can't remove or drop it, because it will always register as having it in their hand.

Deleting the nozzle via admin commands just makes it invisible, if that helps at all.

**Comment by MimicFaux** [comment]
Don't you click on the backpack with the nozzle to 'put it back' If not, it's probably also affected by the other waterpacks

**Comment by Poojawa** [comment]
This is still an issue, just tested it.

**Comment by Poojawa** [comment]
Can't really do anything with it either, I dunno how to debug it. just refrain from using the tanks. I guess.
