### ISSUE TITLE
Maintenance access for rad storm not activating

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#2012]
When an event for a rad storm hits, maintenance access doesn't give emergency access. There is a message afterwards, but before if you do not have maintenance access you are just kinda screwed. That, and if people with certain types of maintenance access are also screwed since they might not always be near their department door.

In the case of maintenance access being given to most jobs, if that's the case, then department maintenance doors do not set themselves to emergency to immediately go into the tunnels.

How to test: Wait for the random trigger of radstorm on a round
Look at a maintenance door

**Comment by chesse20** [comment]
i saw that last round too

**Comment by Poojawa** [comment]
Fixed.
