### ISSUE TITLE
Wearing a clothes makes genitalia Disappear (minor bug)

### ISSUE THREAD

**Issue by chesse20** [citadel-station/citadel-main#2014]
[Note]: # wearing a cloak (possibly works with other tie slots havent tried) makes your charaters dick disappear (probably other items using the same system disappear). taking cloak off just makes it appear.
to recreate bug: wear cloak and nothing else as character with dick and see no dick. take off cloak and the dick is back.

**Comment by chesse20** [comment]
i tried this with wearing a letterman jacket and nothing else and my characters dick disappeared too

**Comment by Poojawa** [comment]
@ktccd isn't this fixed?

**Comment by ktccd** [comment]
Eh, technically not? Wearing a jacket still makes them disappear, since we can't really tell if a clothing item WOULD cover it graphically or not.
But we made a workaround with the expose/hide genitals instead.... not sure if that counts as "solving" the issue :S.

**Comment by Poojawa** [comment]
It's good enough, actually. with is needed to work with.
