### ISSUE TITLE
Stomachs/Vore Panel settings not saving

### ISSUE THREAD

**Issue by AmatsuDF** [citadel-station/citadel-main#2066]
I've been experiencing a persistent issue across two characters at this point, across multiple rounds. Notably, as the title says, my custom stomachs are not saving, nor is my allow devourable setting (usually, once in awhile it does save, only to reset the next round). I am not experienced enough to look at the code to make a guess myself as to the issue, but it seems to happen most often after I have made a custom stomach, or edit the default one in any way then hit Save.

I have asked around, but it felt like the issue was either unknown, or a solution was not available to use on my end.

**Comment by LetterJay** [comment]
@Poojawa

**Comment by Poojawa** [comment]
The only real way to "fix" this is to just reload the sav file. since I don't know how to debug those and the save system is 2009 era black magic.

**Comment by ktccd** [comment]
Wait, so when all of your vore stuff appears gone, can reloading the file fix it? Like, the stuff still exists it just didn't get loaded?

**Comment by ktccd** [comment]
I am unable to intentionally recreate this bug on my private server, but it happens occasionally on the actual server.
I.. I can't fix a bug I don't have any clue why it happens and can't recreate to find out why it happens :S.

**Comment by Poojawa** [comment]
it's a .sav file corruption that can't be otherwise fixed. :C

**Comment by ktccd** [comment]
I figured parts of this bug out. It's definately in the load/save code for the vore prefs.
I think I could fix this by learning how to mess with shit and moving the whole thing into our normal pref pages and using their load/save functions, since they don't have this issue...

**Comment by Poojawa** [comment]
The vore sav file stuff is snowflake that ties in separately. it would require a very significant amount of refractor to ensure the functionality was maintained.

Can't really fix this either, as .savs are corrupted and it'd be next to impossible to do anything but just outright delete.
