### ISSUE TITLE
Weird escape pod orientation bug. Probably upstream.

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#2081]
Round ID: 8846

Launched Escape pod during red alert, landed on Lava world with orientation different from that on the station. Resulted in thrusters, computer and suit storage all being in weird spots.

Pic included.

http://i.imgur.com/NkteXSS.png

**Comment by Poojawa** [comment]
probably not fixed, either that or actually trying to prepresent a 'crash landing'. Either way any time you're using this is a round ending edge case.
