### ISSUE TITLE
RCD Ammo at Central Command (ERT RCD Ammo) Cannot Be Loaded

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#2084]
RCD holds 160u of Matter. Ammo replenishes 160u of matter. If the RCD has so much as 1u of Matter in the reserve, it will refuse to be loaded.

100% sure this is upstream.

**Comment by Poojawa** [comment]
This is kinda not a bug unless it's supposed to take anything smaller than the 30u carts.
