### ISSUE TITLE
Admin-logs report Cargo orders, but as NULL_ENTRY instead of the actual crate names

### ISSUE THREAD

**Issue by Theoun** [citadel-station/citadel-main#21]
Self-explanatory.
"ADMIN LOG: NULL_ENTRY ordered by _[ckey]_/(_[character-name]_) has shipped."
Instead of a more logical crate name inserted.

**Comment by TalkingCactus** [comment]
Most of them seem to work, can you identify the specific crates that produce this bug?

**Comment by lm40** [comment]
Not a bug, NULL_ENTRY is the name of the syndicate equipment crate which is one of, if not the only crate to send admin logs when ordered.
