### ISSUE TITLE
Sprite gets broken after augmentation

### ISSUE THREAD

**Issue by Roland410** [citadel-station/citadel-main#214]
Not sure how to reproduce it myself, but another player reported this. After being augmented their sprite has pretty much disappeared.

Picture for reference: https://gyazo.com/bc5581138b24ed0bb1a71c8ada2df104

**Comment by Roland410** [comment]
After cloning the sprite became normal, so definitely something borked with augmentations on that, species is some cat thing.

**Comment by Poojawa** [comment]
Pertains to change_bodypart_status and limbs being set to BODYPART_ROBOTIC or w/e.

It's all in the limbs section of surgery. I don't know where to begin to fix it.

**Comment by LetterJay** [comment]
Fixed in #313
