### ISSUE TITLE
Engineering robot does not have a Plasteel Synthesizer

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#2192]
I don't know if this was removed or not but the Engineering robot does not have the mentioned synthesizer above. It could be outdated but the TG wiki mentions it https://tgstation13.org/wiki/Cyborg

Just letting you know in case  this feature was never brought over by accident or somehow glitched out.

**Comment by Poojawa** [comment]
I believe it was removed for balance reasons.
