### ISSUE TITLE
Genitals don't seem to be added when selected in character creation.

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#2263]
When selecting genitals in character creation, they do not seem to appear on the sprite, and this extends into the game when joining a round. While also in round, masturbation through the arousal function isn't possible, even though the genitals that are selected in character creation can be selected from the masturbation menu after clicking on arousal. I haven't spent a whole lot of time looking at the citadel code, so I'm not sure what could be causing this.

**Comment by ktccd** [comment]
Wait, so nobody has genitals anymore? Ingame too? O.o

**Comment by ghost** [comment]
I think I've seen other people with genitals, but in my character creation screen nothing comes up, and the same goes for in game. It's weird. I can't think of a way to manually fix it either. I've tried a bunch of different things in character creation in an attempt to, well, reset things, for lack of a better phrase, but no combination of character settings seems to fix it. I can post an image to show the issue, if that would help in any way.

**Comment by ghost** [comment]
Also I know this isn't a serious issue, though, I wasn't really sure about putting it in coderbus-discussion, for some reason. If it would fit better to talk about it there this issue can be closed.

**Comment by ghost** [comment]
Nevermind, there was a flaw in my testing. Genitals are added when joining the round and are just not visible in character creation for some reason. My testing was ghosting in then using player panel to humanize myself, which I now realize would obviously not add genitals, much in the same way being cloned does not add genitals.

This was a mistake on my part, and I apologize for causing any undue stress from this issue. I will test things more rigorously in the future before making a fuss about something.

**Comment by ktccd** [comment]
Cloning should be adding genitals, but IDK what black magic is done to make the preview panel.
I was told the preview panel makes ACTUAL mobs, not images, to display your character, so with that sillyness in mind, it might be that they use the dna changing procs to make you look like you do. I'll take a peek ^^.

EDIT: I think I found something promising.

**Comment by ktccd** [comment]
Done. We must've lost this line during a TG synch.

**Comment by ghost** [comment]
Okay, thank you for looking into it and fixing it.

**Comment by ktccd** [comment]
Wasn't hard, I solved this bug once before already, so I checked to see if the same place had been messed up, and also fixed changelings while I was doing it anyway ^^.
