### ISSUE TITLE
Floor tile icon issue.

### ISSUE THREAD

**Issue by ganglyalexander** [citadel-station/citadel-main#23]
![dreamseeker_2016-08-23_18-59-00](https://cloud.githubusercontent.com/assets/20500377/17913952/bf5a1e0e-6963-11e6-830e-5320d9ab1562.png)

sooo... Here is what happened. A fire broke out and damaged the floor tiles. Before I removed them they were completely black, I removed them and exposed the Plating underneath but when I tried to place the normal floor tiles they seem to just come out a error. If I attempt to crowbar them I just expose the Plating again and get back a floor tile, placing the floor tile again just gives me a error icon on the floor...

**Comment by TalkingCactus** [comment]
This is the default icon_state for floors/plating. It defaults to this when the icon state is either null or does not exist. I'll look into it for my current PR. #14

**Comment by TalkingCactus** [comment]
All fixed, thanks for reporting it in such detail.
