### ISSUE TITLE
Drone Lighting Bug

### ISSUE THREAD

**Issue by Y0rmungandr** [citadel-station/citadel-main#2312]
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Round ID: 9054

Admin spawned a few drones, I took one of them to help set up the engine. I tried talking with a drone buddy, but the speech was bugged, so I tried reconnecting.

This image is the result:

![a](https://user-images.githubusercontent.com/30852509/29103730-353a2d32-7c76-11e7-932a-3f74160190b5.PNG)

According to Game Admin Ragolution this should only happen to MMI's. I tried reconnecting again, as well as exiting the game and rejoining, but it did not go away.

Update: The lighting was fixed when I ghosted out of the drone. 

Update 2: Now able to see perfectly fine as MMI.

**Comment by LetterJay** [comment]
This is a known upstream bug.
