### ISSUE TITLE
Sprite issue - Horse-taur

### ISSUE THREAD

**Issue by ktccd** [citadel-station/citadel-main#2328]
Horse taurs are drawn as if in half-profile, showing BOTH the further and the closer legs next to one another.
The artstyle in this game displays all characters in full profile, which should only show the closest legs.

The result of this is that they look like they are standing in profile mostly, but their legs are angled towards the player's screen somehow.

(Also this will make horse-taurs look weird if they want the taur-genitals I'm adding.)

**Comment by Poojawa** [comment]
most of the taur bodies are Narky-coder sprites. the horse half was one of the first, followed by the fox, cat, and dog ones.

They're all awful.

**Comment by ktccd** [comment]
Well, my spriting skills aren't *quite* up to snuff. Making dicks was easy by comparison ^^.

Good to know why the quality varies so much though.
