### ISSUE TITLE
Missing/Invalid Sand Sprite

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#240]
![image](http://image.prntscr.com/image/4767e427f69f49c191a4af89fa419978.png)
typepath is `/turf/open/floor/plating/beach/sand`, found in the bio-dome beach in lavaland. Some of the turfs seem to be fine, most are pitch-black however.

**Comment by LetterJay** [comment]
Is anyone else having this issue?

**Comment by TalkingCactus** [comment]
I asked the ghosts in the current around and they were seeing the same thing.
