### ISSUE TITLE
Revenants cannot purchase Defile starting out

### ISSUE THREAD

**Issue by roushguy** [citadel-station/citadel-main#242]
Exactly what it says on the tin. Despite starting with 75E, revenants cannot purchase the 75E unlock for Defile without absorbing a soul.

**Comment by ktccd** [comment]
Isn't this an intended effect? Your essence is ALSO your hitpoints. Using every hitpoint to buy something would kill you, so you can't buy it?

**Comment by Roland410** [comment]
You still should be able to buy your basic ability.

**Comment by ktccd** [comment]
I would argue it isn't a basic ability. Base kit is being invisible/intangible, talking in people's minds and eating souls. Otherwise defile wouldn't be bought at all and would already be a basic power....

**Comment by Roland410** [comment]
True about that, but they only have this power if I'm not mistaken to pick up tiles and such remove holy water and salt.

**Comment by ktccd** [comment]
Defile also busts windows, opens containers and such also, I think? Which is definitely a useful weapon.

**Comment by Roland410** [comment]
Indeed it is, revenants should only be spawned on high-death rounds where it shouldn't matter THAT much.

**Comment by ktccd** [comment]
Have to disagree again. Reasons are simple:
On a high death round, all you need to get defile is to find ANY dead corpse for even 1E to buy defile, this is very easy to accomplish. So no, wouldn't matter that much. *almost* wouldn't matter at all, except I think it makes powers cheap (cost to use powers seem to scale based on powers bought). So again, I see no reason why it needs to be a starting power, revenants are strong enough already.
On a non-high death round, getting a free defile would be a bit strong and would basically be a buff that says "admins don't spawn this" on those rounds, wouldn't it? Seems boring.

**Comment by LetterJay** [comment]
Revenants only have 75 health. This isn't a bug, it's a balance issue. The only real resolutions would be...

A) Reduce to cost of Defile
B) Increase the health of revs
C) Do nothing at all

**Comment by Roland410** [comment]
Choice A would probably be the best even though revenants have been REALLY rare lately.

**Comment by ktccd** [comment]
That's an opinion. Rarity has nothing to do with balance... Personally I think C is the best, since revenants are strong as they are. There's a reason people just call them "griefghosts" on TG....

**Comment by katnep** [comment]
i believe we should go with A because a revenant that spawns midround has often been neutered by lack of death and never got any powers, and to be fair it doesn't actually effect the balance of play to let them break windows slower than they can be fixed or rust some walls

**Comment by ktccd** [comment]
wait, midround and LACK of bodies? That's usually the opposite.... Early ones might lack bodies due to being in the beginning.... mid-round you usually have some suicides and some deaths from antags...

**Comment by Roland410** [comment]
They are probably called griefghosts because they can't properly counter them. I've got cucked as a revenant when people know what to do instead of just going "Aaaaaah ghost". Holy water AND salt both stop revenants, which they can only neutralize with defile which takes up the tiles, their shock ability can be removed by breaking or taking out the bulbs from the light source, the virus ability is unless it was changed weaker than the flu and VERY obvious. Revenants are annoying but not really a danger in any situation.

**Comment by Roland410** [comment]
Also don't forget that revenants can only get bodies which are left in the open unless they use defile.

**Comment by katnep** [comment]
again a revenant is more likely to spawn on an extended round due to the general shortness of a secret round, and even on secret bodies are morgued where you can't get them, additionally its also a weak gameplay choice if it revolves around doing nothing

**Comment by ktccd** [comment]
they're a side-antag though. they're not supposed to be even close to a traitor or changeling. The main trick I find works is to abuse that antags like having revenants on their side.
A revenant on extended is going to get wrecked, most likely, due to the crew having nothing better to do than focus down a mere side-antag role.

**Comment by Roland410** [comment]
Especially considering that revenants were supposed to only exist on secret (not literally coded to be so but designed to be) and you usually have to absorb around 450-500 essence which means 5 people who LITERALLY died on you.

**Comment by ktccd** [comment]
I play side-antags a lot on TG, like almost every round I end up traitor. I never have much trouble getting 500-600 essence. And that's with chaplains blessing things with water-tanks full of water and shit hunting me down.

EDIT: I legitimately think this is just a player issue, not a code issue. As cold as it sounds, revenants play different than most roles and you gotta get good at it :S.

**Comment by katnep** [comment]
We aren't TG we have a lower mortality rate due to the playstyle of the playerbase, we can't base our balance based on the actions of other servers

**Comment by Roland410** [comment]
Still, as you just said, that's on TG, and as Sota just said we have a LOT less death and pop usually.

**Comment by ktccd** [comment]
True. Pop isn't as much of an issue, we come close, but we don't allow antags as much murder-freedom here. So that is worth taking into consideration. but why not just lower the goal Essence needed here then?

**Comment by Roland410** [comment]
That'd be another PR, the fact that if you can't get a corpse like instantly at spawn you lose a vital ability is the focus here.

**Comment by katnep** [comment]
becuase the issue isn't they aren't getting enough, its that they can't get ANY because they don't have access to their tool set
its like if we said changelings had to absorb 5 people with no powers before they can unlock any powers, an unnessecary gimp that has no reason to exist

**Comment by ktccd** [comment]
Well, I haven't had chance to try them on this server, so I'll have to defer to you on this. It just feels like buffs on this server to antags might be bad :S. Haven't seen the most robust avarage player.

**Comment by Roland410** [comment]
If you look at it by what it can do and what it can't, what makes it good and what counters it to the ground, you will understand.
You probably haven't seen the crew running around with a spray bottle full of salt on TG.

**Comment by ktccd** [comment]
oh, I do see some. It's just not normal for the entire crew to have the time, as real antags take the main focus ^^.

**Comment by katnep** [comment]
again thats an all secret all the time deal, this is a server that can have up to 5 hours round, the crew would practically jump at the idea of something to do
