### ISSUE TITLE
Shark tail is still gray no matter what the body color is

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#2422]
https://puu.sh/xdwMB/4d703704b3.png

https://puu.sh/xdwO9/d43bb01751.png

https://puu.sh/xdx1h/e3a0a5a529.png

Making a different colored shark color other than the usual gray, the tail will not follow the same color pattern like other ears/tails. Primary, secondary, and tertiary colors (if they matter) do not work.

**Comment by TalkingCactus** [comment]
Fixed
