### ISSUE TITLE
Night vision make you see space past walls

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#2429]
Without night vision
![image](https://user-images.githubusercontent.com/27295611/29488941-f82884b4-84c9-11e7-9639-e678f4573b74.png)

With night vision
![image](https://user-images.githubusercontent.com/27295611/29488948-0a52c3b6-84ca-11e7-9716-6bf8bb691ba2.png)

I can't imagine it's just the night vision mediHUD, and I don't think it's gamebreaking or anything, but it's just a little weird.

**Comment by ktccd** [comment]
This is an upstream thing, and I'm not sure why it happens.
It might be intentional? O.o

**Comment by ktccd** [comment]
This is the issue they tracked for it:
https://github.com/tgstation/tgstation/issues/29521

**Comment by Poojawa** [comment]
Honestly annoying, but it's very much something we need TG to fix
