### ISSUE TITLE
Hair shows up through hardsuit helmets + capes/cloaks show up through naga tails

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#2431]
Kind of self explanatory
example for the hardsuit:
![](https://i.gyazo.com/ccb4d6c34889963cddff737c04d60db4.gif)

example for the cape:
![](https://i.gyazo.com/d04e6ae643afd1b9c155a34ffea5bbec.gif)

**Comment by TalkingCactus** [comment]
#2443
