### ISSUE TITLE
ID: 9193 CWC Not being able to convert.

### ISSUE THREAD

**Issue by Tekoro** [citadel-station/citadel-main#2459]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Sigils of submission aren't converting non-culties. It gives them the "_You feel something invading your mind..._" but nothing really happens. However we noticed that with a mania motor it is possible to convert, not really sure, plus you need some converts to access the mania motor which means you won't get it if you can't convert via sigil of submission.

**Comment by Poojawa** [comment]
Not an issue anymore.
