### ISSUE TITLE
Engi-Borg cannot speak on Engineering Comms

### ISSUE THREAD

**Issue by Penguaro** [citadel-station/citadel-main#266]
Problem Description: Engi-Borg cannot talk on Engineering Channel.
What did you expect to happen: Typing Say ":e Hello Engineering" Should say Hello Engineering on the Engineering Channel.
What happened instead: The text goes to the Common Channel instead
Why is this bad/What are the consequences: It makes it challenging to coordinate with other engineers.
Steps to reproduce the problem: Become a cyborg, select Engineering. Once complete try to :e to talk to engineering.
Revision: What revision was the server running? Server revision compiled on: 2017-03-05
f0ad0ac08b79357a42b7a52197d375f836716ae3 
Current Infomational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 12 of 21 roundtypes
Allow Midround Antagonists: 7 of 21 roundtypes

**Comment by TalkingCactus** [comment]
Cyborgs don't get their department encryption keys. They need to be installed by a human, manually.

**Comment by Penguaro** [comment]
I see what you mean. I was used to playing borg on a different server that had some custom borg stuff. Didn't realize it wasn't the norm.
