### ISSUE TITLE
Attempting to use some admin commands returns "clicked an href with no authorization key!"

### ISSUE THREAD

**Issue by Raeschen** [citadel-station/citadel-main#2718]
ADMIN LOG: Raeschen/(Raeschen Orthoss) clicked an href with no authorization key!

this happens, as an example, when you use;

admin > investigate > notes, memos, watchlists - searching for a ckey
admin > game panel > create object > SPAWN.

Dunno if upstream or local.

**Comment by Raeschen** [comment]
made an upstream issue

https://github.com/tgstation/tgstation/issues/30662

**Comment by MrsTonedOne** [comment]
These will be aplentiful for the next few weeks while we transition to this csrf proof system.

Server ops can enable admin href debug mode in the config to make these errors not block the link while we patch things up.

**Comment by LetterJay** [comment]
Thanks for the info. Marking this as upstream since I toggled debug on already, so it should be fixed for the most part.
