### ISSUE TITLE
Chem fridge doesn't display or allow you to take out pills you put in

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#2745]
![image](https://user-images.githubusercontent.com/27295611/30397649-6aac8d3e-9882-11e7-8bd9-c2b508d4e828.png)

The first four things were there round start, the next four blank spaces should have been pills.
The pill bottles I later put them in showed up and were allowed to be dispensed, 
Taking the machine apart spat the pills back out along with the matter bin and board needed to put it back together.

**Comment by Poojawa** [comment]
This is an issue with the initializing proc, sooo

**Comment by Poojawa** [comment]
#2758 fixes this
