### ISSUE TITLE
Particle Accelerator Rifle Bug

### ISSUE THREAD

**Issue by iknowdude00** [citadel-station/citadel-main#2794]
Round ID: 9422
I was firing the rifle in the testing range using the standard  and all shots failed, no aiming laser thing came up while I was preparing to fire or when I did fire. When I say fire I meant to say that the gun played the sound and the muzzle flash but did not fire a projectile. I tried using the rifle in other places on the station and the problem was consistent. At least until a few mins passed and all the locations the rifle had been fired in previously suddenly exploded whenever someone passes within the shots expected direction, effectively working as a mine field. I don't really know how else to explain what happened but I hope you guys might be able to have a better insight.

**Comment by Poojawa** [comment]
Best to check with TG's issue tracker, but I'm pretty sure it's either that or a timer issue locally

**Comment by Poojawa** [comment]
Being that this is a known issue, we're really just waiting on an upstream fix for it. gg
