### ISSUE TITLE
Certain overlays aren't displaying correctly

### ISSUE THREAD

**Issue by LetterJay** [citadel-station/citadel-main#288]
This is from #286 

A few overlays aren't applying directly or are facing the wrong direction.

![GitHub Logo](https://cdn.discordapp.com/attachments/167060301013843968/292133300892467201/Bug..PNG))

**Comment by TalkingCactus** [comment]
Is this still an issue?

**Comment by LetterJay** [comment]
Nah. This was fixed with #295 with a small port. The preview icons still aren't displaying right, but from what I understand this issue itself can be closed. The getPreview is a bug on its own.
