### ISSUE TITLE
Examining breaks when a ` is present in your flavortext

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#2880]
Basically, if a ` (backtick, NOT an apostrophe) is present in the flavortext, your character will be entirely unable to be examined

**Comment by Poojawa** [comment]
Since they touched it last, and moved it into features. 

Probably just needs a sanitize check rewrite. it was never supposed to be a DNA text feature.

**Comment by ktccd** [comment]
Yeah, I'll get to work on this tomorrow (Don't have more time right now before uni). Sanitizing weird character does seem like a good idea >_<.
