### ISSUE TITLE
Ears don't show up

### ISSUE THREAD

**Issue by pantherpusher** [citadel-station/citadel-main#2946]
The "Cat,Big" ears don't actually show up on your sprite when you pick them both ingame and in the preview.

**Comment by Poojawa** [comment]
I probably fucked up when I was digging around in the file

**Comment by cebutris** [comment]
Wolf ears also don't work, at least on humans!

**Comment by pantherpusher** [comment]
Any progress?

**Comment by Michiyamenotehifunana** [comment]
Blammo, #3567 should fix this, along with Wolf ears.
