### ISSUE TITLE
Onehuman is useless on Crewsimov.

### ISSUE THREAD

**Issue by Raeschen** [citadel-station/citadel-main#2980]
The "Onehuman" card needs to be changed to "Onecrew" because otherwise it has pretty much no effect.

**Comment by WewLads** [comment]
I have a ready to go file that changes OneHuman to OneCrew. I just need someone to accept or deny my butts request because I'm unrobust and don't know how to make the pulls separate.

**Comment by WewLads** [comment]
Nevermind, submitted it as a seperate fork with the help of the good people on discord.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/3172
