### ISSUE TITLE
Fingerprints pass through gloves

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3025]
Round ID -9691

Gloves that are are not finger less leave prints at random chances. Example after a while of using Insulated engineer gloves the fingerprints will sometimes latch onto something like an emag or locker.

**Comment by LetterJay** [comment]
Need more confirmation on this.

**Comment by Kevak** [comment]
Codewise upstream some gloves (notably latex/nitrile/budget) have a chance to leave prints. I consider it silly. However I assume it was done for balancing reasons upstream. It's easy enough to change the chance downstream here.
