### ISSUE TITLE
Mesons bug for cyborgs

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3070]
9638

Borg meson glasses are glitched. They refuse to turn off properly. Just try to use them and you'll see what I mean.

Basically every time I put them back into my inventory they are stuck on the mesons mode. When I take them out and click on them light is not restored but space can't be seen.

**Comment by LetterJay** [comment]
Need more confirmation if this is still an issue.

**Comment by lightcat** [comment]
I will report back later if its an issue.

**Comment by lightcat** [comment]
Fixed, close issue.
