### ISSUE TITLE
Players have partially invisible playermodels/missing parts.

### ISSUE THREAD

**Issue by Raeschen** [citadel-station/citadel-main#3080]
round id of notice: 9648

looks like this https://i.imgur.com/Al5DJ52.png

species: human

**Comment by Roland410** [comment]
Does clearing the cache not help at all?
Last time this happened, it was serverside though, but as I can see not all players suffer from this.
It would also help to know all modifications the character has. Anything from their tail, genitals etc.
Edit: I can see their sprites missing too, so not a clientside issue probably, unless some assets corrupted.

**Comment by Raeschen** [comment]
It's def serverside, everyone sees the same thing.

**Comment by ghost** [comment]
![t7dnl5c](https://user-images.githubusercontent.com/1821504/31082365-b9e89b66-a75c-11e7-8593-933fbbc73e38.png)
Lizard. Digi legs, light belly, among others. All the characters in my saves have invisible parts, including new ones I attempt to make. Genitalia seems to be one of the only constants that's broken.

**Comment by TalkingCactus** [comment]
looks like the physical bodyparts are not being rendered or don't exist. Accessories appear fine.

**Comment by Roland410** [comment]
We managed to narrow it down a bit. Genitals are not causing it to break for sure.

**Comment by Poojawa** [comment]
Long since fixed.

**Comment by Strazyplus** [comment]
> Long since fixed.

Incorrect. 
https://i.vgy.me/3Foi7S.gif

**Comment by Poojawa** [comment]
you necromance a thread over two years old...?

it's also a byond cache issue, not an assets issue.
