### ISSUE TITLE
Enchiladas (and possibly other things, butter???) aren't available on the crafting menu.

### ISSUE THREAD

**Issue by AtticusTaylor** [citadel-station/citadel-main#3119]
Issue reported from Round ID: 9678 (Citadel Station 13)

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

So I know enchiladas are in the game. I've seen them before, they're listed on the wiki as craftable (though, TG wiki, so if they were removed, all I have to say is "Why?") Yet they don't show up under ANY of the food menus. Infact, the entire "Exoctic" menu is just gone fully, but I can see the different things under the "Misc." tab. But not Enchiladas. So, uh. Yeah.

**Comment by Poojawa** [comment]
They're under the 'Meat' category, not exotic/misc.
