### ISSUE TITLE
Underwear preferences don't save

### ISSUE THREAD

**Issue by Roland410** [citadel-station/citadel-main#3182]
As title says, saving your preferences saves everything, except that.
Picture if not clear for someone: https://prntscr.com/gu3rto

**Comment by Poojawa** [comment]
Still needs to be fixed/overhauled/whatever you were going to do with it.

**Comment by TalkingCactus** [comment]
wasn't doing anything with it, just looks awful without proper laying

**Comment by Roland410** [comment]
Unless I'm mistaken, this is still a problem.

**Comment by Poojawa** [comment]
A casualty of time, but doesn't have any plans to be changed at this point.
