### ISSUE TITLE
Freshly built Drying Rack doesn't work due to power code

### ISSUE THREAD

**Issue by WewLads** [citadel-station/citadel-main#3184]
Freshly built drying racks don't have any power, despite them being near an area with power. This can be solved by unwrenching the drying rack and rewrenching it again but this isn't something that's obvious to players unless they know this information beforehand.

I would try to fix it myself but I have no clue how the power system works and I think this issue extendeds the drying rack. Most smartfridges have weird power bugs that can either be solved by the above, or worse rebuilding the machine together.

https://github.com/Citadel-Station-13/Citadel-Station-13/blob/ceff0861285420e53abadce94d2265fcabf1db2f/code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

If anyone wants to take a look at the code.

**Comment by Roland410** [comment]
Used a drying rack on Meta yesterday that I built, had no issues.

**Comment by LetterJay** [comment]
Assuming this to be fixed unless otherwise commented.
