### ISSUE TITLE
Odd bug with undershirts and alt-clicking jumpsuits.

### ISSUE THREAD

**Issue by Axolotl123** [citadel-station/citadel-main#3196]
Issue reported from Round ID: 9722 (Citadel Station 13)

[Directions]: Be wearing a jumpsuit that can be toggled down via alt-clicking it. Proceed to go to the dresser in dorms and changing your undershirt to anything. After a bit of moving around, your character's genitals will show through the underwear.

**Comment by Poojawa** [comment]
Likely fixed, or just so edge case it isn't an issue.
