### ISSUE TITLE
Surgery issues

### ISSUE THREAD

**Issue by Mistdrgn** [citadel-station/citadel-main#3198]
Issue reported from Round ID: 9724 (Citadel Station 13)

[Directions]: # round ID: 9724
issues: Surgery can not remove any organs or implants, it goes through the motions but does not actually remove anything and ends the surgery there, also any implants added do not get removed from the inventory so it is unclear if the surgery failed or succeeded, amputation and limb replacement still seem to work.

**Comment by Roland410** [comment]
Eye surgery also does not work unless it was removed, which I'm not aware of.

**Comment by Kevak** [comment]
That's a bug of the organ manip revamp. Lemme fix that.

**Comment by Kevak** [comment]
Fixed. Rolls into test merge whenevs.
