### ISSUE TITLE
Mice/Legion heads (not megafauna) are unnecessarily odd to damage

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#3207]
Observed an engineer around round ID 9727 hit mice with a wrench and crowbar multiple times, and they didn't die, but fists seemed to work.

Round 9728 rolled around and I decided to try mining with the crusher again, came across a legion and went to crush it as per usual, and the crusher just didn't seem to do any damage to the small heads.

![](https://i.gyazo.com/adfe414dda776a28f674b5357e1c5a7d.png)

No idea what could be causing it, but it appears to just be things with a low amount of health.

**Comment by Kevak** [comment]
Honestly might be an upstream issue. I haven't touched anything relating to how simple_animals take damage.

**Comment by Kevak** [comment]
Found bug and fixed. Rolling into the testmerge whenever Jay gets to it.

**Comment by LetterJay** [comment]
Issue from a previous testmerged PR.
