### ISSUE TITLE
CE message key and actual decryption key are not always the same.

### ISSUE THREAD

**Issue by Raeschen** [citadel-station/citadel-main#3224]
ROUND ID: 9746

No other fingerprints other than mine and the CE trying to access it were on the message console, and no fingerprints at all were on the messaging server, but the passwords differed.

It could possibly be because someone deconned and reconned the messaging server but i feel like this is unlikely

Map at the time was meta - ahelping person about this said he's only seen it happen on meta.

https://i.imgur.com/nQoCu9D.png

**Comment by Roland410** [comment]
I think if you just examine the paper, it doesn't leave a fingerprint, but it may have been a comms agent modifying it, was that not the case?

**Comment by cebutris** [comment]
Sounds to me like a comms agent fucked with it, really

**Comment by Poojawa** [comment]
Don't think this is an issue still.
