### ISSUE TITLE
Space Exploration RNG failure

### ISSUE THREAD

**Issue by Makitotop** [citadel-station/citadel-main#3234]
ID = Makitotop
Character at the time = Irrelevant but Chloe S. Gibbin [Shaft Miner]
I tried to space explore with my GPS as miner in hardsuit with jetpack upgrade but North West South and East all looped back to the opposite end and I tried many times and never got to another z level, ahelped and admin said to report it so reporting.
Also it'd be more fun if you weren't RNG'd to random Z-Levels and could just explore randomized ones at roundstart that don't change placement via rng. [not relevant but meh]

**Comment by Kevak** [comment]
You shouldn’t be getting rng’d to random zlevels. Space is supposed to be a navigatable multitorus. Will test.

**Comment by LetterJay** [comment]
Last I remember going off of a z-level did put you at a random one.

**Comment by Kevak** [comment]
That's old zlevels. TG's had consistent multitorus for over six months now.

**Comment by LetterJay** [comment]
This has been fixed.
