### ISSUE TITLE
Ore redemption machine slightly broken

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3355]
The machine now accepts non ore items like metal sheets and glass sheets for some reason and probably everything else a autolathe does. This is a problem because it eats bag of holdings and well, a lot of ores gone.

**Comment by lightcat** [comment]
Investigating this issue again later to see if its fixed.

**Comment by lightcat** [comment]
Still not fixed

**Comment by Poojawa** [comment]
Fixed at this point.
