### ISSUE TITLE
All-In-One Grinders Unable to Process Botany Plants

### ISSUE THREAD

**Issue by Knouli** [citadel-station/citadel-main#3397]
This is my first bug report, I'll attempt to be as specific as I can, please bear with me.
**Round ID:** 9850
**Server Revision:** 2d2adf
**Severity:** Low
**Impact:** Hits botany pretty bad, inability to extract grown chems means a complete reliance on chemistry for mutagen, and a complete shut out of the ability to isolate chemicals beyond growing specific plants for each chem - reduces application variation to consumption of the grown plant.
**Issue Summary:** All-In-One Grinders are unable to grind (as per what was normal prior to error) nor juice plants grown in botany. 
**Expected Result:** Normal behavior is witnessed as deletion of the plants loaded into the grinder (up the the unit amount of chems the loaded beaker can hold) while depositing the related chemicals within the loaded beaker in liquid form.
**Issue Scale:** Appears to effect all plants and all grinders. Grinders in both botany and chemistry of Boxstation were sampled using Glowshrooms, as well as Plumphelms to no avail. 
**Replication:**
1. Grow any grinder friendly plant (In this case, Glowshrooms and Plumphelms were tested for their previously recognized ability to be ground)
2. Harvest grown plants, depositing within a grinder in any quantity
3. Attempt to grind / juice
4. After the wait period, the plant is left intact while the loaded beaker remains empty

*Note: Attempting to unload and reload plants, and removing and replacing the beaker seems to have no influence on the issue.

**Comment by Knouli** [comment]
This error is witnessed to continue into the following round, Round ID: 9851. A MetaStation shift.
Tests were conducted following the replication steps and include, specifically, white-beets, watermelons, limes, bananas, 
All sample plants were testing in single, and multiple quantities, and were attempted to grind, and juice utilizing botony's All-In-One Grinder.

It appears, however, the 'juice' function of grinders, when filled with 'juice able' plants resemble traditional behavior. In this case limes, and bananas were successfully juiced. 
This modifies the original error, to include explicitly the grind function of All-In-One Grinders; where as the juice function works appropriately for juice-able plants, but all plants remain ungrindable as a base case.

This error all appears to not influence 'special case' grinding such as grinding wheat into flour, or tomatoes into ketchup.

**Comment by LetterJay** [comment]
Is this only an issue with plants or everything else?

**Comment by Knouli** [comment]
As of Round ID 9868 All-In-One Grinders are able to grind solid plasma, silver, gold, and metal were able to be ground into their respective liquid equivalents.  However, when grinding was tested with a blood-tomato the grinder was unable to process the plant into the expected output of blood, vitamin, and nutriment. However, following the pattern I discovered in my previous comment, the blood-tomato was able to be juiced into tomato juice. Leading me to conclude the error influences plants only, whilst using the grind function for non-unique outcomes where the output is different from the chemicals stored (such as grinding wheat into flour).
