### ISSUE TITLE
Spiderlings don't spawn for changlings

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3465]
This has been tested a few days ago so Its not exactly certain if the issue still exists but spiderlings don't appear when changlings attempts to spawn them. This is a waste of a skill point while broken.

**Comment by cebutris** [comment]
Definitley an issue. Not sure if it's present upstream

**Comment by Poojawa** [comment]
Seems to have probably been fixed at this point, since no issues upstream
