### ISSUE TITLE
Pin removal is not working

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3640]
Its in the construction menu. When this item is crafted the pins in guns are not removed. Simple as that.

**Comment by lightcat** [comment]
Updating issue, can't test theory (lack of gun access) but this is what I've experienced.

So you go ahead and remove the firing pin but it doesn't give the pin back and it doesn't prevent the weapon from being fired but it  accepts new pins so if I wanted to remove a mindshield pin I'd do the recipe then insert a new one.

**Comment by deathride58** [comment]
Yep. Firing pins not being returned when using the crafting item to take em out is intentional. Pins are destroyed upon removal for the sake of balance.

**Comment by Poojawa** [comment]
Working as intended.
