### ISSUE TITLE
Possible GatFruit speed error?

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#3646]
I'll be honest I'm not entirely sure how plant growth speed is calculated but if each and every plant doesn't have their own production speed its glitched. I made production speed of the Gatfruit to 1 and its taking over 20 minutes to barely sprout.

**Comment by imsxz** [comment]
Plants have a maturation speed which cannot be changed, gatfruits is 40 for hopefully obvious balance reasons. Once it matures, it'll start producing them every minute or so with 1 production speed.
