### ISSUE TITLE
Cybernetic Heart Sprite Changing when Bitten

### ISSUE THREAD

**Issue by DenialDuckOfService** [citadel-station/citadel-main#3999]
[Directions]: # 10354 Round ID, I was a simple golem messing with RnD on our ship and mourning the fact i need an anomaly core to finish my phazon, Printing cybernetic versions of organs to see what they do better, Printed out the cybernetic heart, decided to see if i can bite it for giggles, bit it and then its sprite changes from the cybernetic version to the human organic version. The directions are above but if you want it more easily readable: Step 1. Acquire working core R&D Console and protolathe. Step 2. Print out a basic cybernetic heart. Step 3. Bite into it you robotic cannibal. Step 4. Have a party as you realise it does work, Or you can try spawning it in with your adminly powers and biting it..that would probably work too.

**Comment by Poojawa** [comment]
More of a 'no-one has cyberheart sprites' for this, but it's kinda a small thing.

Tbh, only in spacemans would you cram a synthetic heart into your face.
