### ISSUE TITLE
Ears and Tails on humans do not save properly

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#4092]
Possibly related to #3182, ears and tails on humans do not save when set, leaving you as a base human the next round unless you manually reset it every single round. This is an issue because catgirls need to be catgirls.

**Comment by Poojawa** [comment]
Not related at all, it's more the continuing racism of /tg/ that leaks through.

**Comment by deathride58** [comment]
Probably just sanitation fucking up somewhere down the line

**Comment by Michiyamenotehifunana** [comment]
This seems to be related to #3182, as underwear also does not save.
