### ISSUE TITLE
PDA's aren't included in pictures taken with cameras

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#413]
Taken with camera:
![image](https://cloud.githubusercontent.com/assets/27295611/25066360/640ca4f8-21d8-11e7-8ef1-ebf620c29a4c.png)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/27295611/25066361/6fed05f6-21d8-11e7-87fa-12b43e338f10.png)

Tried focusing the picture on a M.U.L.E and got the same results.
![image](https://cloud.githubusercontent.com/assets/27295611/25066371/b9be2962-21d8-11e7-8a57-1bc3249c83f0.png)
![image](https://cloud.githubusercontent.com/assets/27295611/25066374/bda724de-21d8-11e7-8a33-09e1579cf45a.png)

The light of the PDA shows up, but the PDA itself doesn't. Tried with both the normal camera and detective's camera, and got the same results.

**Comment by iamafsh** [comment]
cameras are buggy as fuck
it is a truth in life

**Comment by Poojawa** [comment]
No idea how to actually fix this, probably throw it up onto TG's issues.
