### ISSUE TITLE
Box Station mapping error: Maint Bar Gambling Room wooden table is not the right kind of wooden table

### ISSUE THREAD

**Issue by Slayerhero90** [citadel-station/citadel-main#4352]
ROUND ID: 10739, but it happened on the day before, too.

The wooden counter situated between the vendors in the maint bar's gambling room is not made of the kind of wooden table that players build, but of a special type of table that launches players a tile north if they try to climb on it, with a message of "Please do not climb on the bar." and cannot be deconstructed.
I first noticed this as a revenant, when I appeared to bight some players of a dice dare game, and while visible but not paralyzed, I moved onto said table and got launched north into the vending machine. On the listed round, I was able to confirm to the best of my ability that this is a persistent issue and also discover that these can't be unbuilt.

**Comment by deathride58** [comment]
fuccin
reeeEEEE
