### ISSUE TITLE
MediHound Does not come with any Moduels

### ISSUE THREAD

**Issue by Czyrek** [citadel-station/citadel-main#4358]
Round number # 10741

Server revision compiled on: 2017-12-12

a62831

Server tools version: /tg/station 13 Server Service v3.1.6.1

Server tools API version: 3.1.0.2

Current Informational Settings:

Protect Authority Roles From Traitor: 1

Protect Assistant Role From Traitor: 0

Enforce Human Authority: 0

Allow Latejoin Antagonists: 1

Enforce Continuous Rounds: 11 of 18 roundtypes

Allow Midround Antagonists: 8 of 18 roundtypes

ISSUE: When borged as a posibrain, I changed to be a Mediborg. There were no modules available for me (the button I normally choose to select them was missing)

**Comment by LetterJay** [comment]
Sprite is missing for the HUD. Easy fix, I'll get to it when I can, or someone else. Whichever comes first.

**Comment by deathride58** [comment]
Already fixed
