### ISSUE TITLE
Sentience potions are not created

### ISSUE THREAD

**Issue by ktccd** [citadel-station/citadel-main#442]
How to recreate:
Make light-pink slime core.
Inject with plasma.
The core will disappear, but not leave a potion behind.

Tested live on server 2017/04/17, but no idea how to find out server revision.

**Comment by ktccd** [comment]
Gold slime cores also don't seem to work. Maybe this is related? They just despawn with nothing happening when you inject them with blood.
Both these things kind of result in xenobio being really boring :S.

**Comment by TalkingCactus** [comment]
Need someone to confirm this is only an issue with us and not /tg/

**Comment by iamafsh** [comment]
https://github.com/tgstation/tgstation/issues/26392
main tg has it too

**Comment by ktccd** [comment]
Holy heck, I checked TG days ago for this bug in their issues, but there wasn't any issue filed so I assumed this was only on our end...

**Comment by ktccd** [comment]
Does that mean we got more xenobio players than TG?
Or that most people never file issue reports?

**Comment by XDTM** [comment]
Thanks for the report, PR with a fix (along with gold cores) has been created.

**Comment by Kromgar** [comment]
@ktccd probably more xenobio players very few people have the patience to breed slimes for 20 minutes get a shuttle call and all their work goes to shit
