### ISSUE TITLE
Headpatting makes everyone including tailless wag their tail

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#445]
How to recreate:

Swich to help intent, target head
Click any species or person.
No tail is preferred. Headpatted humans with no animal ears or tails make the most light of this issue.

Some species lose their tails when wagging their tail, namely Shark and Datashark. Will go home and test to see if any more species that do not have tail animations simply just lose their tail.

**Comment by harmonyn** [comment]
feature

**Comment by silicons** [comment]
@bgobandit wtf
