### ISSUE TITLE
nightmare glitch w/ ghosts

### ISSUE THREAD

**Issue by lordheichou** [citadel-station/citadel-main#4682]
okay so round ID was 11055.
i was playing robo, died, and got prompt for nightmare, i hit yet.
nightmare spawned as catatonic
i later took the nightmare after getting cloned, and took out its brain for funsies

i get taken from my body (birddi beyye) and get slapped into the nightmares brain
my body goes catatonic
im now a nightmare's brain, removed from my crew member body....

i apparently rolled nightmare, but my ghost didnt get put into the nightmares body
endround report even said i was the nightmare

**Comment by Poojawa** [comment]
Kinda edge case, seems to be working fine from observation.
