### ISSUE TITLE
Deconstructing walls in maint when the wall spawns over a door creates empty space

### ISSUE THREAD

**Issue by Slayerhero90** [citadel-station/citadel-main#4744]
Round: 11161

You know when the map decides to throw a solid wall underneath a door? Usually, deconstructing that leaves plating, but now it leaves open space.

**Comment by Poojawa** [comment]
Still very much an issue that tg's being lazy about fixing.

**Comment by Poojawa** [comment]
As it's upstream, as well, and idk how the fuck to fix it, it's whenever it gets mirrored
