### ISSUE TITLE
Box Station Maint Cafe windows are the wrong windows

### ISSUE THREAD

**Issue by Slayerhero90** [citadel-station/citadel-main#4804]
RID: 11191

Maint cafe (and therefore clown/mime office) windows are directional windows rather than fulltile windows like they should be.

**Comment by deathride58** [comment]
Not a bug, was intentional.

It does look pretty ugly, though, probably gonna switch the directional firelocks and directional windows out for their full-tile variants when i get the chance.

**Comment by deathride58** [comment]
Resolved with #4906
