### ISSUE TITLE
Infinte bananium from clown office airlock

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#4967]
[Directions]:If you try to deconstruct the clown office's airlock, it'll give you bananium... Without actually deconstructing. I don't know if upstream has this and I'm too lazy to check.

Round ID 11300

**Comment by deathride58** [comment]
FUCK!!!!!!!!!!!!!!!!!!!!!!

**Comment by cebutris** [comment]
What even is the Rejected Hunks tag anyway
