### ISSUE TITLE
Drones Cant Toggle Helm Sprites

### ISSUE THREAD

**Issue by HawkerTheGreat** [citadel-station/citadel-main#5]
I just wanted to bring up a few bugs, nothing crucial or anything.

The Drones cannot toggle masks anymore on their sprites, I've currently tested the welding mask and goggles and it doesn't seem to update on their sprites.

**Comment by TalkingCactus** [comment]
Assuming this was a layering issue, it should be fixed from #14 . I won't close it until we know, though.
