### ISSUE TITLE
Catknights aren't actually cats

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#5016]
No round ID, tested locally (though I also noticed it on the server but I don't know the round ID of that).

Anyways, Lavaknights don't get cat ears. Going off of the original PR and the code, they're supposed to.

**Comment by Michiyamenotehifunana** [comment]
I _think_ I can fix this by switching over to our "big cat" ears, since the original default cat ears appear to have disappeared. Surprised this didn't cause much bigger issues tbh. Then again, this can be entirely moot if bhijn goes ahead with their plan to make catknights furry cats.
