### ISSUE TITLE
Current issues I've noticed with the latest sync

### ISSUE THREAD

**Issue by Poojawa** [citadel-station/citadel-main#5203]
Scrubpup don't respect blacklisting of items

Races are entirely invisible again. Sigh.

Map load might be fucked, wasn't really paying attention to it. old maps were cleaned up as well.

**Comment by deathride58** [comment]
Could solve races being invisible by porting over hippie's modular species spritestuff

**Comment by Poojawa** [comment]
That's not the issue. 

species code has to be directly modified, and probably needs an overhaul. just haven't really looked into it again.

**Comment by Poojawa** [comment]
The sync branch is now updated with 1/31 because holy fuck I can't be arsed to continue updating maps

**Comment by Poojawa** [comment]
Removed the old Citadel map. It doesn't even load in DM anymore, all that's left are a few dirty var edits on the 'backup' maps from travis.

Layers were slightly refractored, but mob icons aren't showing up and I don't fucking know why :C

**Comment by Poojawa** [comment]
wew.
