### ISSUE TITLE
Odd spawn as round-start AI

### ISSUE THREAD

**Issue by ZeroNetAlpha** [citadel-station/citadel-main#5373]
Issue reported from  Round ID: 11621 (Citadel Station 13)

Reporting client version: 511
https://gyazo.com/860c61df043b1a0a4833047d32c52318
Spawned in as an AI round start and the spawn placed me in a secondary AI slot. 

[Round ID]: # 11621
[Reproduction]: # Unsure how to reproduce. Ready up as AI i guess?
[For Admins]: # Nothing to note.

**Comment by cebutris** [comment]
Upstream issue. Fixed in #5376

**Comment by deathride58** [comment]
Fixed by #5376 which just got merged
