### ISSUE TITLE
Conveyor belts do not work on cargo shuttles

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5381]
Issue reported from  Round ID: 11626 (Citadel Station 13)
Reporting client version: 511

The cargo shuttle conveyors no longer work when the conveyor switch in cargo is activated (all maps, boxstation.)

Basically this bug makes it annoying to load and unload crates as they don't actually make it onto the shuttle fully.

**Comment by Poojawa** [comment]
do they not leave the belt at all or?

because belts don't push more than one off the belt

**Comment by lightcat** [comment]
The dual pair of conveyor belts on the shuttle do not work. Every map is affected.

The first conveyor belts that touch the cargo shuttle don't work.
as in dont turn on.

**Comment by Poojawa** [comment]
I haven't noticed this issue of late, or at least, it hasn't really been an issue. conveyors push and pull boxes as expected
