### ISSUE TITLE
Orm still confirmed broken

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5425]
Round ID 11669
The orm machine still eats mining satchels of holding.

**Comment by AmatsuDF** [comment]
It also will eat a lot of stuff, like PKAs.

**Comment by Poojawa** [comment]
Doesn't eat mining satchels of holding from my testing

Did eat the PKA. seems to be intended behavior as you can also insert guns into 'em as well.

it's basically a 'careful with your click' sort of situation.
