### ISSUE TITLE
Slime People - Liver = Toxic heaven

### ISSUE THREAD

**Issue by Kyutness** [citadel-station/citadel-main#5559]
[Round ID]: #11781

[Reproduction]: 
1.) Be a slime person
2.) Have someone surgery your liver out
3.) Enjoy being practically immune to charcoal, omnizine, tricordrazine, anti-toxin, and if you're a xenobio slime person (splitting kind) enjoy having stupid amounts of jelly production to make clones with. INFINITE BODIES! Constant toxin damage is instead converted to a passive toxin healing effect.

**Comment by Poojawa** [comment]
@jakeramsay007
