### ISSUE TITLE
Engineering cyborgs cannot weld airlocks

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#557]
Airlocks require disarm or grab intent to weld. Cyborgs only have help and intent, and cannot weld an airlock to decon it and get the board out if emagged. Or simply weld an airlock in general.

How to reproduce:
Target any airlock as an engineering borg with a welder
Receive the message 'This airlock door does not need repairing'
Switch intents and use welder again
Attack the door with the welder.

**Comment by LetterJay** [comment]
https://github.com/tgstation/tgstation/issues/25292
