### ISSUE TITLE
Tyrant Lawset is loading antimov

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5625]
Yeah I'm not going out of my way to test this unless I can do it round end but it loaded a law to kill all humans instead of Tyrant laws.

**Comment by Poojawa** [comment]
I've actually seen the tyrant lawset uploaded. during the golem BSA drama.

they were properly applied. 

`inherent = list("Respect authority figures as long as they have strength to rule over the weak.",\
					"Act with discipline.",\
					"Help only those who help you maintain or improve your status.",\
					"Punish those who challenge authority unless they are more fit to hold that authority.")`
