### ISSUE TITLE
Slime + cyborg gear + regrow limb = regrowing cyborg gear for free

### ISSUE THREAD

**Issue by Poojawa** [citadel-station/citadel-main#5632]
Just on the tin. a slime replaced their body with cyborg limbs, instead of being an android, they were still capable of regenerating limbs.

@jakeramsay007

**Comment by cebutris** [comment]
This isn't Chayse's fault, is it? Slimes have always been able to regenerate limbs, have they not? If so, this might be an upstream issue

**Comment by Poojawa** [comment]
it might be, but also he's the maintainer of slimes on our code, so

**Comment by Poojawa** [comment]
found to be edgecase/fluke. good stuff.
