### ISSUE TITLE
GHOSTS CAN BECOME SPIDERS

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#565]
PLAYER CONTROLLED SPIDERS ARE VERY VERY OVERPOWERED, AND FOR SOME GODAWFUL REASON ANY GHOST CAN BECOME THEM. THIS CAUSES ANY SPIDER EVER TO BASICALLY GET THE SHUTTLE CALLED. PLEASE HELP.

**Comment by LetterJay** [comment]
This only applies to sentient spiders and isn't really a bug or issue and more of a gameplay thing.

**Comment by ktccd** [comment]
The thing is, that if a sentient spider makes an egg-cluster, the egg cluster will be changed to spawn spiderlings with their player-controlled variable set to true. So when they grow up, they become MORE player-controlled spiders.
This is obviously intended, as it's explicitly coded to be like this, so it's up to the xenobiologist to not make sentient spiders carelessly.
EDIT: So it's not any spider ever, it's only spiders that were created by egg-clusters laid by sentient spiders.
