### ISSUE TITLE
Research point to round escalation mismatch.

### ISSUE THREAD

**Issue by fludd12** [citadel-station/citadel-main#5677]
I definitely understand the reduced research points due to our longer-lived rounds, but not every round is extended. Several gamemodes have a scale of progression over the course of the round, and while TG's shorter rounds allow this scale of progression to happen rather quickly, science is no longer capable of keeping up with this scale.

Unsure how much of an issue this presents, may require player discussion, but simply posing my view on the matter.

**Comment by fludd12** [comment]
An example: On TG code, if nuclear operatives declare war, there will be an average of about 38 research blocks capable of being unlocked, minus four or eight depending on if they intend to research weaponry and advanced weaponry, before the operatives can arrive.

On our code, there is an average of thirteen, which gives enough for advanced weaponry and maybe one weapon depending if there is enough points to research the other prerequisites.

**Comment by cebutris** [comment]
Solution for that specific example: Make war declaration massively increase research generation. "There's a significant threat to you're station, we're remotely overclocking your research servers" or something like that

**Comment by MimicFaux** [comment]
Remember, CWC can also declare war

**Comment by Poojawa** [comment]
added to the trello
