### ISSUE TITLE
Medical Borgs both hound and normal Cannot use Defibs

### ISSUE THREAD

**Issue by Harakoniwarhawk** [citadel-station/citadel-main#5694]
[Round ID]: 11891

[Testmerges]:  

[Reproduction]: Be A medihound and try and select the Defibrillator paw module, you will be unable to and attempting to apply the Defibrillator upgrade will do nothing either.
The same thing occurs when a mediborg is given the Defibrillator upgrade, they cannot select the module either.

[For Admins]:

**Comment by Poojawa** [comment]
rip. will look into this tomight
