### ISSUE TITLE
Tesla coil research boards not working as intended.

### ISSUE THREAD

**Issue by ZeroNetAlpha** [citadel-station/citadel-main#5778]
Issue reported from  Round ID: 11961 (Citadel Station 13)

Reporting client version: 511

[Round ID]: 11961

[Reproduction]: # Tesla Coil Research Variant not creatable on main server.
Steps for reproduction.

1. Get a tesla coil board from engineering autolathe.
2. Use screwdriver on tesla coil board to turn it into research variant.
3. Something fucks up here and the new board is essentially blank.
4. Try to build it anyways. Get to the last step to screw it all together and nothing happens when screwed.

**Comment by Poojawa** [comment]
Fixed ~
