### ISSUE TITLE
Immortal Revs

### ISSUE THREAD

**Issue by Squi-RL** [citadel-station/citadel-main#5780]
Issue reported from  Round ID: 11966 (Citadel Station 13)

Reporting client version: 511

[Round ID]: # 11965
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Be revenant, get killed, get up immediately afterwards

[For Admins]: # no admin shenanigans involved as far as I'm aware.

(hope I filled out everything right)

**Comment by Poojawa** [comment]
Upstream issue. it'll be fixed soon(ish)
