### ISSUE TITLE
Broken shuttle conveyors (With picture)

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5826]
https://imgur.com/a/5cTB4

The white crate on the conveyor (Furtherest to the left on the conveyor) is on a conveyor that doesn't move. It moved in previous versions.

**Comment by ZeroNetAlpha** [comment]
This was broken when they changed how shuttles work upstream.

**Comment by Poojawa** [comment]
Can't really do anything about this. until upstream fixes their shit (freeze on the 21st)
