### ISSUE TITLE
Golem's being unable to speak 

### ISSUE THREAD

**Issue by Harakoniwarhawk** [citadel-station/citadel-main#5844]
[Issue]: # Was a Free Golem and found out that every time I tried to speak I got the 'You cannot seem to speak' message.

[Reproduction]: # Become a free golem and try to speak, be unable to.

**Comment by Knightfall5** [comment]
This seems to happen with a few different roles. Pirates and Ashwalkers both weren't able to talk as well. Seed vault plant people, however, can talk just fine.

**Comment by MimicFaux** [comment]
Abductors too. (But this seems to be solved with an admin heal)

**Comment by Poojawa** [comment]
resolved
