### ISSUE TITLE
Human legs show under naga section

### ISSUE THREAD

**Issue by LetterJay** [citadel-station/citadel-main#593]
I'm sure this is well known by now, but people have been saying legs are showing with the naga sprites if you pick naga as your taut part. This probably has something to do with the new system or something was missed during the update. I'm not sure which. @Poojawa would probably know more about it since they worked more with the taur code than I have.

**Comment by Verkister** [comment]
It seems to be a problem with all taurs, not just nagas. The extra color layer just isn't showing up for some reason on any applicable taur.

**Comment by Poojawa** [comment]
#456 would probably resolve the leg issue. as for colors and stuff, it's likely needing a prioritization of color layering since they changed it all up. 

Admittedly, I was just guesstimating on what was already done.

**Comment by LetterJay** [comment]
I forgot to close this. I 'fixed' it by reverting mutable_appearances for extra layers to use images instead. While it costs more to render, it works. So either I overlooked something or MA doesn't support more than one layer.

**Comment by Poojawa** [comment]
>commented 19 days ago
>I forgot to close this.

>closed this 29 minutes ago
