### ISSUE TITLE
PA eats emag

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5932]
Clicka  few times on a console and it just fries the Emag while not emagging the console.

**Comment by Poojawa** [comment]
You've never been able to emag the PA. just pulse wires.

**Comment by lightcat** [comment]
No reopen this you missed the entire point here.  The **PA MAKES THE EMAG GO BLACK. IT FIRES IT DESPITE YOU SAYING IT CANT BE EMAGED.** There is a problem here.

**Comment by Poojawa** [comment]
The problem is you're trying to emag something that has no emag function. It's not a bug.
