### ISSUE TITLE
I cant enter cidadel server.

### ISSUE THREAD

**Issue by Jorjao1234** [citadel-station/citadel-main#594]
Soo,i played cidadel server for a long time,then I had to format my computer and after that i tried to enter the cidadel station and everytime i try it says conection died,i don't know why this happens,because i dont got banned or something like that,I did not know where else to look for help for my problem, I hope they can help me solve this because the citadel server is my favorite server and I really do not know what the problem is.

**Comment by TalkingCactus** [comment]
We recently changed our IP. Try joining from the SS13 BYOND hub and then (if applicable) change your bookmark to the new IP. If you do not receive an error message besides `connection died` after doing this then it's something on your end and there's nothing we can do, sorry. For further assistance, try checking the tgstation [forums](https://tgstation13.org/phpBB/) and/or GitHub [issues](https://github.com/tgstation/tgstation/issues) section.
