### ISSUE TITLE
Life is hard nighmares. (Exhaustion, vore safety net, borg-lights not disabling)

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#5958]
Issue reported from  Round ID: 12098 (Citadel Station 13)

Reporting client version: 511

Entered the round inside an atmos gas tank, jumped into space to make it onto the station, by the time I'd smashed my way through a window, I was too exhausted to break **any** lights. Suggestion: Apply the Kinetic Crusher stamina regen to Light Eater, as the sole weapon and tool of a nightmare, swinging it around is going to be done a lot. Getting throw a window shouldn't be a herculean effort.

After disposaling myself I ambushed the CE in maint. Unfortuantely, they had gutsnuggled someone, and despite their host being very dead, they were still free to scream and broadcast my location. It's always been policy that vore not be used for combat advantages, and carrying around a friend inside you that cannot be reached, is bad for business to antags trying to be stealthy. If people want a pocket alarm, pAIs are a thing. Those at least can be stripped off and spaced. Suggestion: Vore'd occupants be dumped out on death.

After fleeing the scene, a pair of mediborgs came racing to the site of human harm. The light coming off them wouldn't disable after several hits, leaving me trapped and dying. suggestion: Coding knowledge I lack.

**Comment by Poojawa** [comment]
Borg lights are a very small % chance to be disabled. because being able to one shot them is bullshit. 

I'll see about putting some sort of vision filter on prey again, I've a few ideas.

**Comment by deathride58** [comment]
Could probably add stamina regeneration upon breaking light sources with the nightmare armblade, aye.

**Comment by Poojawa** [comment]
or just make stamina regen faster in shadow
