### ISSUE TITLE
Dying in combat mode, prevents ghosts from normal click functions

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#5960]
Issue reported from  Round ID: 12100 (Citadel Station 13)

Reporting client version: 511

How to reproduce: Be in combat mode, die, be unable to right click as a ghost to open the dropdown to examine things.

**Comment by deathride58** [comment]
It's a minor bug. You can resolve this yourself ingame by using the "Toggle rightclick" verb in the OOC tab.
