### ISSUE TITLE
Shadow walk deleting nightmare

### ISSUE THREAD

**Issue by Lurphinw** [citadel-station/citadel-main#5989]
[Round ID]: # 12118
[Reproduction]: # Spawned as a random event Nightmare. Upon being down by a beepsky and crawling back into to a dark tile, My nightmare was deleted immediately upon shadow walking. Unfortunate because everyone was scrambling into maint right after!

**Comment by Poojawa** [comment]
@deathride58 I've gotten confirmation of how this is being reproduced.

They get qdel'd when they shadow walk in stamina crit,
