### ISSUE TITLE
"Lost in blue space" The death of and life for a Cyborg!

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#5996]
Issue reported from  Round ID: 12140 (Citadel Station 13)
Reporting client version: 511
[Reproduction]: Get a body bag, then place it under a borg before picking it up, then place the body bag now with a borg into a Bag of Holding. Then place them into the  destructive analyze before going in and recovering the mats uses the make the Bag of Holding. Then go to robotics and make a reboot bord for the Cyborg, they come back to life! But are useless other then door nobs or harm alarms
https://imgur.com/a/OYcmC

What this dose is removes there everything! There cell, there systems, any mods they have even there Posi brain or MMI(Like how Syda-Cyborgs don't have brains if its magic carp spawned in) They can be reconstructed but are still able to be revived and talk/move. Your also unable to deconstruct them after cutting all wires I found them unable to go back to being able to chose there model and if you try to wrench them it goes into a loop of activating the bolts but never goes past it to deconstruct the Cyborg.
When revived was still able to be locked down and blown*

**Comment by Poojawa** [comment]
this is... edgecase

I'm not even sure where to begin. First off, WHY

**Comment by Trilbyspaceclone** [comment]
Its for a other reports as well but that is character nulling sorta thing... I wanted to test what happens if you decon someone that is in the medihound sleeper as well... Just need more test subjects! The idea being that you can remove someone form the round with a Emag Borg... I'm thinking its going to pop out the person but still testing more blue space body bags!

**Comment by Poojawa** [comment]
Okay but y tho

**Comment by Trilbyspaceclone** [comment]
Mostly it was just me joking around and not knowing it would work. The  realized the overpowerd things you can do. *Will make a different github Issue about all the little quirks its has! Going more into the Carbons and NPCs as well as what happens when you add a AI and decon them. Still testing if you can bag megafuna(If you can BDM x Bluespace body bag)*
Also its not about being put into the analyzer its self you have to place it into a object like boh that a analyzer can decon to get the mats back

Back form MORE testing!! Side note you can in fact still decon borgs... Also if someone is in the borgs bell it pops them out alive but removed there items.
To answer the question "Why do you do this" its all in this one tip ``"Tip of the round: The more obscure and underused a game mechanic is, the less likely your victims are to be able to deal with it."``

**Comment by Poojawa** [comment]
Quit fucking deconning borgs. jesus christ.
