### ISSUE TITLE
Digestion noises can only be toggled off

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#5999]
[Round ID]: # 12148
Call me slow, but I just tested out the sound toggles from #5789 and found something interesting.
![image](https://user-images.githubusercontent.com/27295611/37596817-5feed756-2b4b-11e8-8cb0-99a8dbeaacaa.png)
tl;dr you can successfully toggle eating noises and dogborg sleepers, but you can only toggle digestion noises off and not back on.

**Comment by Poojawa** [comment]
fixed in #5994
