### ISSUE TITLE
Missing a way to rebuild a PDA messager for Telecoms

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#6034]
Issue reported from  Round ID: 12165 (Citadel Station 13)

Reporting client version: 511
 - Truns out there IS no PDA messager bord... Its a world object that cant be rebuilt. 
[Reproduction] Brake it
Rods,meteors, Antags and more can take out PDAs for the whole round. 
Perhaps make PDA messager a build-able object that has a high build cost do to being so important for the crew. Spit ball cost of 5 capacitors 2 manipulators 2 lasers for the basic parts. For Telecoms parts 2 subspace transmitters?

**Comment by Poojawa** [comment]
Solved in a PR upstream.
