### ISSUE TITLE
Synthflesh vial in hypo kit does nothing.

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#6047]
**Round ID**: 12177
**TestMerge Ref**: #5907 

CMO's hypospray kit contains a vial of Synthflesh... which does nothing. Synthflesh only heals on surface/skin application and is a wasted slot. I recommend it be replaced with mutadone or ryetalin or something. Maybe Corazone.

**Comment by Poojawa** [comment]
There's a patch function on the hypo, right click menu.

**Comment by Ragolution** [comment]
oh neat
