### ISSUE TITLE
Laser Carbine Sprite Missing

### ISSUE THREAD

**Issue by Kevak** [citadel-station/citadel-main#605]
#I have no idea, current. Don't think caused by testmerge.

Laser Carbines (The ones printed from R&D) lack sprites. You can right click them on the tile to pick them up but they otherwise don't have sprites. Likely due to a misspell in the code for 'which sprite should item use' Should be a low difficulty fix.

Reproduction involves printing a laser carbine from R&D. Unsure if sticking a firing pin into the spriteless carbine provides a sprite.

**Comment by LetterJay** [comment]
Fixed in #606
