### ISSUE TITLE
Neko ears not spawning

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#6056]
Issue reported from  Round ID: 12181 (Citadel Station 13)

Reporting client version: 511
[Reproduction]: # Go to character Appearance and then go to tail/ears scroll down to Neko, add neko ears and tail see that it dose nothing.

In surgery, neko ears and tail do not show so you cant add/remove them.

**Comment by GrayRachnid** [comment]
can we mark this high priority thanks.

**Comment by ghost** [comment]
Just don't play as a neko nerd lmao
