### ISSUE TITLE
[UPSTREAM] Brass golems CANNOT be created if you have 11 sheets

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#6077]
[Round ID]: # 12191

[Reproduction]: # Create an unfinished golem shell and attempt to add anywhere between 11 and 50 sheets. It will promptly inform you that you cannot make a golem out of that material. Works properly with PRECISELY 10 sheets but refuses all other values in the item's stack, including 11 up to 50.

**Comment by Poojawa** [comment]
Yeah push this upstream ~
