### ISSUE TITLE
SOMEONE FUCKED MOB CODE SOMEWHERE

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#62]
MOBS ARE NOT MOVING, WANDERING, ETC. SOMEONE LIKELY FORGOT A ..() SOMEWHERE OR SIMPLY DELETED SOMETHING THEY SHOULDN'T HAVE. THE LAST CHANGE TO LIVING MOBS AT A LOW LEVEL WAS living.dm FROM @Poojawa

**Comment by ghost** [comment]
**_FIXITFIXITFIXITFIXITFIXIT_**
