### ISSUE TITLE
Prides mirror + Moth Skin + Cancel = Game Breaking Invisibility.

### ISSUE THREAD

**Issue by hotwizards** [citadel-station/citadel-main#626]
My apologies, as this is my first bug report. I can explain what happened, so. Here goes.

Basically. When I stumbled acrost prides mirror, in Lavaland. I used it. Clicked the race tab, but cancelled out when I was on the race menu. Mainly because I just said "Fuck it" and realized I had no time to travel through space. This mistake turned into a glorious moment when I was teleported into space, and spent ect ect finally got to a safe place. This is where the bug happens.

My character has genitalia activated, arousal, ect ect. Including the Moth Body Marking, Insect Body, Bob Hair 2, and Selleck Moustache. And when I took off my clothes to heal myself.

I was just a floating penis. I am /not/ being sarcastic.

I made my way back to the station, and went to the surgeon to remove said penis.

What happened?

I turned completely invisible. I could not drag myself onto anything, but I could interact with anything. As such, my hitbox was completely disabled (unless using sechuds, then there's a very slim hitbox) or picking up items that show up in your hands.

How did this happen?

Going to prides mirror, selecting race option, then cancelling out. As an insect, with the moth body markings.

Do you have screenshots?

http://imgur.com/a/PlOQ5

Did you do any bad things because of this?

I slapped people and whispered into their ear.

I'm both mortified and laughing my ass off right now. I do not know if this can be replicated, and frankly. I have no idea how to run the code to check. But if it can, it'd probably be better to post it anyways.

**Comment by Poojawa** [comment]
@TalkingCactus has this been resolved if you know?

**Comment by TalkingCactus** [comment]
No idea, but I suspect it's not our code that's the issue.

**Comment by Poojawa** [comment]
Still pretty much edge case, sooo.
