### ISSUE TITLE
Lava knights armor ruinning player sprites

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#6297]
Issue reported from  Round ID: 12386 (Citadel Station 13)

Reporting client version: 512

If you ever puck up or ware a lava land knights armor your sprite will be unseeable other then the item that you last interacted with! I.e Only showing a item in hand or pice of clothing
[Reproduction]: # Pick up ANY lava knight armor and be unseen like a true ninja.

Admin Worgilisk handled my Ahelp, fixing my sprite by resetting my charater.

**Comment by Trilbyspaceclone** [comment]
Side note- If you get there bage (ID) or the traitor ID card and mimic there ID then place it into a wallet theirs no sprite for it making your wallet unseeable as well.

**Comment by Poojawa** [comment]
pick up *

wear *

**Comment by Trilbyspaceclone** [comment]
Meh to rare and I think its fixed now!
