### ISSUE TITLE
Upgrading chem dispensers breaks saved recipies

### ISSUE THREAD

**Issue by FalcoGer** [citadel-station/citadel-main#6401]
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
go to chemistry station and enter for example this recipe:

`Cyanide`
`welding_fuel=5;carbon=5;hydrogen=20;nitrogen=5;oxygen=15`

or

`Tricordrazine`
`carbon=10;oxygen=10;sugar=10;carbon=15;silicon=15;nitrogen=10;silicon=10;potassium=10`

without the chem dispenser upgraded, this will produce the right amount of chemicals
when upgraded, and trying to save the recipes it will say 'the chem dispenser isn't precise enough, save anyway?'
when trying to make the above mentioned recipes it will produce plenty of garbage. in case of tricordrazine it makes the 90u tricord, but somehow 2 extra units of kelotane
the cyanide is totally unsuable.

**Comment by Poojawa** [comment]
oh no, how awful.

Not really a bug. Is it really that hard to copy/paste it again?

**Comment by FalcoGer** [comment]
perhaps you would like to READ the problem before you close the issue without resolving it.
a bug is a bug, even if it were trivial to work around it.
then the next logical step after reading the bug report is to TEST the bug.
clearly you have not done that, as your workaround is as useless as i described it to be to begin with.
Perhaps I should be more clear:

the saving recipes system is BROKEN when upgrading chem dispensers.

allow me to describe the problem in more detail.
if you input the recipes in an unupgraded chemical dispenser, they do work.
if you upgrade it after the fact, they do not work any more.
if you input the recipes into the dispenser after the ugrade, the dispenser complains, as mentioned above, and it does not work.

the feature is broken. this is a bug, as in: "it is not working as intended."
I would appreciate you not belittling my contribution, discarding it without giving it even a LOOK, or even  giving the bug report a look.
thank you very much.
I shall reopen and reference the issue.

I find it quite reassuring that bug reports on here are given an ever so brief glance 3 weeks after reporting and then discarded without even a most rudimentary test of the system that would reveal it to be indeed a bug.
Since 3 weeks did indeed have passed, I shall compile the latest version and check for this issue myself, since you are apparently unwilling to do so and would rather ignore the problem.

**Comment by deathride58** [comment]
As much as I hate chem macros, it's really not a big deal to ask for some basic QoL.

This is an upstream issue, and should be reported over at https://github.com/tgstation/tgstation

This issue here will remain open until it's fixed upstream, like how all other upstream issue reports are typically handled.

**Comment by FalcoGer** [comment]
for reference, here is the bug report video
https://youtu.be/DEIIREdrDtY
the javascript errors at the end are just a curiosity and irrelevant in this case.

**Comment by PersianXerxes** [comment]
This no longer happens, for the record

**Comment by DeltaFire15** [comment]
Recipes have been changed to work differently.
