### ISSUE TITLE
DreamSeeker crash as AI with crew monitor open

### ISSUE THREAD

**Issue by FalcoGer** [citadel-station/citadel-main#6414]
Issue reported from  Round ID: 12488 (Citadel Station 13)

it seems that either moving around the crew monitor window lots or moving the viewpoint around while the crew monitor is open will cause dream seeker to hang

- Be AI, open crew monitor.
- move/jump around much with the cam
- crash the game.

**Comment by LetterJay** [comment]
Issue with BYOND

**Comment by Ghommie** [comment]
The main issue with Crew monitors crashing the game was their mini-map exponential likeliness to freeze the client the more human mobs with suit sensors were roaming around the station.
This has been fixed for a long time now by removing the laggy mini-map altogether.
