### ISSUE TITLE
No revenant prompt?

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#6510]
Issue reported from  Round ID: 12607 (Citadel Station 13)

Reporting client version: 512

Deadchat alerted to a revenant spawn, waited patiently, no prompt, no griff ghost

https://cdn.discordapp.com/attachments/322376567839784960/438583484043493376/unknown.png

**Comment by Ghommie** [comment]
I do not recall this ever happing to me those rounds I joined in as an observer. Maybe the prompt simply loaded under the main tab instead, maybe not, this is a 1+ old issue that hasn't been reproduced anyway.
Feel free to re-open another if you believe the issue still lingers around.
