### ISSUE TITLE
Issue 6401 not resolved. closed without testing, discussing or even reading the description.

### ISSUE THREAD

**Issue by FalcoGer** [citadel-station/citadel-main#6654]
Reference Issue #6401
Issue not resolved.
Issue is indeed a bug.
Video demonstrating issue following shortly, since assigned staff seems to not care to, or incapable of performing a simple test himself, but he would rather speculate that it is 'not a bug, just copy it again'.
Well since copying it again would indeed be a bother and not working as intended, yes this is a bug. Since copying it again does indeed not resolve the issue, as described in the bug report to begin with, your advice is useless and shows that you didn't even give it a glance or thought.

Video recorded with the latest build from git, pulled 15 minutes prior to this issue.

Video regarding and demonstrating the issue. If you bother long enough to get to this point of the message that is before discarding it.

https://youtu.be/DEIIREdrDtY

Thank you very much. For your timely response.
And yes, I'm bitter about being completely ignored, then told I'm wrong, told a fix that will not fix it, obviously without even the slightest bit of testing or reading of the issue described.
That is all.

**Comment by deathride58** [comment]
Yeah, the maintainer that closed that previous issue is no longer with us for unrelated reasons.

The issue in question is an upstream issue, though. You'll want to make an issue report upstream about it.

**Comment by FalcoGer** [comment]
whatever that means.
