### ISSUE TITLE
Lighting Bugs

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#67]
Here's a list of anomalies that I've noticed so far.

1. Shuttles: ![shuttle](http://image.prntscr.com/image/8e1a22fae59a495783fe2ff347e13f1c.png)
     Shuttles have always been awful for lighting, even in the last system. The solution use to just be to make shuttles always illuminated. There must be a better solution than this, though.

2. Roundstart: When the round starts, the lighting builds itself. This should happen in the pregame lobby during initialization.

**rest of issues have been resolved**

**Comment by TalkingCactus** [comment]
ONE DAY I'LL DO THE EMBEDDED IMAGES RIGHT THE FIRST TIME WIHOUT LOOKING IT UP

**Comment by ghost** [comment]
I can add lights to shuttles, totally forgot about that.

**Comment by TalkingCactus** [comment]
It's a larger issue than that, I'm sure. For instance, the strange tile in the middle that is lit up.

**Comment by ghost** [comment]
Very strange. I'll have to talk to PJB and do some debugging I suppose

**Comment by TalkingCactus** [comment]
I don't know exactly how you're doing it but I would guess that the overlays you're using aren't being generated unless they're being updated by a light source.

**Comment by ghost** [comment]
They should all generate upon initialization regardless of whether there's any lights affecting them, maybe an issue with how shuttles appear and disappear from movement.

**Comment by TalkingCactus** [comment]
Moreso was talking about the second issue listed, there. Refresh the page if you haven't.

**Comment by ghost** [comment]
Oh, had to refresh. That's really strange as well. I'll work on it, maybe zlevel issue.

**Comment by TalkingCactus** [comment]
It was happening on the station as well. In maintenance mostly.

**Comment by ghost** [comment]
So it seems as though this is happening to areas without affecting lights?

**Comment by PJB3005** [comment]
Isn't lighting on shuttles disabled by default?

I know we enabled it on /vg/ and it liked to runtimes like shit (hoo boy 600 MB runtime logs) due to an impossible error I've been unable to track down.

EDIT: that said the error multiplied exponentially due to another bug which I did fix but the core of it's still there somehow. Oddly enough it's only runtimes and I've yet to discover a visual problem arising from the runtime.

**Comment by ghost** [comment]
It should be but I guess something was changed in the process, i'll see if I can disable dynamic lighting on it.

**Comment by TalkingCactus** [comment]
Yeah, it's basically off. Spent a while on another repo trying to at least come up with some workaround to mimic real lighting. No luck. Shuttles suck.

**Comment by ghost** [comment]
Are there any runtimes, cactus?

**Comment by TalkingCactus** [comment]
No, none.

**Comment by PJB3005** [comment]
https://github.com/ParadiseSS13/Paradise/pull/4679 obligatory port this

**Comment by PJB3005** [comment]
Wait is the shuttle broken when it's docked at station without having been moved at all?

**Comment by TalkingCactus** [comment]
At the station it's fine. Only breaks the lighting after landing on lavaland. Probably an issue with moving and overwriting an area with dynamic lighting versus space/shuttle areas which have it disabled.

Here's what it looks like after re-docking at the station. ![re-docked](http://image.prntscr.com/image/317d6fb6d9b3471db9640bff1df009bf.png)

**Comment by PJB3005** [comment]
Wait I see what's going on. It's taking the overlays with it for some reason.

**Comment by ghost** [comment]
Well, it does move everything on the shuttle along with the vars

**Comment by PJB3005** [comment]
> along with the vars.

Yeah we had an issue on /vg/ related to that too. You're gonna need to exclude every turf level variable related to lighting from variable copying.

**Comment by ghost** [comment]
#68 should fix all this

**Comment by TalkingCactus** [comment]
Shuttles are still updating their lighting and becoming pitch black after moving to lavaland. We need this fixed before we can release.

**Comment by PJB3005** [comment]
Shuttles need to ignore lighting overlays and again, if they're doing any variable copying like on /vg/ disable it.

**Comment by ghost** [comment]
Like I said I have no idea how to do that so unless someone can show me an example or do it themselves my hands are tied. :v

**Comment by ghost** [comment]
Shuttle code is also such a clusterfuck I wouldn't even know where to put it

**Comment by TalkingCactus** [comment]
I'll attempt to bundle a fix with my current PR if I can.

**Comment by TalkingCactus** [comment]
bump @unusualcrow

**Comment by ghost** [comment]
you said you'd try to bundle a fix with your current PR so I let it go, I don't have any idea how to fix this

**Comment by PJB3005** [comment]
Have you tried?

**Comment by ghost** [comment]
no because i don't know where to begin 💯 💯 💯 💯 💯 💯

**Comment by PJB3005** [comment]
It's related to the order of moving of turfs related to variables, I'll take a look.

**Comment by ghost** [comment]
As for the second issue, i'm not sure how specifically the lighting setup works but create_all_lighting_overlays() is definitely run during the subsystem's initialization which is pregame.
It seems to appear when the game begins on /vg/ as well.

**Comment by PJB3005** [comment]
The actual core of the issue I've found is that shuttle code doesn't correctly notify the turf of having its area changed when it changes. Also I think the shuttles might be moving lighting overlays.

So basically the turf sees, after the turf gets changed, that the dynamic-ness didn't change which is false because the area DID change in dynamic-ness, but it never notified the turf.

**Comment by PJB3005** [comment]
... Did nobody report the glaring issue that picking up flashlights didn't work?

Well, I fixed it.
