### ISSUE TITLE
Peaceful eye stab murder & being able to smash bottles over peoples heads

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#6741]
Issue reported from  Round ID: 12836 (Citadel Station 13)

Reporting client version: 512
It allows me to harm Players and myself, as well as mobs that have "Eyes" that can be stabbed
Its harmless! *Health scans tell that it dose eye damg and 7 harm* 
Turns out you can also smash people over the head with bottles to! Oh the peaceful horror!
[Reproduction]: #Get a screw driver and aim head well having Pacifist trait... 
[For Admins]: # BlackMajor saw this first hand and in LOOC told me it was do to quote "LOOC: Durgit: eye stabs are a different form of attack that isn't covered under the pacifism deny's"

**Comment by Wilchenx** [comment]
Report it upstream
