### ISSUE TITLE
Alien Stuns do not work with new stamina system.

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#6786]
Issue reported from  Round ID: 12884 (Citadel Station 13)

Reporting client version: 512

This was tested as a queen.

NeuroToxin spit does not paralyze Receivers as the description states it does. People who get hit can nearly instantly pull up a gun and start shooting.

Tackle may be broken as well, couldn't test.

**Comment by lightcat** [comment]
I should also mention that you cant drag bodies away easily since they can just crawl away... big HEFT XENO. Probably due to the issues above.

**Comment by Trilbyspaceclone** [comment]
Neuro Toxin dose not stun anymore, xenos get the same stuff as the drink. But it dose tons of stam damg as well as the pounce always placing you in stam crit.

**Comment by MimicFaux** [comment]
Should tack this on here, but abductors are also having a rough time. (Although not to the extent xenos are)

**Comment by Ghommie** [comment]
This has been fixed (then broken, then fixed, then broken, then fixed for the final time) long time ago.
Feel free to open a new issue next time someone fouls up alien tackle and/or neurotoxin.
