### ISSUE TITLE
All fedora's spawning with detective flask and have armor value's

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#6803]
Issue reported from  Round ID: 12904 (Citadel Station 13)

Reporting client version: 512
The ClothesMate Vender is vending out fedoras with the Detective flask as well, Its armored like detectives gear as well. 
*All fedoras spawning with Detective Flasks
*As well as all fedora are armor [armor-25-5-25-10-0-0-0-30-50-0]

[Reproduction]: # Go to the  ClothesMate Vender and vent one to get a armored sec-gear hat with a flask of whisky and all! 
*March 5th 2018 update*-  Turns all all fedora spawns are spawning with Detective Flask and armor (aka Library, bar, maints area ect.) 

[For Admins]: #  -Derkuleen and BlackMajor are the admin that handled my Ahelps.

**Comment by Trilbyspaceclone** [comment]
*Theory on this*
Detective Fedora is pulling its armor stats form normal Fedora and normal fedora is pulling its inventory form detective fedora
Unknown why normal Fedora is armored, most likely do to old gang game-mode replaced the Fedora with armored gang Fedora
*End of Theory on this*

PM to-Admins (Lilly Trilby): If its pulling a fedora form the detec locker then it could be armored
-- Administrator private message --
Admin PM from-Derkuleen: let me check the values on it then
-- Administrator private message --
Admin PM from-Derkuleen: yeah, lol it is

**Comment by Trilbyspaceclone** [comment]
PM to-Admins: can you stat that fedora?
Admin PM from-BlackMajor: HAHA WHAT IT HAS 25% RESISTANCES
Admin PM from-BlackMajor: armor [armor-25-5-25-10-0-0-0-30-50-0]
**With more testing and code looking** 
obj/item/clothing/head/fedora
    name = "fedora"
    icon_state = "fedora"
    item_state = "fedora"
    armor = list("melee" = 25, "bullet" = 5, "laser" = 25, "energy" = 10, "bomb" = 0, "bio" = 0, "rad" = 0, "fire" = 30, "acid" = 50)
    desc = "A really cool hat if you're a mobster. A really lame hat if you're not."
    pocket_storage_component_path = /datum/component/storage/concrete/pockets/small
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/e0f971ecbb843c5caddbba5ec3d6ba11a8e52d76/code/modules/clothing/head/misc.dm

**Comment by improvedname** [comment]
its a subtype
