### ISSUE TITLE
Plants randomly dying

### ISSUE THREAD

**Issue by Greenpoison** [citadel-station/citadel-main#687]
As a botanist this is an issue that has been plaguing us recently. Plants that have completely fine stats are showing up as "looking unhealthy". Just a prior warning that this is my first issue report so apologies for how messy this is. Evidence of the issue:

https://gyazo.com/5d6e501da19a647e680579e4f8919c07
https://gyazo.com/b2c9dc420768f3ffff9601cb42977776

**Comment by TalkingCactus** [comment]
`Lifespan: 29`
Are you sure your plants aren't just dying of age?

**Comment by Greenpoison** [comment]
I'm an idiot, thanks for pointing that out (still fairly new to botany and in game mods said it looked like a bug).
