### ISSUE TITLE
Robots dont need ID access to turn on and off

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#7046]
This is kind of game breaking to robotics. Besides beepsky and others that spawn on the map any built robot can be turned off. So any securtron, ED and floorbot and be turned on and off without the required access.

**Comment by LetterN** [comment]
they do. they just show the on and off switch. But you still require the access for it to be turned on and off

**Comment by improvedname** [comment]
@deathride58 close not an issue

**Comment by lightcat** [comment]
I can still do this and have manually done this that is why there was a bug report.
