### ISSUE TITLE
Light tiles can be made without using up the wired glass sheets

### ISSUE THREAD

**Issue by DenialDuckOfService** [citadel-station/citadel-main#7192]
Issue reported from  Round ID: 13275 (Citadel Station 13)

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # 
[Round ID]: # 

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: So basically i was making some light floor tiles and at the final step where you add metal sheets to the wired glass sheets, the wired glass sheets are not consumed, only the metal is consumed in this proccess.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Poojawa** [comment]
can't replicate.

 That's some wired glass tile
There are 6 wired glass floor tiles in the stack.
You make a light tile.
 That's some wired glass tile
There are 5 wired glass floor tiles in the stack.
 That's some light tile
There is 1 light floor tile in the stack.
