### ISSUE TITLE
Canvases Causing Dreamseeker Crashes

### ISSUE THREAD

**Issue by rpilcrow** [citadel-station/citadel-main#7269]
[Round ID]: 13394, and some far earlier rounds that I don't recall the ID of.

[Reproduction]: Currently using BYOND 512.1427, Windows 7.
I'm not sure how many people this is affecting, but it's almost certainly not an insignificant number, since during a round in which somebody sat in the bar painting, I noticed a disproportionate amount of people complaining about crashes (and then they stopped when that person went SSD and the painting was removed).
Anyway, the issue seems to occur whenever the game first tries to render a canvas that has been modified while out of your view. The problem doesn't occur when rendering a canvas that is in view when you log in, however.

Reproduction would almost certainly require two or more people, but the steps are pretty simple;
- Put a canvas down
- Start drawing on it
- Get somebody else to walk by
And as much of a dick move as it might be, it could also be tested by setting yourself up in an art storage and watching for people to go SSD as they walk by.

I wish I could offer more details, but that's about it.

**Comment by Poojawa** [comment]
Upstream issue. tbh these should be disabled till fixed.
