### ISSUE TITLE
Defib wall mounts spawn full defibs

### ISSUE THREAD

**Issue by Hemlock32** [citadel-station/citadel-main#7376]
Issue reported from  Round ID: 13589 (Citadel Station 13)

Reporting client version: 512

[Reproduction]: # Picking up a defib from a wall mount, spawns a defib on the ground, or in your hands. A full defib. Not the paddles. But, the one on the wall stays there. Then, removing the defib from the wall de-spawns the one spawned by the glitch

This issue has been present for well over a week now, and I was not the one to discover it

**Comment by Poojawa** [comment]
Known issue, TG's lazy on the fix.
