### ISSUE TITLE
radio emotes conflict with drunk memes

### ISSUE THREAD

**Issue by nik707** [citadel-station/citadel-main#7423]
[Round ID]: #13773

Not testmerge related.

[Reproduction]: Being drunk occasionally makes your character *BURP*, which if it happens at the end of a chat message on radio results in your message coming across as an action, I believe the same happens with normal say. Perhaps a possible fix is to add something after the asterisk to prevent it, Iunno.

**Comment by Poojawa** [comment]
they only activate on . s so just have shit grammar and you'll be fine.
