### ISSUE TITLE
"Return to lobby if preferences unavailable" defaults to assistant.

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#7443]
Issue reported from  Round ID: 13870 (Citadel Station 13)

Had only silicon roles set for my preferences, and round began as a normal assistant.

**Comment by Poojawa** [comment]
Cannot replicate. 

Set two accounts to 'high' pref AI, return to lobby.

One got AI, one was kicked back to lobby as expected.

`Starting game...

You have failed to qualify for any job you desired.

ADMIN LOG: Could not find ai landmark for (selected ckey) . Yell at a mapper! We are spawning them at their current location.`

Might've been a fluke, as the game has an 'emergency' setting people to assistant if they were chosen or almost chosen for an antag role.

**Comment by MimicFaux** [comment]
Good enough for me.
