### ISSUE TITLE
TAIL WAGGING BUG!?

### ISSUE THREAD

**Issue by zombieme7** [citadel-station/citadel-main#7537]
[Round ID]: #14325

[Testmerges]: # When being petted, your tail starts to wag, but if you climb on a table it'll stop.

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Poojawa** [comment]
that's weird

but also likely a side effect of the translate that sprites do now on tables. damnifino

**Comment by deathride58** [comment]
Likely due to Stun() causing a chain of proc calls that eventually end with your tail no longer wagging due to your being incapacitated
