### ISSUE TITLE
Cryo pods never places items into storage or log people cryoing on the console 

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#7554]
[Round ID]: 
Any round that people cryo

[Reproduction]: 
Be any job and have any item that is listed to stay in round. Cryo, relise that your items are not in the console but openly on the ground for anyone to take, then hear 15 mins latter that people think your dead some were do to the console unable to display peoples name is they cryoed 

[For Admins]:
I quite remember a time when this worked, and items were recover via people with proper access like sec/heads/silicons

**Comment by izzyinbox** [comment]
I manually fix this each round by mass modifying the sleeper's `control_computer` to the wall computer object, if that helps pinpoint the issue.
