### ISSUE TITLE
OmegaStation missing CMO Hypo!

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#7578]
Round ID:  
4364
Map:
OmegaStation
Round Type:
Traitors & Changlings

Issue:
There is no CMO Hypo spray making people/THINGS(Changlings) unable to greentext!

Reproduction:
Role antag, have the goal to steal the CMO Hypo spray, take the ONLY one that is non-vender and STILL FAIL even when Admins/Mentors tell you it works and will count to it!

For Admins:
Sadly the Hypo is the *old* hypo and don't have the new flange safety that make death-mix'es in 3 seconds not do able. Its the old op robust hypo not the new one

**Comment by Poojawa** [comment]
If it doesn't have a CMO locker, then w/e
