### ISSUE TITLE
HoS Trenchcloak literally doesn't exist

### ISSUE THREAD

**Issue by ComradeNecron** [citadel-station/citadel-main#7581]
[Round ID]: 14397

it's probably still in the code somewhere, but appears nowhere on-station or in the loadout screen

**Comment by Poojawa** [comment]
if it's not in the locker, I think it was meant as an alt wearing version.

**Comment by Michiyamenotehifunana** [comment]
It was never added to the loadout. The locker code was not modularized properly and the changes to it have regressed.
