### ISSUE TITLE
A SECOND TAIL WAGGING BUG!?

### ISSUE THREAD

**Issue by zombieme7** [citadel-station/citadel-main#7588]
[Round ID]: #14447
[Round ID]: # (**INCLUDE THE ROUND ID**)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Someone pat me on the head while my tail was wagging, and my tail stopped wagging 
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Poojawa** [comment]
*wag is just a switch emote

but it's an easy fix
