### ISSUE TITLE
Piggy back space walkers (With a canister)

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#7607]
Round ID
14544
Map "Meta Station"

[Issue]:
You can freely move around in space without a carp or jet pack with a friend easily removing any danger of floating of into the dark, full void that is SS13 space.

[Reproduction]: 
Well you piggy back someone, they can drag a canister around. Well dragging a canister around you can go into 0-g and space walk like normal without a jet pack freely moving! If you are running or sprinting this makes you go at faster speeds, as if your pushing off a wall.

[For Admins]: 
This is second hand bug reporting. I have not seen/confirmed this bug for myself and are doing it on behalf of a friend.

**Comment by funnyman2003** [comment]
bro..this ain't a bug, THISA FEATURE. Punishes dorks for not having freinds B)
