### ISSUE TITLE
Animal ears and tails will not save

### ISSUE THREAD

**Issue by queenrogerSS** [citadel-station/citadel-main#7609]
[Round ID]: Encountered on a private server with no changes

[Reproduction]: Set your Tail and Ears setting as something in Character Appearance as a human and save setup. When switching characters back and forth, or restarting the server, they will not appear and will have to be set again to work.

**Comment by Poojawa** [comment]
Swapping characters of different species does reset the preferences, due to different default features.

I don't know why it's not cleanly swapping between loads tho. :v

**Comment by SkullyRoberts** [comment]
This bug has been fixed, at least for me.
