### ISSUE TITLE
Cat ears/tail don't save even when you tell it to!

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#7613]
Issue reported from  Round ID: 14587 (Citadel Station 13)
Reporting client version: 512

[Reproduction]
Save your Feline character ears and tail as cat, then next round when you check your cat like ears and tail... You fine them unsaved!

[Fix!]
Cry in a hole till it gets better!

[For Admins]
Weh

**Comment by Poojawa** [comment]
duplicate of #7609
