### ISSUE TITLE
Patch Update prevents Golems from healing themselves.

### ISSUE THREAD

**Issue by WallaceShark** [citadel-station/citadel-main#7661]
[https://i.imgur.com/eeu9QO1.png](url)

[Round ID]: 14756

[Reproduction]: Spawn as Golem. Use patch on self. Fail to do so.

Recent pull (#7651) blocking suit-users from using medicine patches prevents golems from using their ship's medicine patches. Golem skin counts as a hard material, so they are essentially blocked from all sources of healing save for dedicated medical machines they do not have access to.

This was mentioned to be a possible consequence of the pull request, but nothing was done to fix this before merge.

Switching Golem skin to a soft material could act as a work-around, but I dunno if that'l break anything else (space/pressure resistance).

**Comment by MimicFaux** [comment]
Skeletons too.
