### ISSUE TITLE
Space Parallax Overlays All Turf and Mobs

### ISSUE THREAD

**Issue by IgiariValkyr** [citadel-station/citadel-main#77]
Issue concerning the Space Parallax for animated stars and what not.

-Issue caused just by a base compile from 510.1332 version of Dream Maker, which is the earliest version of Dream Maker able to compile Sixth Port without code issues. Runs on latest Dream Daemon.

![c05eadb4069f6e4ae5623a3b0b3c4d91](https://cloud.githubusercontent.com/assets/5521322/20647134/dd7f03b6-b451-11e6-9c7d-8936b2fdbef1.png)
![921d8addfdb37badcb3d616ce9eb3a66](https://cloud.githubusercontent.com/assets/5521322/20647136/dfc9a5f4-b451-11e6-970c-8335bd0b1d8a.png)

-Current workaround: Disable parallax through game preferences and restart Dream Seeker. Stops the parallax from being shown, thus removing it from overlaying everything.

**Comment by TalkingCactus** [comment]
@unusualcrow Can you take a look at this?

**Comment by TalkingCactus** [comment]
Also try the latest version of 510 if you haven't, yet.

**Comment by TalkingCactus** [comment]
Working just fine for me on byond 510.1347
![working](http://image.prntscr.com/image/4c3ddfb36cec4b12ae9d0038e9be4df1.png)

**Comment by ghost** [comment]
He's using an earlier version of BYOND, that's why.
Compatibility for planes and stuff was introduced later so it'll break if you're not using latest.

**Comment by TalkingCactus** [comment]
I'll change the minimum version, then.
