### ISSUE TITLE
Cult whispers need exclamation points removed.

### ISSUE THREAD

**Issue by Bapldap** [citadel-station/citadel-main#7768]
Issue reported from  Round ID: 15250 (or some shit) (Citadel Station 13)

Reporting client version: 512
Cult whispers have an exclamation point at the end. It's an easy fix so you just need to remove the exclamation points from the whispers. Since they have exclamation points, they can be heard through walls fifty miles away, and it's pretty gamebreaking.

**Comment by Poojawa** [comment]
@deathride58 

this is your code

**Comment by SkullyRoberts** [comment]
Fixed by #7765 . Suggest closing this report.
