### ISSUE TITLE
BUG report: loading lavaland rivers in build mode soft crashed server.

### ISSUE THREAD

**Issue by Derkuleen** [citadel-station/citadel-main#7842]
[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:) **on citadel server**
[Round ID]: # (**INCLUDE THE ROUND ID**) **15625**
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.) **likely not related to any merges**

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) **not yet reproduced**

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.) **was using buildmode map gen running the lavland river. i loaded a small area of lavaland in a square, about a 10x10 or less. I followed by another larger box perhaps 15x15 or 20x20 that went over the previous area (trying to enlarge it) server immediately soft crashed where players were able to type IC and OOC but  unable to move.**

**Comment by Poojawa** [comment]
don't attempt world gen on a live server? test in private first
