### ISSUE TITLE
[Balance] Rod of Ascleius OP?

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#7906]
Rod of Asclepius seems really overpowered for what it does. The caveat is that it gives you the pacifist trait, but as a non-antag, that hardly matters when you can just heal everyone. The downside, seemingly, is that you ash when you die, but how often is that going to happen when you're literally immortal.

Item was added to the lavaland loot table in  #5892

Thoughts?

**Comment by Trilbyspaceclone** [comment]
If you in ANY way loose the rod you get dusted, so if a antag needs you dead, cut off arm with a knife and die. Or force drop the rod*

**Comment by RMagnum** [comment]
Rod is fine as it is, you can just get singled out, and it's rare loot from lavaland, it's ment to be strong pretty sure. I don't see a need for change, since pacifism is a huge downside, AND you dont have access to an arm.

**Comment by CdrCross** [comment]
Also, it renders one of your two hands useless for anything but the rod. I think it has enough counterplay to not be OP.
