### ISSUE TITLE
botany trays changing color

### ISSUE THREAD

**Issue by lordheichou** [citadel-station/citadel-main#796]
using ambrosia gaia on a tray in botany turns it orange so it doesnt need water or nutrients anymore.
i planted something and the tray turned blue again, which is default and normal. the tray retained its use. when the plant is harvested, the tray stays blue.

**Comment by Poojawa** [comment]
Is this issue still occurring?

**Comment by Poojawa** [comment]
Don't think it is, if it hadn't already been put into the various fixes as of late.
