### ISSUE TITLE
Occupation preferences default to assistant

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#7965]
Issue reported from  Round ID: 16121 (Citadel Station 13)

Reporting client version: 512

Set my jobs to medium with the preference to return to lobby if unavailable.
Round begins with myself as an assistant, and the chosen job completely unpopulated.

Really rustles my jimmies.

**Comment by Poojawa** [comment]
Is this a reoccurring bug or is it rarely or just once?

It may have been that you were attempted for an antag position but were denied
