### ISSUE TITLE
Character Creation Window Issues.

### ISSUE THREAD

**Issue by NotReallyHo** [citadel-station/citadel-main#8]
The character creation window doesn't seem to include everything the player selects. Lizard snouts don't appear to be working either and character markings don't update as well. The wing section seems a bit useless as none of them appear to be working either.

**Comment by LetterJay** [comment]
Lizard mutant parts are disabled until everything else is put in or someone else gets it to work the races.dm

Wings are also not yet implemented, so nothing will show until the correct sprite/code is added.

**Comment by TalkingCactus** [comment]
Fixed in #14

**Comment by Zeldazackman** [comment]
>Tfw not even sure if the person that opened the issue plays ss13 anymore since it's been years 🥇
