### ISSUE TITLE
player sent to title screen after genetics crashed their game

### ISSUE THREAD

**Issue by Derkuleen** [citadel-station/citadel-main#8036]
Issue reported from  Round ID: 16450 (Citadel Station 13)

Reporting client version: 512

Reply PM from-Lolzalolka/(Chris Bloise): I was in the process of cloning, suddenly my body presumably exploded.#My game froze up and I had to restart it. After I entered the game again, the title screen showed up and I was presented with the option to "Join game". #I could pick any job despite the fact that I was already in the round beforehand. 

Player was in cloning and something caused them to "explode" crashing their game and sending them to title screen. 
antags of the round: ninja, ling, traitor. only ninja was near medbay at the time. 
their body was still in medbay when they rejoined and their character was still set to wanted even when they rejoined.

**Comment by Poojawa** [comment]
somehow their ghost was deleted, damnifino

**Comment by Arturlang** [comment]
Still a thing, might be a runtime? If only a admin could post runtime logs.

**Comment by Ghommie** [comment]
Should have been fixed now that it uses transfer_ckey().
