### ISSUE TITLE
Burning slime extract with green slime cores not working.

### ISSUE THREAD

**Issue by IrkallaEpsilon** [citadel-station/citadel-main#8077]
[Round ID]: # 16559

[Testmerges]: -
[Reproduction]: Go do Xenobiology, get an adult orange slime. Get green slimeextracts, 10 in total. Feed adult orange slime green extracts. Be amazed that you dont get an armblade extract but rather nothing and wasted 15 mins getting everything set up. The extract is in the code yet it fails to spawn it seems. Why is this bad? Its in the code. its not working. Its dissappointing that it doesnt work.

[For Admins]: -

**Comment by IrkallaEpsilon** [comment]
I am dumb. Did it the wrong way.

**Comment by SkullyRoberts** [comment]
No you aren't. The wiki page is confusing.
