### ISSUE TITLE
Inventory glitch?

### ISSUE THREAD

**Issue by Keilara** [citadel-station/citadel-main#81]
[Note]: # 
![citadel station 13 2016-11-29 111646](https://cloud.githubusercontent.com/assets/24250718/20714074/5a008304-b625-11e6-9b9f-98dd73d3e1cc.png)
I found a glitch earlier while I was clearing space vines, when I got smothered by them and my vision was blinded I somehow lost my entire inventory hud, so I reconnected and my inventory was all missing, untill I moused clicked over it most of it came back but what has to be clicked dragged is permamently stuck on me and unable to be removed. Reconnecting doesn't seem to fix the issue.

**Comment by TalkingCactus** [comment]
1. What type of vines were they?
2. What version of BYOND are you using?

**Comment by Keilara** [comment]
1. Green space vines.
2. 5.0 Public Version 510. 1347

**Comment by TalkingCactus** [comment]
Do you know if the vines had any mutations though?

**Comment by Keilara** [comment]
They seemed like the standard green ones, we got to them before they mutated, I was clicking about a lot as well with a welder, till I got engulfed by vines and my hud vanished.

**Comment by Keilara** [comment]
Should I have someone else try to strip me to see if it fixes it?

**Comment by TalkingCactus** [comment]
That'll fix it, yes.

**Comment by TalkingCactus** [comment]
This issue is also in the wrong repository, please post it [here](https://github.com/Citadel-Station-13/Citadel-Station-13-5th-Port/issues) for further assistance.
