### ISSUE TITLE
MMI problems with mech

### ISSUE THREAD

**Issue by SpiritLongstien** [citadel-station/citadel-main#8136]
Issue reported from  Round ID: 16760 (Citadel Station 13)

Reporting client version: 512

[Testmerges]: N/A

[Reproduction]: When turned into an MMI and placed into an Odysseus, The MMI can use the lighting, strafing, View stats (and all the menu in it), Internal tank usage, but is unable to use the mechs equipment, however able to swap between the equipment

**Comment by Poojawa** [comment]
well known issue from upstream

**Comment by SandPoot** [comment]
did you check if you gotta do it like the AI and middle click?
