### ISSUE TITLE
"Genitals use skintone" preference appears to lack a SQL hook.

### ISSUE THREAD

**Issue by fludd12** [citadel-station/citadel-main#814]
I have set it and saved it repeatedly, but the preference gets reverted between rounds.

**Comment by LetterJay** [comment]
These don't use SQL.

**Comment by fludd12** [comment]
I figured they were *supposed* to, though, which was my point.

**Comment by Poojawa** [comment]
It's just missing a tag in the save file.

these is actually resolved if I ever figure out SQL. lol
