### ISSUE TITLE
 "Family Heirloom" trait item as Assistant can not be stored in backpack

### ISSUE THREAD

**Issue by CalamaBanana** [citadel-station/citadel-main#8281]
[Reproduction]:  Spawn as assistant with the family heirloom trait

The Family Heirloom trait gives you a small item you have to keep on your person. Some jobs have job specific items, which is nice flavor. But the assistant item got modified recently, it is an empty toolbox that could previously fit in the backpack. It no longer does, making it nearly impossible to keep your heirloom safe as assistant.

Proposed solution: If you don't like them having an empty toolbox that fits in their backpack, just have assistants roll from the generic heirloom item list, as s o many other jobs already do.

**Comment by davidchan13** [comment]
Toolbox fits the theme the best but something like a heirloom gas mask would also work.

Edit: In retrospect, why isn't the Assistant Heirloom a tattered grey jumpsuit?
