### ISSUE TITLE
Cogscarab shells are visible as ghost role to latejoiners, giving away the round type

### ISSUE THREAD

**Issue by CalamaBanana** [citadel-station/citadel-main#8297]
![grafik](https://user-images.githubusercontent.com/46299792/56848195-605d3a00-68e6-11e9-83ad-edd8438fe07d.png)

Attentive late joiners instantly know it's clockwork cult if a shell is around.

**Comment by Useroth** [comment]
Bring back the non-antag cogscarab ghost role that's just for building and it will be impossible to meta.

**Comment by davidchan13** [comment]
Even better, when you click to join as a cogscarab it won't let you join, it just refreshes the late join screen. You still need to ghost and go into the spawner tab to play as one.
