### ISSUE TITLE
At least one borg module can be recovered from cryo storage, and glues itself to your hand.

### ISSUE THREAD

**Issue by SectoidDan** [citadel-station/citadel-main#8304]
[Round ID]: #17226

[Reproduction]: Earlier in the round, an engineering borg entered cryo storage. Later on, while checking the items in cryo storage, I noticed Station Schematics listed there. As I was the CE, I thought that unusual, and recovered the item and picked it up. It was of course the cyborg module, and it worked as usual in my hand, but I couldn't drop it, throw it, or put it into any container and eventually required admin assistance to remove it.

I don't know if it was the active module or just one that happened to be in one of the borg's "hands". No other items were in cryo storage. On being made to drop-all via VV, the schematics disappeared.

**Comment by Trilbyspaceclone** [comment]
#8345 thx

**Comment by Ghommie** [comment]
Should have been fixed in #9410.
