### ISSUE TITLE
The [F] follow of a Mentorhelp observes the target instead of orbiting like other instances of [F]

### ISSUE THREAD

**Issue by MimicFaux** [citadel-station/citadel-main#8339]
Issue reported from  Round ID: 17376 (Citadel Station 13)

Reporting client version: 512

[Round ID]: # 17376

[Reproduction]: # As a ghost, select the [F] of an incoming mentorhelp.

**Comment by Poojawa** [comment]
Intended.  Observation allows you to see the target's hud and inventory.

**Comment by Useroth** [comment]
Also, it's meant to not allow every mentor to aghost when someone mhelps.
I think the easiest solution would be to add a button for "cancel camera view" on the top of the screen, when you use the mentorhelp follow.

**Comment by Arturlang** [comment]
It doesnt allow you to see hud or inventory, only making you see their mob, sadly
