### ISSUE TITLE
Station Alert and Atmospheric Alert consoles do not turn orange/red anymore.

### ISSUE THREAD

**Issue by CalamaBanana** [citadel-station/citadel-main#8441]
For some reason, both those consoles now have an issue with not properly displaying the correct overlay.

When testing, the update_icon functions get called, debug messages I added right below add_overlay("alert:2") would be displayed. Directly setting the alert:2 as default icon_screen works as well, so it's not an icon issue either. Not sure what's broken all of a sudden, doesn't look like anyone touched that stuff. Weird.

**Comment by Poojawa** [comment]
Byond version?

**Comment by CalamaBanana** [comment]
I am on 512.1467.  This is how it looks on main:

![grafik](https://user-images.githubusercontent.com/46299792/58413819-003eec80-807a-11e9-9e14-7d75457145bf.png)

Doesn't seem to be a local problem, everyone I talked to confirmed they see "green" only, too.

**Comment by Poojawa** [comment]
hmm. I'll look into it
