### ISSUE TITLE
HoS skirt sprite isn't displayed on characters.

### ISSUE THREAD

**Issue by UntoldTactics** [citadel-station/citadel-main#8509]
Happens in multiple rounds (constant)

[Reproduction] Pretty simple, the sprite for in-hand and on floor HoS skirt exists, but when you put it on,  you are instead naked, and a "ERROR" is displayed just next to your character.

**Comment by Poojawa** [comment]
Need more information, Digitgrade legs? regular?

**Comment by UntoldTactics** [comment]
Normal legs, and well heres a picture. http://prntscr.com/nz4fp6

**Comment by Poojawa** [comment]
That's the formal skirt, not the other. but should be an easy fix

**Comment by UntoldTactics** [comment]
Theres another HoS Skirt? :thinking:

**Comment by Poojawa** [comment]
the one literally in your inventory at the same time, nerd.

**Comment by UntoldTactics** [comment]
> the one literally in your inventory at the same time, nerd.

Thats the normal security officer skirt, not HoS skirt.

**Comment by Michiyamenotehifunana** [comment]
This seems to be the one I made from a kitbash of the Formal uniform and the Miku skirt. I bet this is because of the deprecation of whatever var we had used before `alternate_worn_icon` came along. Should be a simple enough fix if that's the case.

**Comment by Ghommie** [comment]
This should have been fixed on #8970 by replacing the older HoS skirt (it was a little ugly, to be honest) with the new one from tgstation (which can not be adjusted to be worn casually yet). I even searched for said missing old uniform in uniform.dmi to confirm it.
