### ISSUE TITLE
Random server reconnects

### ISSUE THREAD

**Issue by Atrocious-Augur** [citadel-station/citadel-main#8519]
[Round ID]: # 17671
For the last few weeks I've played (Seems like since the server was switched from low-power mode?) I'll sometimes have a random server reconnect. The game will pause, all sound will stop, almost like a crash, before popping up seconds later. I'm getting really sick of it because if it happens at a bad time, I'm just dead, and there's nothing I can do about it.

I have an ethernet cable connected to my PC, and don't really ever had internet connectivity issues on my side. But honestly with how quick is reconnects, I'm not even sure if it's a connectivity issue.

[Reproduction]: There seems to be no correspondence between how many people are on the server and how often or if at all I get this issue. No particular things I do cause the reconnect to happen either.

![image](https://user-images.githubusercontent.com/51285309/58783585-1aa32980-8596-11e9-8423-52bfa8976000.png)

**Comment by Poojawa** [comment]
does this happen on other servers or just here? 

Do you have changed FPS settings? What's your parallax setting at?

**Comment by Atrocious-Augur** [comment]
Putting this here since I forgot -- I tried playing on BD before, seems like I didn't have any problems besides normal slowdown (no complete loss of control through reconnecting). I play with my FPS on 40, and was on fancy parallax but turned it down to see if that was an issue, and it wasn't. Not sure what to do about it, I can't replicate any specific situations that cause a reconnect.

**Comment by Ghommie** [comment]
I don't think this has really anything to do with the code or repository but bad server internet connection and reachability issues amongst other things, not even a byond issue.
And as thus, this shall be closed. But worry not, because we totally aknowledge (and bitch about) these sort of issues. Everyday.
