### ISSUE TITLE
Simplemobs still vore people instead of attacking

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#8542]
**[Round ID]:** # 17707

**[Reproduction]:** Be a gorilla, attempt to attack someone. This bug happens even if vore prefs are off (it tried to make me vore myself and I have prefs set to off)

**Comment by Ghommie** [comment]
@Poojawa.
Even though I'm confident people may have pinged you already, your task.

**Comment by Poojawa** [comment]
Can't reproduce.


![](https://i.gyazo.com/bac6d84075a0c476315492d9499ab344.png)

**Comment by ghost** [comment]
it seems somewhat inconsistent, usually you hit people normally but sometimes it tries to eat them instead.
