### ISSUE TITLE
fire extinguishers cant be emptied

### ISSUE THREAD

**Issue by xxxnoscopexx** [citadel-station/citadel-main#8577]
Issue reported from  Round ID: 17736 (Citadel Station 13)

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Ghommie** [comment]
#8093 👏 didn't 👏 update 👏 its 👏 description.
Sad nerf to rightful robusting.

**Comment by xxxnoscopexx** [comment]
A sad day indeed
