### ISSUE TITLE
Deconstructing and reconstructing roundstart chem dispensers resets charge to 100%

### ISSUE THREAD

**Issue by Sishen1542** [citadel-station/citadel-main#8613]
As said above, if you spend all charge in a dispenser and deconstruct it, the 10MJ high cap power cell will be at 100% charge still which allows you to slap it back in for 1000 units of chemical goodness. Does not work with anything but the cells the dispensers start with.

![](http://puu.sh/DE5H9/3b5fc91fdd.png)

**Comment by Ghommie** [comment]
#8101 was going to update and thus fix this, but went closed.
oh well.
Edit: No wait, actually it wasn't.

**Comment by Sishen1542** [comment]
> #8101 was going to update and thus fix this, but went closed.
> oh well.
> Edit: No wait, actually it wasn't.

All good, thanks for the quick fix bud.
