### ISSUE TITLE
Seed vault spawn tweaks aren't all working

### ISSUE THREAD

**Issue by dapnee** [citadel-station/citadel-main#8647]
#8391 Added in an autolathe to the seed vault, issue with that is: It's VAR edited to be hacked already (which doesn't work, having to cut/mend/cut the contraband wire for it to show contraband items), and the plant DNA disk blueprint doesn't actually install on the autolathe (which I doubt you really need more disks then you start with, but it's thoughtful).

**Comment by davidchan13** [comment]
Despite #8674, this is still broken.

**Comment by Ghommie** [comment]
Design was fixed a while ago.
