### ISSUE TITLE
2 bugs I found

### ISSUE THREAD

**Issue by EverothB** [citadel-station/citadel-main#8680]
Hello, im new to posting information here, so here is my best take. 

1)Mining satchel: When you begin a round and the satchel is on your back, it can pick up ores and store on the box without a problem. If the satchel is taken out, then placed again in the bag, it will not pick up and store again. I am not sure if its required to have on the pocket for it to work normally and it working on the bag is a bug. Or if the bug here is it not working once it is pulled out and then placed in. This works in any round.

2) With the nudity permit you get a red text that sais suit right next to your character. I am not sure if anyone else but the user can see this.
![permit](https://user-images.githubusercontent.com/51928993/59631344-2d2c6f80-910d-11e9-99c4-789323695605.png)

**Comment by Ghommie** [comment]
1) the mining satchel working inside the backpack is perhaps the bug.
2) easy peasy non-existant icon state for the "uniform" overlay.

**Comment by EverothB** [comment]
Just hope this helps
