### ISSUE TITLE
Shoving on diagonal tables can go through windows

### ISSUE THREAD

**Issue by Linzolle** [citadel-station/citadel-main#8705]
## Testmerges:
The following pull requests are currently test merged: 
#8512: '[WIP] Megafauna anti-cheese, new killer tomato strain, ashstorm cleaning. V2' by Useroth at commit 133db8986f 
#8016: 'Experimental lagfix: Reducing GC allowance time from 2 minutes to 10 seconds' by kevinz000 at commit a9abd9c7b8 
#8607: 'Created the Doomball. A dodgeball that gibs anyone hit with it, or the thrower if caught. Also a possibly functional gamemode where everyone has doomballs and hijack objectives.' by SkullyRoberts at commit a9a0c22579 
#8415: 'Adds a sprint buffer - 35 tiles, regen 2 tiles/second (always active), 0.3 stamcost per tile if empty (as old) directly applied to staminaloss rather than stamina action buffer (unlike old)' by kevinz000 at commit 7fd50ffc95 

## Reproduction:
Arranging tables in this way allows two people to work together to shove one of them through a sliding windows by having one stand on the table, and the other to shove them diagonally through the window.
![dreamseeker_2019-06-20_16-53-21](https://user-images.githubusercontent.com/18472207/59884098-bd391600-93a6-11e9-8ffb-38219caeca4f.png)
![dreamseeker_2019-06-20_16-53-26](https://user-images.githubusercontent.com/18472207/59884157-e6f23d00-93a6-11e9-9d0d-8b2dd526e6c7.png)

**Comment by ghost** [comment]
this works even if you don't have the access to the windoor, just in case anyone is wondering.
