### ISSUE TITLE
Tech-Disks dont sell

### ISSUE THREAD

**Issue by Trilbyspaceclone** [citadel-station/citadel-main#8723]
## Round ID:
17911
## Reproduction:

Do toxins, get a ton of tech nodes, load them on a disk, scan them with the export gun.
Fine out it dosn't cell for anything, cry as you wanted to be a good cat that makes money for a fancy pen crate

**Comment by Ghommie** [comment]
Kevinz killed off cargo money generation through tech nodes long, long time ago. It shouldn't be a bug unless he says so.
