### ISSUE TITLE
Flashes impact my character while wearing sunglasses.

### ISSUE THREAD

**Issue by Tupinambis** [citadel-station/citadel-main#8746]
For whatever reason, I can get flashed while wearing sunglasses, which is most likely a bug.
On a related note, I also received the blinding effect while welding with my welding helmet down.

Issue reported from  Round ID: 17952 (Citadel Station 13)

Reporting client version: 512

**Comment by Ghommie** [comment]
Any particular testmerge happening during that round?

Also did you only receive the blinding temporary overlay? or also the eye damage/confusion effects?

**Comment by Trilbyspaceclone** [comment]
moffs have a -1 to eye protection
not a bug if your a bug iirc
