### ISSUE TITLE
Dressers do not allow you to change underclothes.

### ISSUE THREAD

**Issue by gambobombuski** [citadel-station/citadel-main#8803]
## Round ID: 
#18021

## Testmerges:
8356, 8748, 8415, 8016, 8512 (Ones currently active.)

## Reproduction:

Start with a nude character. Click on the wardrobe and select any item. It will complete the cycle like normal, but will then not apply the changes selected.

I've tried this with a character that has default nude to all of the dresser items and to a character that has underclothes and the dresser fails to modify their outfits.

This bug DOES NOT occur when using Mirrors.

**Comment by Ghommie** [comment]
From what I know, there is a badcode option to hide underwear around the code. I personally haven't tried it personally, but did you make sure you said option wasn't on beforehand?

Regardless, I'll have to check on it later myself, since I am making a minor refactor of underwear anyway.
