### ISSUE TITLE
Warp Whistle deletes your sprite permanently, making you invincible to everything except ranged attacks.

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#8859]
## Round ID:
18160

## Testmerges:
#8855 #8356 #8836 #8415 #8838 

## Reproduction:
Use warp whistle. May or may not involve having Sleepy Carp (which I doubt).

**Comment by Poojawa** [comment]
https://github.com/tgstation/tgstation/pull/37077

**Comment by EgoSumStultus** [comment]
Fixed by #8917

**Comment by Trilbyspaceclone** [comment]
This is now fixed iirc
