### ISSUE TITLE
Cryo Tubes are Sometimes Slow to Inject Chemicals

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#8951]
## Round ID:
N/A

## Testmerges:
The following pull requests are currently test merged:
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#8838: 'You can now eat dead headslugs.' by BlackMajor at commit cb65964ff6
#8856: 'Security Gun Rebalancing Electric Boogaloo - overhauls magrifles/magpistols, burst fire autorifles, nerfs laser carbines, resprites energy guns' by kevinz000 at commit 28072a31dc
#8356: '[READY] FermiChem! Adds a new reaction mechanic, 9 new chems and a few extra features to accommodate the new chems.' by Thalpy at commit 15ab1a26a4
#8930: 'Fixes nanite viruses take two' by kevinz000 at commit 94f5573e3a

## Reproduction:

Unsure how to reproduce it consistently, but working medical, I've had repeated cases where the patient has been placed in a cryo tube that stays activated for a long period of time before chemicals from the beaker are injected.  This often necessitates workarounds like opening the tube to feed the patient a sip of the beaker to ensure they begin healing in a reasonable amount of time.

**Comment by Owai-Seek** [comment]
I've been told that this is possibly lag in the atmos system but would like to confirm (as a person who often works medical) that this happens fairly often. It can result in someone being stuck in cryo for an excessive amount of time until someone checks on them (assuming anyone actually DOES check on them.)

**Comment by Trilbyspaceclone** [comment]
Were they wareing any suits that were unable to be injected thought?

**Comment by Owai-Seek** [comment]
I have had people fresh from cloning put in the tube, sometimes it just doesn't push the chems in and you have to spoonfeed them from the beaker. Once they have some Cryoxadone in them the cryo tube will begin pushing more in and function normally.

**Comment by IronEleven** [comment]
Okay one detail I was able to discern, when it happens, it seems to affect cryo globally.  Multiple patients were not receiving chemicals in both tubes last round (round ID 18624)

**Comment by PersianXerxes** [comment]
Hopefully #11032 addresses this?
