### ISSUE TITLE
Shoving someone onto a dense object on the same tile as a table slides them on top of the dense object.

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#8973]
## Round ID:
18384

## Reproduction:
make table. put dense object on top. shove person adjacent to tabled object into tabled object. they slide onto the table.
example: build table frame. build wall girder. finish both. shove player into table/wall.
this counts for shutters as well, so R&D shutters are useless because you can shove into them.

**Comment by Ghommie** [comment]
This doesn't apply to climbing onto the table, right?
