### ISSUE TITLE
Vial's can't transfer out and pills don't fill up bottles in the chemmaster

### ISSUE THREAD

**Issue by dapnee** [citadel-station/citadel-main#8975]
As of round 18390 and possibly a bit longer, chemistry's been a bit borked. Hypovials can not transfer into other containers, but other containers can transfer into hypovials. Along with this, the chemmaster, when loaded with a pill bottle, does not fill the bottle with pills on creation, just dumping them out as they would normally without a pill bottle.

**Comment by Ghommie** [comment]
The latter issue has been actually around for very long (even on tg), but seemengly I forgot about it as I stopped trying to load pill bottles uselessly.
Nevertheless, thanks for the bug report, I'll be looking into it.
