### ISSUE TITLE
Other Maps Don't Have 'unique' Cargo

### ISSUE THREAD

**Issue by MrBobCool** [citadel-station/citadel-main#8981]
Issue reported from  Round ID: 18398 (Citadel Station 13)

Reporting client version: 512

It's simple, other maps then Pubbystation (if I remember) don't have 'unique' crates. Like 'lewd' crates for example.

**Comment by Ghommie** [comment]
Uh, could you be more specific about it? I don't understand what you are referring to.

**Comment by MrBobCool** [comment]
Nevermind. I'm just a small brainer.
