### ISSUE TITLE
Downward facing sprites for Tajarn are larger than others.

### ISSUE THREAD

**Issue by Brimcon** [citadel-station/citadel-main#9]
Picture related, also left/right is bigger at the feet oddly.
![image](https://cloud.githubusercontent.com/assets/7198283/17565928/4197c7de-5eee-11e6-991f-ca4e248b42dc.png)

**Comment by TalkingCactus** [comment]
Does this happen in-game, too? Or is it just in the preview?

**Comment by Brimcon** [comment]
In game as well.
![image](https://cloud.githubusercontent.com/assets/7198283/17566580/df0187f6-5ef0-11e6-9ce7-1952b6ae34a9.png)

**Comment by Brimcon** [comment]
Update on Tajarn sprite issue for your reference 
![image](https://cloud.githubusercontent.com/assets/7198283/17568587/51f8d572-5ef9-11e6-8ae5-ea7ac1fa9333.png)

**Comment by TalkingCactus** [comment]
Fixed on my end, will be in the next update.
