### ISSUE TITLE
Quirks deleting every time?

### ISSUE THREAD

**Issue by YakumoChen** [citadel-station/citadel-main#9023]
As an engineer or a miner I couldn't take harmless quirks like "sleepy", it ended up just deleting all my quirks except the neutral ones. Is the banned quirk list too harsh or just shitcode?

**Comment by Ghommie** [comment]
@kevinz000, You may want to double check your quirks filtering.

**Comment by IronEleven** [comment]
In my experience the message displays every round but the quirks are still there.

**Comment by EmeraldSundisk** [comment]
Does it specifically state which quirks are removed? I've seen a message come up when playing certain roles but don't recall it naming any specific quirks (or removing any of them).

**Comment by YakumoChen** [comment]
I believe it did when I played roles like engineer (or maybe security) but not as miner.

**Comment by ghost** [comment]
close on god
