### ISSUE TITLE
Standard Surgical Tools Do Not Work On Organ Manipulation If Another Surgery is Open on Another Body Part

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9028]
## Round ID:
18470

## Testmerges:
#8356: '[READY] FermiChem! Adds a new reaction mechanic, 9 new chems and a few extra features to accommodate the new chems.' by Thalpy at commit a9330b784a
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#8930: 'Fixes nanite viruses take two' by kevinz000 at commit 94f5573e3a
#8927: 'Tones down some items attack stamina costs. kills hypereutactic blades copypasta.' by Ghommie at commit 6c712a6931
#8856: 'Security Gun Rebalancing Electric Boogaloo - overhauls magrifles/magpistols, burst fire autorifles, nerfs laser carbines, resprites energy guns' by kevinz000 at commit 28072a31dc
#8838: 'You can now eat dead headslugs.' by BlackMajor at commit cb65964ff6
#8848: 'Trait blacklisting system: Blacklists Mute and Brain Tumor from ALL heads of staff. Blacklists pacifist + paraplegic from HoS. Blacklists Paraplegic/nolegs from CE. Blacklists phanosthing/no-recognize-faces from HoP' by kevinz000 at commit 175b69e868

## Reproduction:
The miner retrieved a non-player Ashwalker corpse that was previously a legion host.  I began removing its organs for a bounty.  Emptying the groin of organs worked fine, but once I began the chest organ manipulation, standard surgical tools would not work and every step required a ghetto tool substitute.

**Comment by Ghommie** [comment]
Mmmh, while I assume you already know chest/head organ manipulations steps differ slighty from the rest of the body, and that keeping different surgeries on a body has some issues already last I checked.
Did you also make sure this was not the case for other bodies you attempted this on?

**Comment by YakumoChen** [comment]
did you make sure to end the first surgery? you can only do one surgery at a time

**Comment by IronEleven** [comment]
I didn't know about the multiple surgeries, that seems to be the cause.  Odd that ghetto tools work and regular ones don't though.

**Comment by Poojawa** [comment]
So I'm not actually crazy, since pacifist character couldn't use regular tools, but ghetto ones were fine

**Comment by IronEleven** [comment]
The character in question was not a pacifist.

**Comment by Poojawa** [comment]
Something's just fucky with surgery tools then.

**Comment by ghost** [comment]
daily reminder you can do multiple surgeries at once


talking to you robotics mains
