### ISSUE TITLE
Personal AI Deleted When Riding the Head of a Player Transformed Into a Monkey

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9059]
## Round ID:
18537 

## Testmerges:
#9055: '[TESTMERGE ONLY] Revert "Makes staminaloss also apply the oxyloss fullscreen overlay."' by kevinz000 at commit 07c5844645
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#8930: 'Fixes nanite viruses take two' by kevinz000 at commit 94f5573e3a
#8838: 'You can now eat dead headslugs.' by BlackMajor at commit cb65964ff6
#8848: 'Trait blacklisting system: Blacklists Mute and Brain Tumor from ALL heads of staff. Blacklists pacifist + paraplegic from HoS. Blacklists Paraplegic/nolegs from CE. Blacklists phanosthing/no-recognize-faces from HoP' by kevinz000 at commit 175b69e868
#8356: '[READY] FermiChem! Adds a new reaction mechanic, 9 new chems and a few extra features to accommodate the new chems.' by Thalpy at commit 5795f6bbe2

## Reproduction:
Personal AI was using a rabbit hologram and riding on my head.  I turned myself into a monkey using a DNA injector.  The Personal AI was nowhere to be found following my transformation.

**Comment by Poojawa** [comment]
w-

what.

how does...

**Comment by Ghommie** [comment]
Fucking magic.
