### ISSUE TITLE
Health scanners do not show messages when scanning someone that is missing organs

### ISSUE THREAD

**Issue by dapnee** [citadel-station/citadel-main#9091]
I’ve noticed this twice now, few days apart from each other. The first time, I was a Viro and my lungs popped thanks to lack of air. I was going to see if it showed up as being an issue on my advanced health scanner so I could show it to others as I mimed, but only received a “Lexia Wardle has used the advanced health scanner on herself.” message and no other read outs on my health. I gave the scanner to another player and they had the same issue. Yesterday a coworker lost their tongue and again, the scanner wouldn’t return a message reading their health.

**Comment by Sishen1542** [comment]
@Thalpy

**Comment by Thalpy** [comment]
Was this when PoojBlood was merged? because that was an issue, otherwise, I'll double check the scanner code!

**Comment by Thalpy** [comment]
Oh wait, a few days, hmm. Yeah it's probably me then. I'm on the case!

**Comment by Thalpy** [comment]
Okay, I think the problem was using getorganslot() on a mob/living, instead of mob/living/carbon/human. So it should be fixed now. If you get anything like this again (after server is updated) let me know, and if possible link the round ID so I can check runtimes.

**Comment by Thalpy** [comment]
(And thank you very much for reporting this!!)

**Comment by Thalpy** [comment]
Okay I actually fixed it, I mislabeled Lung as L.

**Comment by Sishen1542** [comment]
thanks for the quick work fermi :+1:
