### ISSUE TITLE
Antimatter engine controller cannot be interacted with.

### ISSUE THREAD

**Issue by lolman360** [citadel-station/citadel-main#9128]
[Round ID]: 18654

## Testmerges:
#9038: 'Fixes/tweaks jump boots' by kevinz000 at commit 1c1ca84c3a
#9055: '[TESTMERGE ONLY] Revert "Makes staminaloss also apply the oxyloss fullscreen overlay."' by kevinz000 at commit 07c5844645
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#8930: 'Fixes nanite viruses take two' by kevinz000 at commit 94f5573e3a
#8848: 'Trait blacklisting system: Blacklists Mute and Brain Tumor from ALL heads of staff. Blacklists pacifist + paraplegic from HoS. Blacklists Paraplegic/nolegs from CE. Blacklists phanosthing/no-recognize-faces from HoP' by kevinz000 at commit d6885d41a9
#9065: 'Makes femur breakers adminspawn only' by deathride58 at commit b2a77b272d
#9116: 'Changes beforeShuttleMove on airlock to addtimer(0) rather than InvokeAsync' by kevinz000 at commit 411e0cc2cc

## Reproduction:
Build an AM engine with parts ordered from cargo. Wrench down controller. Set up shielding. Insert fuel jar. Cry because you can't interact with it at all. Not even the AI can.

**Comment by Ghommie** [comment]
Haven't heard of this being still an issue in a while.
