### ISSUE TITLE
Free golems getting no mining points.

### ISSUE THREAD

**Issue by scarth64** [citadel-station/citadel-main#9129]
## Round ID:

18658

**Comment by scarth64** [comment]
Checked onstation as well, no points gained from the ORM there either

**Comment by Drakyle-The-Forgotten-Deity** [comment]
Are you clicking the ORM while holding the ores to deposit them? if so that would be why, to get points the ores need to be picked up by the ORM itself by either dragging the Ore Box over the collection point or emptying the ore onto the floor where the ORM is collecting from.
