### ISSUE TITLE
Syndicate borer spawners have no cooldown, no feedback for when pressed

### ISSUE THREAD

**Issue by cebutris** [citadel-station/citadel-main#914]
When you buy the syndicate borer spawner thingy, you activate it in your hand to send a message to the ghosts to join. But you don't get a message that it's doing anything, so you might be confused and think it's not working. So you press it again, still not getting any feedback. Meanwhile, in ghostchat, you get spammed with borer notifications nonstop because there is no cooldown, and the summoner doesn't know that they've actually activated it about a billion times

**Comment by Poojawa** [comment]
These are removed due to upstream's removal as well. the maintainer of this side fare hasn't updated it either.

**Comment by ktccd** [comment]
Sorry about that, but I've been putting it off for a while now, trying to merge the thing to TG.
Except then they went into a feature-freeze so I couldn't add them.
And then they removed them completely so now I gotta re-make borers completely if I want them again....
**Infinite headaches**

**Comment by ktccd** [comment]
ok, so I found PART of the problem:
My syndicate borer spawner is pretty much copy-paste stolen from the other antag spawner items, and all of them have this issue >_<.
EDIT:
I figured out how to fix it, but I'm having problems making git work so I can push it. Might take a while.
