### ISSUE TITLE
Strawberries and their plant are invisible.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9148]
Issue reported from  Round ID: 18712 (Citadel Station 13)

Reporting client version: 512

"pack of strawberrie seeds" produces an invisible plant and invisible food product.

To reproduce, literally just plant the seed in any tray and "watch" as your invisible plant grows.

**Comment by Trilbyspaceclone** [comment]
#9150 
Fix'es that, I cant spell basic things...
