### ISSUE TITLE
Various durathread shit has no sprite

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#9163]
## Round ID:
18740

## Reproduction:
grow durathread, be disappointed
durathread seeds are spriteless
raw durathread bundles (use durathread bundle in hand) is spriteless
durathread is spriteless

**Comment by ghost** [comment]
update: durathread helmet has no sprite, durathread armor is https://gyazo.com/f139af33561b5289c5f8e901abe7629f
aka totally fucked

**Comment by izzyinbox** [comment]
It has missing sprites for digitigrade legs too.
