### ISSUE TITLE
bone hurting blood

### ISSUE THREAD

**Issue by Linzolle** [citadel-station/citadel-main#9167]
## Testmerges: 
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#9074: 'Donator grouping system' by kevinz000 at commit cd36b9ab12
#9055: '[TESTMERGE ONLY] Revert "Makes staminaloss also apply the oxyloss fullscreen overlay."' by kevinz000 at commit 07c5844645
#9047: 'RGB Blood Reworks + Blood Replacement machine' by Poojawa at commit 7fef33160d

## Reproduction:
Draw blood from a lizard and inject it back into them. It will turn into bone hurting juice upon injection. Does not work when injected into containers. Very likely to be caused by #9047

**Comment by IronEleven** [comment]
I also noticed similar behavior with monkies

**Comment by Poojawa** [comment]
Fixed
