### ISSUE TITLE
IAA pinpointer is broken

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#9206]
Issue reported from  Round ID: 18855 (Citadel Station 13)

Reporting client version: 512

After my first target died, the second target's pinpointer was ???.  It also might've potentially been because my target removed their ID.

**Comment by Trilbyspaceclone** [comment]
Might have been off Z-level who/what job were they?

**Comment by Arturlang** [comment]
pinpointer doesnt seem to update for new targets

**Comment by keronshb** [comment]
This issue is over 2 years old and IAA is gone
