### ISSUE TITLE
Silver Core Luminescents Can Spawn "Oops"

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9215]
## Round ID:
18875

## Testmerges:
#9027: 'Job menu improvements Except maybe Kevin will merge it this time instead of a month later' by Poojawa at commit 1ba9d374fe
#9047: 'RGB Blood Reworks + Blood generator, Bleeding instead of blood deletion' by Poojawa at commit d7ec568efc
#9055: '[TESTMERGE ONLY] Revert "Makes staminaloss also apply the oxyloss fullscreen overlay."' by kevinz000 at commit 07c5844645
#9057: 'Adds the Male AI vox voice.' by EgoSumStultus at commit d9a6be301a
#9074: 'Donator grouping system' by kevinz000 at commit cd36b9ab12
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#9193: '[TESTMERGE ONLY FOR NOW] Disables crit_threshold changes through mood ' by kevinz000 at commit 1e6845491d

## Reproduction:
Selkie was a luminescent, using the silver slime extract to create food.  The following object resulted:

 That's an oops.

If you're reading this it means I messed up. This is related to moths eating clothes and I didn't know a better way to do it than making a new food object.

**Comment by nik707** [comment]
Fixed
