### ISSUE TITLE
Peach Seeds and Peaches have no sprite.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9225]
## Round ID:
n/a
## Reproduction:
Check the seed vendor, peach seed Icon is missing. Grab seed, no icon. Plant see, tree grows, peaches are invisible,

Peaches from PR #9146 

There is no icon for peaches/peach seeds, one needs to be made and added. (Please don't try to use the apple icon for peaches, it needs its own.) I'd suggest using the peach can icon as reference, or just making it bigger.

**Comment by Trilbyspaceclone** [comment]
This one is not my fault damn it
