### ISSUE TITLE
Peach Sprites not working correctly.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9233]
## Reproduction:
Check Vendor and harvest some peaches.

![image](https://user-images.githubusercontent.com/7543955/64136327-e589bb80-cdbe-11e9-90a5-315aaf98e2d3.png)

I'm sorry I keep reporting botany junk pfft.

**Comment by Trilbyspaceclone** [comment]
I added the sprites, called the peach... ect ect
