### ISSUE TITLE
Recycler Deleting All Clothing

### ISSUE THREAD

**Issue by MacaroniCritter** [citadel-station/citadel-main#9240]
Issue reported from  Round ID: 18965 (Citadel Station 13)

Reporting client version: 512

The Recycler, when having a person in a folded bluespace body bag go through it, will delete all items on said person however they will still appear on the person until a different clothing is put in there spot, additionally if any other individual attempts to remove any invisible items from the person they will disappear after interacting with outside of holding it.

**Comment by ghost** [comment]
how quirky...,,,,

**Comment by Poojawa** [comment]
Recycler code is so fucking awful.

**Comment by ghost** [comment]
^ close or die @Adelphon
