### ISSUE TITLE
Glass Sheets Cannot Be Inserted into the Ore Silo

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9244]
## Round ID:
18979

## Testmerges:
#9027: 'Job menu improvements Except maybe Kevin will merge it this time instead of a month later' by Poojawa at commit 1ba9d374fe
#8936: '[TESTMERGE ONLY] Temporarily reverts dark mode toggle PR' by deathride58 at commit 840135d8ab
#9193: '[TESTMERGE ONLY FOR NOW] Disables crit_threshold changes through mood ' by kevinz000 at commit 1e6845491d
#8017: 'IRV viewer for player rep, TESTMERGE ONLY - Right branch edition' by kevinz000 at commit 359a1214cc
#9243: 'Updates dogborg sprites and some.' by BlackMajor at commit fbc2d3c8fe

## Reproduction:
Attempt to insert glass sheets into the science protolathe, science circuit imprinter, or ore silo.  This was also reproduced locally with plasmaglass, reinforced plasmaglass, and r-glass.

**Comment by Trilbyspaceclone** [comment]
this was fixed, you can close it <3
