### ISSUE TITLE
Prey See All Nearby Orgasm Messages In Second Person (You)

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9299]
## Round ID:
19201

## Testmerges:
#9277: 'Adding Horn colors, Alternate Digi Leg framework, and species squash' by Poojawa at commit bf3d30c0e4
#9214: 'properly ports neovgre from hippie' by Sishen1542 at commit b98a5016b3
#9253: 'Doubles stamina regen when standing/laying down' by chefferz at commit d21a45cd53
#8937: 'darkmode/lightmode fixes and tweaks.' by Ghommie at commit c090c98118
#9234: '[WIP] [TEST-MERGE] Makes clock work reebe less laggy + addtions ' by Trilbyspaceclone at commit 7146cc6455
#9293: 'leftover legcuffs/handcuffs overlays fix.' by Ghommie at commit f3a5e2e321

## Reproduction:
Get vored, have someone climax near you while vored.  It will display "You climax" instead of "[Person] climaxes."

**Comment by Poojawa** [comment]
Was it the predator that did, or someone else nearby?

**Comment by IronEleven** [comment]
Someone else nearby

Edit: I am fairly sure the orgasms in question were triggered by masochism, if that helps reproduce the issue.

**Comment by Poojawa** [comment]
tbh, you shouldn't be seeing visible messages anyway, because blind. But it's just fucky code as is.

**Comment by Ghommie** [comment]
This is being fixed in #8948.

**Comment by IronEleven** [comment]
Closing since the fix was merged, I don't do vore enough to retest it personally, however.
