### ISSUE TITLE
Envy's Knife doesn't copy Digigrade Legs

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9345]
Issue reported from  Round ID: 19303 (Citadel Station 13)

Reporting client version: 512

What it says on the tin, Envy's knife doesn't copy digigrade legs now.

**Comment by Weblure** [comment]
Probably just needs a var name change somewhere in the code, after the leg update was merged. Who was the creator of that PR?

**Comment by Weblure** [comment]
Found em
@Poojawa Can you confirm if this is caused by #9277 ?

**Comment by Poojawa** [comment]
It does and it doesn't. 

Envy's knife doesn't actually transform persay because it's more of just copy/paste, rather than forcefully checking on_species_gain
