### ISSUE TITLE
"Save Chat Log" button does not work.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9346]
Issue reported from  Round ID: 19305 (Citadel Station 13)

Reporting client version: 512

I've used it before, don't know when it stopped working (but I've seen at least one other person mention it.) Clicking the Save Chat Log button does not open a window to save the current chatlog like it used to, it just does, well, nothing.

**Comment by Ghommie** [comment]
Ok, thanks for the report, it should be now fixed.

FYI anyway, for the time being the function will saves the logs independently from your chat palette preferences, meaning that even if you had the dark mode on the saved logs will display only with the default .css stylesheet.

My experience with js and the ajax function is basic at best and this peeve hasn't been probably solved elsewhere yet.
