### ISSUE TITLE
Ion Laws are listed above Law 0s

### ISSUE THREAD

**Issue by CdrCross** [citadel-station/citadel-main#9355]
The issue here is quite simple. Probably as an artefact from TG, AIs get Ion Laws listed above Law 0s. This is a problem because according to Silicon Policy (https://katlin.dog/citadel-rules/main#silicon-policy), Law 0s are a higher priority than Ion Laws. This leads to confusion and accidental rulebreaks, and should be fixed.

**Comment by jakeramsay007** [comment]
Non-reproducable in testing environment
