### ISSUE TITLE
MMI was unable to receive my mind and I was ghosted, was prompted to make bug report.

### ISSUE THREAD

**Issue by KathrinBailey** [citadel-station/citadel-main#9360]
## Round ID:
19364

## Reproduction:
I was doing some 'roleplay' in dorms when I heard a ticking, I went outside and found a syndicate bomb in maints. It was my first time encountering one and I was too panicked to read the chat, I just yelled "SYNDIE BOMB MAINT" and didn't look at the timer, I tried to just grab the bomb so I can move it. Anyway, I blew up, and I got this message:

**Oops! Something went very wrong, your MMI was unable to receive your mind. You have been ghosted. Please make a bug report so we can fix this bug.**

Unfortunately, I didn't think about the station/round time but I would guess it was around 1hr 40m round time. Here is a bunch of logs of around that time for Ctrl-F-ing the round logs to find the more precise moments:
https://pastebin.com/hmcYUA77

To actually reproduce:
Box Station, maintenance tunnel above dorms as Vale engi dogborg. A few tiles to the right of the furthest right cabin.
![image](https://user-images.githubusercontent.com/53862927/65736142-013c6500-e0d2-11e9-96df-da2beaaaefbf.png)
I RCDed the floor to deconstruct, I was one tile to the right of the bomb. The bomb (most likely) detonated by the timer running out. I was previously undamaged and only had ion thrusters upgrade. The bomb was screwed open.

**Comment by YakumoChen** [comment]
Explosion code is pretty ass, the explosion probably damaged the brain inside your mob

**Comment by Thalpy** [comment]
This happened before the tg organ port testmerge, so it couldn't have been that.
