### ISSUE TITLE
Can't be borged, Brain Dies as soon as its put in the MMI!

### ISSUE THREAD

**Issue by CaptainHooch** [citadel-station/citadel-main#9363]
## Testmerges:
BYOND Version: 512.1484
Server revision compiled on: 
The following pull requests are currently test merged:
#9191: 'Ports fireman carrying from /tg/' by Linzolle at commit 5ab224e20a
#9234: '[WIP] [TEST-MERGE] Makes clock work reebe less laggy + addtions ' by Trilbyspaceclone at commit 7146cc6455
#8937: 'darkmode/lightmode fixes and tweaks.' by Ghommie at commit 7d3003179b
#9214: 'properly ports neovgre from hippie' by Sishen1542 at commit b98a5016b3
#9309: '[READY][TESTMERGE] Ports TG's organ handling (with a few tweaks to make it fit).' by Thalpy at commit b622ea4fd2

**Comment by ghost** [comment]
@Thalpy maybe?

**Comment by YakumoChen** [comment]
Were they banned from cyborg?

Please do not use GoofSize text in issues.

**Comment by Thalpy** [comment]
It's highly likely it's me, I'm on the case!

**Comment by Thalpy** [comment]
It was me, should be fixed. Thank you for submitting the report and sorry if it ruined your round..!
