### ISSUE TITLE
AEGs don't emit radiation

### ISSUE THREAD

**Issue by PersianXerxes** [citadel-station/citadel-main#9378]
## Reproduction:
So over the course of several conversations on the Discord, several individuals including Snekmin (Snake Redtail), have mentioned that AEGs (printable at the Security lathe) are supposed to emit radiation as a downside for how powerful they are.
Several other members, including Emilia, then brought to light that this is not the case. A quick check on a test server seems to verify that AEGs do not, in fact, emit radiation and I have been told this is a bug.

Per Snekmin, I'm posting this report so the issue can be addressed, whether that means they're fixed or someone higher up steps in to state this was an intended buff to AEGs.

**Comment by davidchan13** [comment]
AEG rads were removed about the same time you could upgrade charges and move them about. Las guns were just outperforming AEGs when all of security could just wrench a table charger and drag it around.

**Comment by PersianXerxes** [comment]
That makes some sense, a lot of folks on the server seem to be unaware this was an intended change, then.
