### ISSUE TITLE
Infinite Spraypaint glitch

### ISSUE THREAD

**Issue by keronshb** [citadel-station/citadel-main#9395]
Issue reported from  Round ID: 19456 (Citadel Station 13)

Reporting client version: 512

I have no clue how I did this.  Here were the events leading up to it:

1) I accidentally spraypainted Sachi a few times in combat mode with a spraycan, I put it away in my backpack after he brought me to medbay to heal me.

2) I was spraying windows in regular mode and didn't notice that my spraycan was still spraying despite it saying "there's nothing left in the can!"

**Comment by ghost** [comment]
i'm pretty sure this is fixed
