### ISSUE TITLE
Horse Tail Disappears on Pat

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9425]
#9381: 'Ports the /tg/ anti_magic component and implements holymelon charges' by jakeramsay007 at commit 5ae76df5de 
#9197: 'The Syndicate Uplink Refresh. Balancing, New Items, and More! (Ready To Merge Edition)' by Tupinambis at commit daba5cc6cc 
#9234: '[WIP] [TEST-MERGE] Makes clock work reebe less laggy + addtions ' by Trilbyspaceclone at commit 7146cc6455 
#8937: 'darkmode/lightmode fixes and tweaks.' by Ghommie at commit 7d3003179b 
#9214: 'properly ports neovgre from hippie' by Sishen1542 at commit c9fb4cecbc 
#8894: 'T G F U S I O N' by kevinz000 at commit 6dff5246d4 
#9047: 'RGB Blood Reworks + Blood generator' by Poojawa at commit b589565398 

Issue reported from  Round ID: 19508 (Citadel Station 13)

Reporting client version: 512

Horse Tail disappears when it wags, patted Maria Parksons and their tail disappeared.

**Comment by Weblure** [comment]
The same thing happens with the axolotl tail

**Comment by Poojawa** [comment]
y'sure, because I can't reproduce
