### ISSUE TITLE
Head Rev status carries over to blob, possibly other ghost roles

### ISSUE THREAD

**Issue by PersianXerxes** [citadel-station/citadel-main#9455]
## Reproduction:
During a round on 10/9/2019 which ended around 5AM EST, a head revolutionary was executed and then took control of a blob that spawned. They retained their status as a head rev while being a blob.

If this bug affects other ghost roles, it could create the potential for a head rev to make a round that doesn't end without admin intervention.

**Comment by Ghommie** [comment]
A little issue with the TM'd #8615, now fixed, the watchdog only has to update the server.

**Comment by PersianXerxes** [comment]
I should probably wait for confirmation it was fixed, but... I'll forget. Closing this on Ghommie's word.
