### ISSUE TITLE
Sprite Issues (Oh no, my Privates)

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9495]
Issue reported from  Round ID: 19637 (Citadel Station 13)

Reporting client version: 512

Hand clips through Hemi and Knotted Hemi sprites on pretty much every species on the list. There's basically a line just clipping right through em. (Layering issue with hands)

I've also seen some issues with an unerect tapered, at least on lizards. Specifically while rolling on the ground. (Layering issue with Satchel)

**Comment by Ghommie** [comment]
Could you provide some visual example of this layering issue on discord? Won't promise it'll be easy to fix.
