### ISSUE TITLE
CHECK_MULTIPLE_BITFIELDS doesn't work, I'm pretty sure.

### ISSUE THREAD

**Issue by Thalpy** [citadel-station/citadel-main#9497]
## Round ID: There is no round ID

Because I'm so hopping mad at this I'm making a bug report cause i can't figure it out and I _aaaaaaa_

## Reproduction:

CHECK_MULTIPLE_BITFIELDS(flag_var, flag1 | flag2 | flag3) Doesn't work and it causes me pointless grief trying to get it to work.

**Comment by Ghommie** [comment]
Oh yea, I just realized (again) that CHECK_MULTIPLE_BITFIELDS returns TRUE only if all the flags are found within the field. CHECK_BITFIELD(flags_var, flag1 | flag2 | flag3 | etc.) will work fine however.
It's pretty late, I had a brain fart and told you to do something that wasn't actually correct yesterday, Sorry Thalpy.

That said, this non-issue can be closed now now.

**Comment by Thalpy** [comment]
Ah heck
