### ISSUE TITLE
Another lighting bug

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#95]
**We're experiencing huge amounts of lag from runtimes in the lighting code.**

**Some ruins seem to not be updating their lighting in lavaland. It seems to affect the entire area of the ruin so it's not attached to any area related vars.**
![picture](http://image.prntscr.com/image/219263a54ffb47329ee85934128a4b18.png)

**Comment by PJB3005** [comment]
Bets are on a lack of change_area and changeTurf

**Comment by ghost** [comment]
This seems to happen on any randomly generated area like ruins and spacegen

**Comment by TalkingCactus** [comment]
@unusualcrow @PJB3005 We need lighting corrected soon or we'll be forced to revert the changes. I don't have the time to learn the lighting system and fix it in a reasonable amount of time.

**Comment by PJB3005** [comment]
If you can give me a pointer to where the ruin code is (because I couldn't for the life of me find it) I'll see what's up.

**Comment by LetterJay** [comment]
`runtime error: 
[00:53:32]Cannot read null.x
[00:53:32]proc name: recalc corner (/datum/light_source/proc/recalc_corner)
[00:53:32]  source file: lighting_source.dm,268`

This floods followed by a bad list runtime error until the server locks up.

@PJB3005

**Comment by PJB3005** [comment]
Stack trace?

**Comment by LetterJay** [comment]
```runtime error: 
[10:07:54]bad icon operation
[10:07:54]proc name: Blend (/icon/proc/Blend)
[10:07:54]  usr: Charlie Kirkson (/mob/living/carbon/human)
[10:07:54]  src: /icon (/icon)
[10:07:54]  usr.loc: the floor (118,167,1) (/turf/open/floor/plasteel/red/side)
[10:07:54]  call stack:
[10:07:54]/icon (/icon): Blend(/list (/list), 2, 1, 1)
[10:07:54]getFlatIcon( (/atom/movable/lighting_overlay), 2, 'icons/effects/lighting_overlay...', null, 4)
[10:07:54]the camera obscura (/obj/item/device/camera/spooky): camera get icon(/list (/list), Charlie Kirkson (/mob/living/carbon/human))
[10:07:54]the camera obscura (/obj/item/device/camera/spooky): captureimage(Charlie Kirkson (/mob/living/carbon/human), Charlie Kirkson (/mob/living/carbon/human), 1)
[10:07:54]the camera obscura (/obj/item/device/camera/spooky): afterattack(Charlie Kirkson (/mob/living/carbon/human), Charlie Kirkson (/mob/living/carbon/human), 1, "icon-x=18;icon-y=12;left=1;scr...")
[10:07:54]Charlie Kirkson (/mob/living/carbon/human): ClickOn(Charlie Kirkson (/mob/living/carbon/human), "icon-x=18;icon-y=12;left=1;scr...")
[10:07:54]Charlie Kirkson (/mob/living/carbon/human): Click(the floor (118,167,1) (/turf/open/floor/plasteel/red/side), "mapwindow.map", "icon-x=18;icon-y=12;left=1;scr...")```

This is the only stack trace I can find before it shit itself.

**Comment by PJB3005** [comment]
God that's basically unreadable, can you format it with proper block syntax? It's three ` before and after the code.

I'd paste it into a text editor if I weren't on my phone.

**Comment by LetterJay** [comment]
Sorry, swapping between Discord and Git. They both use different formatting.

**Comment by PJB3005** [comment]
Anyways that second runtime you posted is `getFlatIcon` not taking colour matrices into account. Your choice to make the camera ignore lighting overlays or to make get flat icon use `mapColors` when it detects the color of an object being a list.

**Comment by LetterJay** [comment]
Wait, was that a question or what? Need @unusualcrow to comment in, since he's the one working on lighting.

**Comment by PJB3005** [comment]
The "stack trace?" was me asking if I could get a stack trace to that runtime you posted.

**Comment by LetterJay** [comment]
I meant why you said in reference to the trace I posted

**Comment by LetterJay** [comment]
What*

**Comment by ghost** [comment]
I honestly have little to no understanding of the lighting system so
¯\_(ツ)_/¯¯\_(ツ)_/¯¯\_(ツ)_/¯

**Comment by LetterJay** [comment]
No stack trace found for it. Only thing I can find is it spewing out can't read null.x runtimes. Which point to

```	x = new_turf.x + (horizontal == EAST  ? 0.5 : -0.5)
	y = new_turf.y + (vertical   == NORTH ? 0.5 : -0.5)
```
in lighting_corner.dm

**Comment by LetterJay** [comment]
@PJB3005 most of it is here.

http://i.imgur.com/ZoQsFiK.png

**Comment by PJB3005** [comment]
That's an entirely different runtime though???

**Comment by PJB3005** [comment]
@LetterJay are you sure that's the code that actually *loads* the ruins though?

**Comment by PJB3005** [comment]
Also, could I get the runtime log files you're using here?

**Comment by LetterJay** [comment]
I'm gonna have to pastebin this in sections.

http://pastebin.com/WCHW7ifH [Part 1]
http://pastebin.com/9g8ePjEa [Part 2]

Beyond that it's just Bad List for two hours.

**Comment by LetterJay** [comment]
If you're asking for the file that loads the map, then no. Those are the files that random gen the areas in the map. Those random gen areas are the only ones failing to produce light.

**Comment by PJB3005** [comment]
The ruins being broken seems to be that the corners are incorrectly being marked as inactive which is...

I'm not even sure how that could happen honestly.

**Comment by LetterJay** [comment]
Was this lighting code originally made to work with randomly generate turf, though? I dunno if that has anything to do with it. I just know it works on any turf that isn't randomly generated.

**Comment by PJB3005** [comment]
As long as the random code correctly calls `ChangeTurf` it should be fine. The only way for corners to have lighting overlays and to not be activated is if something bypasses the correct code for building overlays which I highly doubt.

**Comment by PJB3005** [comment]
Alright I figured it out I think, working on a fix now.

**Comment by LetterJay** [comment]
Seems to have fixed it. Nice job. 

Fixed in https://github.com/Citadel-Station-13/Citadel-Station-13/commit/26086f39109d71c8d6f8be3c5c986e14f00342d9
