### ISSUE TITLE
Cult stuns no longer function

### ISSUE THREAD

**Issue by PersianXerxes** [citadel-station/citadel-main#9519]
## Testmerges:

#9503 

## Reproduction:

As of the tazer rework's merge, cult stuns (both blood and clockwork cult) no longer function. Cultists must bring stunprods or stunbatons in order to actually stun a victim for conversion, making the cults ineffective.

**Comment by deathride58** [comment]
This PR lacks detail. I'm unable to reproduce the bug mentioned, it seems like both cult stuns are working proper. Kindle simply hardstuns for 1.5 seconds (which is the current intended behavior), and bloodcult stuns force a strong knockdown and stamcrit (also intended behavior). Furthermore, these two things are completely separate code from tasers, meaning if these were affected by the taser rework branch, then there'd be a _lot_ more than just those two things broken.

**Comment by PersianXerxes** [comment]
In round ID: 19688, kindle was not applying the hard stun effect and was instead applying a knock down with stam loss only. However, as of round ID: 19705, kindle is now working as intended again.

While nothing has changed that should have affected this, I'm going to close this issue until I see reports of kindle working improperly again.
