### ISSUE TITLE
Lightning Bolt has no CD

### ISSUE THREAD

**Issue by Kersakof** [citadel-station/citadel-main#952]
How to test:
1. Pick a mage in ragin mages
2. Pick the spell lightning bolt
3. Cast it
It doesn't go on CD, and you can cast it as many times as you want. So you can kill entire rooms without them being unable to do anything unless they time stop.

> Blazeel (as Unknown) says, "UN'LTD`P'WAH"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD P'WAH"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD`P'WAH"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD P'WAH"
OOC: Noname979427: :ashdrake:
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD`P'WAH"
OOC: Eastwardrope: and everytime was because magic weapons
Blazeel (as Unknown) says, "TOKI`WO`TOMARE"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD P'WAH"
Blazeel (as Unknown) says, "FORTI`GY`AMA"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
OOC: Noname979427: :assdrake:
Blazeel (as Unknown) says, "UN'LTD P'WAH"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD P'WAH"
You energize your hand with arcane lightning!Left-click to shoot it at a target!
Blazeel (as Unknown) says, "UN'LTD P'WAH"
OOC: Noname979427: :meme:

**Comment by silicons** [comment]
this is
uh
most likely
my fuckup
from upstream
well
shit
eh
boys?
fuclk
fuck
fuck
fuck...

**Comment by Poojawa** [comment]
I don't think any of the wizard powers have cooldown tbh

**Comment by Kersakof** [comment]
By CD I mean I can spam it immediately after I cast it. The other wizard spells have like 5-60 seconds of CD. Lightning bolt says 15/15, but doesn't go to 0 after I case it, hence why I posted a 'sample.' I could kill an entire room within 5 seconds.

**Comment by silicons** [comment]
@Poojawa I assume you handled that borked PR and this is fixed?

**Comment by Poojawa** [comment]
I believe so. it was in the myriad of PRs
