### ISSUE TITLE
Abductor Tech Disk Interacts Oddly With Techweb

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#9657]
## Round ID:
19863

## Testmerges:
#9592: ' Porting movespeed modification system updates. ' by Ghommie at commit cb74be29ae
#7617: 'Eternalween' by DarkWolfInsanity at commit 71dadbe99e
#9533: 'RPD flipping works again' by JTGSZ at commit 9b7c7b6e0f
#9501: 'Borg buffs - Allows jaws to incapacitate, gives secborg a taser, and more! (wall of text in desc)' by deathride58 at commit f72d058eb5
#9631: 'Medibots now ACTUALLY heal slimes, rather than just not killing them (or how I learned binary logic the hard way)' by kevinz000 at commit 8f7270ea3e

## Reproduction:
Spawned abductor tech disk as a traitor scientist, inserted into R&D console, uploaded the technology present on the disk.  This allowed me to print alien alloy, but the Alien Tech node was listed as locked with a red point value despite having enough points.  This meant I could not proceed down the tree to Hazard Nanites.

**Comment by ghost** [comment]
could you try reproducing this yourself by any chance? it worked normal on my end

**Comment by IronEleven** [comment]
It seems like the behavior is only triggered when the disk is used after the prerequisites to Alien Technology are researched (Industrial Enginering and Biological Technology).

**Comment by ghost** [comment]
I tried that and it still worked for me, which is odd. must be something else conflicting with it

**Comment by ghost** [comment]
or a testmerge

**Comment by IronEleven** [comment]
I downloaded a copy of the master branch just before testing, only other thing that I've noticed is that uploading the tech from the disk a second time seems to be a workaround.
