### ISSUE TITLE
Changing status displays doesn't always work.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9731]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
The 'Biohazard' 'Red Alert' and a few other settings don't display when selected.

**Comment by GrayRachnid** [comment]
Found the difference. `/status_display/evac` seems to work fine and shows status display changes. but `/status_display` does nothing other than show evac time.

**Comment by Tupinambis** [comment]
Fixed by #10796. Thanks
