### ISSUE TITLE
You actually cannot alt+click a tile again to close the floor menu list

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9758]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Alt click a tile, it shows you a list of items. Alt click it again, it doesn't close. In the past, you could alt click again to close it. Now, this isn't an issue for your normal everyday player because all you have to do is move away from the tile and it'll auto-close, but. You can't do that as AI. If an AI alt clicks a tile it permanently keeps that tile open and in vision, which is somewhat intended, but you can't close it after which is annoying because sometimes I don't want a tile permanently open due to the fact that it takes an extra tab space.

**Comment by SandPoot** [comment]
As i know, there was some pr saying that it was a bug and should stay open if alt clicked again, and as AI i’m pretty sure you can’t do that the same way you can’t examine
