### ISSUE TITLE
Fireman Carry bug has returned.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9787]
Issue reported from  Round ID: 20059 (Citadel Station 13)

Reporting client version: 512

Fireman Carry bug (Highlighted here) is back.

https://github.com/Citadel-Station-13/Citadel-Station-13/issues/9429

**Comment by Ghommie** [comment]
I accidentally broke it when refactoring how riding offhands are handled, it is being fixed on #9723 already.
