### ISSUE TITLE
Xeno acid appears to not work on structures.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9792]
## Round ID:
20069

## Testmerges:
#9557: 'Dynamic voting (needs testing)' by Putnam3145 at commit d381be7f07
#9628: '[Ready] [Testmerge] MK II Cargo Rework - Sell harder edition ' by Trilbyspaceclone at commit 6e328ea1b1
#9625: 'Unmodularize digi/muzzled clothing sprites.' by Ghommie at commit b7364a1e8a
#9711: 'Reverts carbon based hat throwning - Aka hat throwing only works on borgs' by Trilbyspaceclone at commit 3880c68944
#9748: 'Makes science fun' by lolman360 at commit 67cdbd954d

## Reproduction:
Watched a xeno drone acid a reinforced window and a reinforced wall. They only acided each once. It's my understanding that you put the acid on and then you leave it to melt. It kept melting with the acid on for over 10 minutes and nothing had changed to either the wall or window.

**Comment by Ghommie** [comment]
reinforced walls/windows being so sturdy against xenomorph acid is a feature, not an issue.
Normal walls and windows are still quite susceptible to it.

**Comment by GrayRachnid** [comment]
Hmm, alright I'll close this issue then.
