### ISSUE TITLE
Wizard cannot teleport to the station from the Wizard Den.

### ISSUE THREAD

**Issue by 2birdie** [citadel-station/citadel-main#9848]
## Round ID:
#20146

## Testmerges:
#9825: '[TESTMERGE ONLY] Revert "Porting multi-z support updates."' by kevinz000 at commit 60ff65fb67
#9748: 'Makes science fun' by lolman360 at commit 67cdbd954d
#9711: 'Reverts carbon based hat throwning - Aka hat throwing only works on borgs' by Trilbyspaceclone at commit d31b42b1e9
#9625: 'Unmodularize digi/muzzled clothing sprites.' by Ghommie at commit c7a3652d0a
#9806: 'Borg changes. Compresses Service/Janitor/Scrubpuppy borgs together. Removes borgi. Adds vore sleepers to service and engi dogborgs. Demodularizes some dogborg stuff too.' by BlackMajor at commit 0c33757b14
#9818: 'Ports the Saboteur borg for nukeops and new cyborg tools/weapon icons.' by GrayRachnid at commit c1dfa4227b
#9826: '[Test Merge] Revert "ID console fixes and other tweaks."' by Trilbyspaceclone at commit 66c76e8553

## Reproduction:
Hello!
I was chosen to be a Wizrobe, and ran over to the mystical mirror. It was there that I changed my race to vampire! I'm not sure if I bat formed before using a magical whistle, but it did not function properly, in any case. The tornado rolled through after I placed the artifact wind instrument into my backpack, nothing happened.
Later, and some race changes later, neither my teleport scroll nor my teleport spell would move me! The spell did billow out smoke, however. Subtumaka teleported me where I wanted to go by the end, and the teleport spell functioned as expected while on station.

More concisely.
>be wizard
>magic mirror into vampire
>forgot if i bat formed
>used magic whistle and put it in my backpack. the tornado rolled across the screen but i did not move.
>play with races more
>teleport scroll and spell did not move me. worked when on station through admin assistance.

**Comment by Ghommie** [comment]
About the scroll, were you still holding it by the time you selected the location as intended, or did you backpack it just like the warp whistle?

**Comment by 2birdie** [comment]
I believe I put it in my pocket, but it might have went into the backpack.

**Comment by Ghommie** [comment]
Well then, tele scroll isn't broken.
