### ISSUE TITLE
The magical wizard mirror at the wizard's den can grant bat form to non-vampires.

### ISSUE THREAD

**Issue by 2birdie** [citadel-station/citadel-main#9849]
## Round ID:
#20146

## Testmerges:
#9825: '[TESTMERGE ONLY] Revert "Porting multi-z support updates."' by kevinz000 at commit 60ff65fb67
#9748: 'Makes science fun' by lolman360 at commit 67cdbd954d
#9711: 'Reverts carbon based hat throwning - Aka hat throwing only works on borgs' by Trilbyspaceclone at commit d31b42b1e9
#9625: 'Unmodularize digi/muzzled clothing sprites.' by Ghommie at commit c7a3652d0a
#9806: 'Borg changes. Compresses Service/Janitor/Scrubpuppy borgs together. Removes borgi. Adds vore sleepers to service and engi dogborgs. Demodularizes some dogborg stuff too.' by BlackMajor at commit 0c33757b14
#9818: 'Ports the Saboteur borg for nukeops and new cyborg tools/weapon icons.' by GrayRachnid at commit c1dfa4227b
#9826: '[Test Merge] Revert "ID console fixes and other tweaks."' by Trilbyspaceclone at commit 66c76e8553

## Reproduction:
If one becomes a vampire with the magical mirror and uses bat form (it might happen without using it, too?) followed by becoming a spaceskeleton (and maybe other races?), the user will keep bat form, and be able to swap forms normally.
Also, space bats of this sort can use the force wall spell if they have it, though I'm hesitant to say that's a bug. It's fun.

**Comment by DeltaFire15** [comment]
I fixed this.
