### ISSUE TITLE
Medical HUD does show dead people.

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9854]
Issue reported from  Round ID: 20151 (Citadel Station 13)

Reporting client version: 512

![image](https://user-images.githubusercontent.com/7543955/69020231-cfcd7080-0981-11ea-8777-5e7394ca5306.png)

If someone is dead for too long the HUD is supposed to show that they can no longer be revived, this but they stay in this state forever.

**Comment by Ghommie** [comment]
The defib grace time was rised from 2 minutes to 25 (for reference, tgstation's is 15 minutes) some time ago following the organs rework port.
That said, it'd take a while to confirm and replicate this issue.

**Comment by Owai-Seek** [comment]
25? Dear god. Do all of their organs just die off during that time?

If so, is there a way to tell the HUD that they are too organ damaged to fix?

**Comment by GrayRachnid** [comment]
you can still defib them in this state by bringing their body heat down to 140k

**Comment by Thalpy** [comment]
There should be a lil heart icon underneath if their heart is too damaged to defib them. You'll have to perform either a coronary bypass/Emergency Cardioversion Induction surgery or inject them with a Oligopotent Synthtissue Colony to repair their heart to defibbable levels (read the book that should appear soon for more details). If their brain is too far gone, an injection of neurine or Emergency Cardioversion Induction will fix that too. Basically, using Emergency Cardioversion Induction will revive anyone with that symbol.
