### ISSUE TITLE
Borgs still cannot use camera consoles.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9890]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Be borg, touch console. No bueno.

**Comment by SandPoot** [comment]
weird bug, as borg i could use xeno console though

**Comment by Ghommie** [comment]
That's because normal camera consoles and advanced camera consoles are of different types (`obj/machinery/computer/security` vs `obj/machinery/computer/camera_advanced`), differently coded.
