### ISSUE TITLE
HUD Temperature icon is flipped

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9927]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Shows too cold for hot and too hot for cold.

**Comment by Putnam3145** [comment]
see https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9770, which fixes this

**Comment by MarinaGryphon** [comment]
hey it's just a logic flip, `loc_temp-H.bodytemperature` should be`H.bodytemperature-loc_temp`

**Comment by MarinaGryphon** [comment]
> hey it's just a logic flip, `loc_temp-H.bodytemperature` should be`H.bodytemperature-loc_temp`

actually im dumbass
