### ISSUE TITLE
Bo staff Disarm is wonky.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9930]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Hit someone while on disarm intent with Bo staff, their stamina drops. Get error message that you cannot attack them while they are down when they're still standing.

**Comment by Ghommie** [comment]
Turns out the message was about being unable to attack mobs who can't retaliate, as in, are unconscious, in soft crit or dead. It's totally possible for a mob to be unconscious while buckled to a chair or something.
