### ISSUE TITLE
HoP console still does not have an ID check.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9949]
## Round ID:
20286

## Testmerges:
BYOND Version: 512.1484
Server revision compiled on: 
The following pull requests are currently test merged:
#9872: '[READY] Plumbing' by lolman360 at commit 2d033c37d3
#9922: 'Ports new Brain Traumas from /tg/. Does not include the shitty creeper antag or Wizard Traumas, i'm porting wizard traumas later. Also adds the Desynchronizer and changes the way some heaRing args are handled.' by GrayRachnid at commit 0b60d5e6ef
#9892: '[TESTMERGE] Fully demodularizes Knockdown() and updates it for rework' by Putnam3145 at commit db2ae83963
#9894: '[TESTMERGE] Explosion/bomb armor rework' by Putnam3145 at commit c40cad1658
#9884: 'Black powder fix. Alternative to #9861' by Useroth at commit b91d0e27da
#9319: 'Captain can now be converted in CWC/Bloodcult without a mindshield' by jakeramsay007 at commit 37b7963076
#9748: 'Makes science fun' by lolman360 at commit 67cdbd954d
#9711: 'Reverts carbon based hat throwning - Aka hat throwing only works on borgs' by Trilbyspaceclone at commit d31b42b1e9
#9815: '[READY] Syndicate battledroids.' by lolman360 at commit b26b10a9f0
#9372: '[Ready] [Test Merge] Ports Xenobio Hotkeys' by Weblure at commit 3dac695d53
#9575: 'Box Beautification & Bar Rework & Issue 9706 Fix' by KathrinBailey at commit 9ee4acd143

## Reproduction:
Put an ID in the 'target' slot and leave the 'Confirm Identity' slot empty. You can add and remove access.

@Ghommie

**Comment by GrayRachnid** [comment]
Correction, the issue is that once you're "Logged in" it doesn't auto-log out when you remove the ID.

**Comment by Ghommie** [comment]
Yes, it doesn't auto-log out anymore. That's an intended change they did on tgstation a while ago for consistency with other consoles with access requirements, I even mentioned it on the last (or was it second to last) related PR.
Nevertheless I can make a quick "emojicracy" vote on the discord for that.

**Comment by GrayRachnid** [comment]
Yeah I guess if it's intended it's fine, i'll close this though.
