### ISSUE TITLE
Port all the new donuts from /tg/

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9952]
![image](https://user-images.githubusercontent.com/6613514/69681600-916c3b80-107c-11ea-9ba8-b993cece607f.png)

**Comment by Linzolle** [comment]
you do it

**Comment by GrayRachnid** [comment]
I would have if I wanted to, instead I leave it as an offering for a rookie

**Comment by GrayRachnid** [comment]
i'm such a positive influence trust me this is not because i'm lazy

**Comment by YakumoChen** [comment]
I don't think we have some of those plants

**Comment by Ghommie** [comment]
Not an issue. Trilby is already working on the port too (which is pretty much fine at a glance), so don't worry about it.
Also the new sprites look yummy, ngl.
