### ISSUE TITLE
Metastation Interrogation room Telescreen is silly.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9963]
![image](https://user-images.githubusercontent.com/6613514/69756045-94703600-1127-11ea-8ee3-9bd6090e87cb.png)

**Comment by Ghommie** [comment]
Never used nor cared about the interrogation room personally, what's that telescreen for? Watching the interrogation side of this area?

**Comment by GrayRachnid** [comment]
Yup
