### ISSUE TITLE
Looking through a camera does not show gas particles.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9978]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
A good example would be to look at the atmos cameras and you'll notice that the N2O and Plasma tanks don't have their particles.

**Comment by GrayRachnid** [comment]
..Turns out it's a higgs-buggson.

**Comment by DeltaFire15** [comment]
Cameras have been reworked, this is probably gone
